"use client";

import { useState } from 'react';
import { pageGeneratorAgent, type PageDesign, type GeneratedPage } from '@/agents/pageGenerator.agent';

export default function AIGeneratorDemo() {
  const [generating, setGenerating] = useState(false);
  const [result, setResult] = useState<GeneratedPage | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Example design data
  const exampleDesign: PageDesign = {
    title: "My First Custom Page",
    description: "A fun interactive page!",
    backgroundColor: "#fef3c7",
    elements: [
      {
        type: 'text',
        id: 'title',
        x: 100,
        y: 50,
        width: 400,
        height: 60,
        content: 'Welcome to My Page! 🎉',
        style: {
          fontSize: 32,
          color: '#1e40af',
          fontWeight: 'bold',
        }
      },
      {
        type: 'shape',
        id: 'circle1',
        x: 150,
        y: 150,
        width: 100,
        height: 100,
        style: {
          shape: 'circle',
          backgroundColor: '#3b82f6',
        }
      },
      {
        type: 'button',
        id: 'btn1',
        x: 200,
        y: 300,
        width: 200,
        height: 50,
        content: 'Click Me! 🚀',
        action: 'celebrate'
      },
      {
        type: 'text',
        id: 'desc',
        x: 100,
        y: 400,
        width: 500,
        height: 40,
        content: 'This page was generated by AI!',
        style: {
          fontSize: 18,
          color: '#4b5563',
        }
      }
    ]
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setError(null);
    setResult(null);

    try {
      console.log('🚀 Starting AI generation...');
      const generated = await pageGeneratorAgent.generatePage(exampleDesign);
      console.log('✅ Generation complete!', generated);
      setResult(generated);
    } catch (err) {
      console.error('❌ Generation failed:', err);
      setError(err instanceof Error ? err.message : 'Unknown error');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-purple-500 via-pink-500 to-orange-500 p-8">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <div className="bg-white/95 backdrop-blur-sm rounded-3xl shadow-2xl p-8 mb-6">
          <h1 className="text-4xl font-black text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-purple-600 mb-4">
            🤖 AI Page Generator Demo
          </h1>
          <p className="text-gray-700 mb-6">
            Watch the AI convert visual design data into a working React component!
          </p>

          {/* Generate Button */}
          <button
            onClick={handleGenerate}
            disabled={generating}
            className={`px-8 py-4 bg-gradient-to-r from-blue-500 to-purple-500 text-white font-bold rounded-xl shadow-lg transform transition-all duration-200 ${
              generating ? 'opacity-50 cursor-not-allowed' : 'hover:scale-105'
            }`}
          >
            {generating ? (
              <span className="flex items-center gap-2">
                <div className="w-5 h-5 border-3 border-white border-t-transparent rounded-full animate-spin" />
                AI is thinking... 🧠
              </span>
            ) : (
              '✨ Generate Page with AI'
            )}
          </button>
        </div>

        {/* Design Preview */}
        <div className="bg-white/95 backdrop-blur-sm rounded-3xl shadow-2xl p-8 mb-6">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">📐 Input Design Data</h2>
          <div className="bg-gray-50 rounded-xl p-4 overflow-x-auto">
            <pre className="text-sm text-gray-700">
              {JSON.stringify(exampleDesign, null, 2)}
            </pre>
          </div>
        </div>

        {/* Error Display */}
        {error && (
          <div className="bg-red-50 border-2 border-red-500 rounded-3xl p-6 mb-6">
            <h3 className="text-xl font-bold text-red-700 mb-2">❌ Error</h3>
            <p className="text-red-600">{error}</p>
          </div>
        )}

        {/* Results Display */}
        {result && (
          <>
            {/* Metadata */}
            <div className="bg-white/95 backdrop-blur-sm rounded-3xl shadow-2xl p-8 mb-6">
              <h2 className="text-2xl font-bold text-gray-800 mb-4">📊 Generation Metadata</h2>
              <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
                <div className="bg-blue-50 rounded-xl p-4">
                  <div className="text-sm text-blue-600 font-bold">Elements</div>
                  <div className="text-2xl font-black text-blue-800">{result.metadata.elementsUsed}</div>
                </div>
                <div className="bg-purple-50 rounded-xl p-4">
                  <div className="text-sm text-purple-600 font-bold">Complexity</div>
                  <div className="text-2xl font-black text-purple-800">{result.metadata.complexity}</div>
                </div>
                <div className="bg-green-50 rounded-xl p-4">
                  <div className="text-sm text-green-600 font-bold">Size</div>
                  <div className="text-2xl font-black text-green-800">{result.metadata.estimatedSize}</div>
                </div>
                <div className="bg-orange-50 rounded-xl p-4">
                  <div className="text-sm text-orange-600 font-bold">Warnings</div>
                  <div className="text-2xl font-black text-orange-800">{result.metadata.warnings?.length || 0}</div>
                </div>
              </div>

              {result.metadata.warnings && result.metadata.warnings.length > 0 && (
                <div className="mt-4 bg-yellow-50 rounded-xl p-4">
                  <div className="text-sm font-bold text-yellow-800 mb-2">⚠️ Warnings:</div>
                  <ul className="text-sm text-yellow-700 space-y-1">
                    {result.metadata.warnings.map((warning, i) => (
                      <li key={i}>• {warning}</li>
                    ))}
                  </ul>
                </div>
              )}
            </div>

            {/* Generated Component Code */}
            <div className="bg-white/95 backdrop-blur-sm rounded-3xl shadow-2xl p-8 mb-6">
              <h2 className="text-2xl font-bold text-gray-800 mb-4">💻 Generated Component Code</h2>
              <div className="bg-gray-900 rounded-xl p-4 overflow-x-auto">
                <pre className="text-sm text-green-400 font-mono">
                  {result.componentCode}
                </pre>
              </div>
              <button
                onClick={() => {
                  navigator.clipboard.writeText(result.componentCode);
                  alert('Code copied to clipboard! 📋');
                }}
                className="mt-4 px-6 py-3 bg-gradient-to-r from-green-500 to-emerald-500 text-white font-bold rounded-xl hover:scale-105 transform transition-all duration-200 shadow-lg"
              >
                📋 Copy Code
              </button>
            </div>

            {/* HTML Preview */}
            <div className="bg-white/95 backdrop-blur-sm rounded-3xl shadow-2xl p-8">
              <h2 className="text-2xl font-bold text-gray-800 mb-4">👁️ Live Preview</h2>
              <div 
                className="border-4 border-gray-300 rounded-xl overflow-hidden"
                style={{ minHeight: '500px' }}
                dangerouslySetInnerHTML={{ __html: result.preview }}
              />
            </div>
          </>
        )}

        {/* How It Works */}
        <div className="bg-white/95 backdrop-blur-sm rounded-3xl shadow-2xl p-8 mt-6">
          <h2 className="text-2xl font-bold text-gray-800 mb-4">🧠 How The AI Works</h2>
          <div className="space-y-4 text-gray-700">
            <div className="flex gap-4">
              <div className="text-3xl">1️⃣</div>
              <div>
                <strong className="text-blue-600">Analyzes Design:</strong> The AI looks at all your shapes, text, and buttons to understand what you&apos;re building.
              </div>
            </div>
            <div className="flex gap-4">
              <div className="text-3xl">2️⃣</div>
              <div>
                <strong className="text-purple-600">Detects Patterns:</strong> It finds patterns like headers, rows, grids, and button groups.
              </div>
            </div>
            <div className="flex gap-4">
              <div className="text-3xl">3️⃣</div>
              <div>
                <strong className="text-green-600">Generates Code:</strong> Uses CodeLlama AI (or smart templates) to create clean React components.
              </div>
            </div>
            <div className="flex gap-4">
              <div className="text-3xl">4️⃣</div>
              <div>
                <strong className="text-orange-600">Validates & Optimizes:</strong> Checks the code for errors and adds kid-friendly styling!
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
