interface Question {
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

interface TopicLesson {
  id: number;
  title: string;
  icon: string;
  description: string;
  content: string[];
  questions: Question[];
}

export const lessons: { [key: number]: TopicLesson } = {
  502: {
    id: 502,
    title: 'Making Inferences',
    icon: '🔍',
    description: 'Reading between the lines',
    content: [
      "Time to become a READING DETECTIVE! 🔍 Let's learn about INFERENCES!",
      "Authors don't always tell you EVERYTHING directly!",
      "Sometimes you have to READ BETWEEN THE LINES!",
      "This is called making an INFERENCE!",
      "WHAT IS AN INFERENCE? 🤔",
      "An inference is a SMART GUESS based on clues!",
      "It's figuring out something that's NOT directly said!",
      "Formula: TEXT CLUES + YOUR KNOWLEDGE = INFERENCE!",
      "Example:",
      "'Maya's stomach rumbled loudly. She looked at the clock - 12:30. The cafeteria smelled amazing.'",
      "The text doesn't SAY Maya is hungry...",
      "But you can INFER it!",
      "Clue 1: Stomach rumbling",
      "Clue 2: Lunchtime (12:30)",
      "Clue 3: Good food smells",
      "Your knowledge: Rumbling stomach = hungry!",
      "Inference: Maya is hungry! 🎯",
      "WHY DO AUTHORS DO THIS? 📖",
      "Authors want writing to be INTERESTING, not boring!",
      "Instead of saying 'Jake was scared'...",
      "They might write: 'Jake's hands trembled. His heart raced. He couldn't move.'",
      "More exciting! You get to figure it out!",
      "Makes you THINK about what you're reading!",
      "Creates a picture in your mind!",
      "TYPES OF CLUES: 🕵️",
      "1. ACTION CLUES:",
      "'Emma slammed the door and stomped upstairs.'",
      "Actions show feelings - she's probably angry!",
      "2. DESCRIPTION CLUES:",
      "'Dark clouds filled the sky. The wind picked up. Birds flew away quickly.'",
      "Describes a situation - storm is coming!",
      "3. DIALOGUE CLUES (what characters say):",
      "'I studied for HOURS!' said Tom with a big smile.",
      "He's probably proud or confident!",
      "4. SETTING CLUES:",
      "'Leaves crunched underfoot. The air felt crisp. Pumpkins sat on porches.'",
      "Details tell you it's probably autumn/fall!",
      "INFERENCE vs GUESS: What's the Difference? 🎲",
      "RANDOM GUESS: No evidence, just picking anything!",
      "'The character is an alien!' (No clues support this!)",
      "INFERENCE: Based on clues from the text!",
      "'The character is sad' (because text says they're crying)",
      "Inferences MUST be supported by the text!",
      "Always ask: What evidence do I have?",
      "PRACTICING WITH EXAMPLES: 📚",
      "Example 1:",
      "'The teacher handed back tests. Lisa's face lit up. She showed her paper to her friend.'",
      "What can you infer?",
      "Lisa probably did WELL on the test!",
      "Evidence: Face lit up (happy), showed friend (proud!)",
      "Example 2:",
      "'Ben packed his swim trunks, towel, and sunscreen. He couldn't wait for tomorrow!'",
      "What can you infer?",
      "Ben is going swimming tomorrow, probably at a pool or beach!",
      "Evidence: Swimming items, excited about tomorrow!",
      "Example 3:",
      "'The playground was empty. Backpacks filled the classrooms. The hallways were quiet.'",
      "What can you infer?",
      "School is in session - kids are in class learning!",
      "Evidence: Empty playground, full classrooms, quiet halls!",
      "USING YOUR BACKGROUND KNOWLEDGE: 🧠",
      "Inferences need TWO things:",
      "1. Clues from the TEXT",
      "2. What YOU already KNOW (background knowledge!)",
      "Example:",
      "'Sarah grabbed her umbrella before heading out.'",
      "Text clue: Taking umbrella",
      "Your knowledge: Umbrellas protect from rain!",
      "Inference: It's probably raining or about to rain!",
      "The more you know, the better your inferences!",
      "Reading helps you learn more, which helps you infer better!",
      "CHARACTER FEELINGS: 😊😢😠",
      "Characters' feelings are often NOT stated directly!",
      "You infer them from actions, words, and descriptions!",
      "CLUE: 'Alex's eyes filled with tears.'",
      "INFERENCE: Alex is sad or hurt!",
      "CLUE: 'Jamie jumped up and down, cheering loudly.'",
      "INFERENCE: Jamie is excited or happy!",
      "CLUE: 'Ryan crossed his arms and looked away.'",
      "INFERENCE: Ryan is upset, angry, or doesn't want to participate!",
      "Look for body language clues - they reveal feelings!",
      "PREDICTING WHAT HAPPENS NEXT: 🔮",
      "Inferences help you PREDICT future events!",
      "'Dark clouds gathered. Lightning flashed in the distance. People hurried inside.'",
      "Inference about NOW: A storm is approaching!",
      "Prediction about NEXT: It will probably start raining soon!",
      "Good readers constantly make predictions!",
      "CHECKING YOUR INFERENCES: ✅",
      "Not all inferences are correct - check them!",
      "Question 1: What clues support my inference?",
      "List the evidence!",
      "Question 2: Does my inference make SENSE?",
      "Is it logical based on the clues?",
      "Question 3: Am I adding ideas NOT in the text?",
      "Stick to what's supported by evidence!",
      "Question 4: Could there be another explanation?",
      "Sometimes multiple inferences are possible!",
      "COMMON MISTAKES: ⚠️",
      "Mistake 1: Going TOO FAR!",
      "Text: 'Mike loves dogs.'",
      "Bad inference: 'Mike wants to be a veterinarian!'",
      "That's too much! Just because he loves dogs doesn't mean he wants that career!",
      "Mistake 2: IGNORING the text!",
      "Making guesses based on what YOU think, not what the text says!",
      "Always use text evidence!",
      "Mistake 3: Using JUST background knowledge!",
      "Text: 'The cat meowed.'",
      "Bad: 'The cat is evil!' (No text evidence!)",
      "Good: 'The cat might want food or attention!' (Common cat behavior!)",
      "INFERENCE IN DIFFERENT TYPES OF TEXTS: 📕📰",
      "STORIES/FICTION:",
      "Infer characters' feelings, motivations, relationships!",
      "Predict what happens next in the plot!",
      "Figure out themes and lessons!",
      "INFORMATIONAL/NON-FICTION:",
      "Infer causes and effects not directly stated!",
      "Make connections between facts!",
      "Predict outcomes based on information!",
      "POETRY:",
      "Infer meaning from imagery and metaphors!",
      "Figure out the poet's feelings or message!",
      "Connect symbols to bigger ideas!",
      "PRACTICE SCENARIO 1: 🏀",
      "'Coach blew the whistle. The team gathered around. Everyone was breathing hard and covered in sweat. They high-fived each other and grabbed water bottles.'",
      "What can you infer?",
      "The team just finished practice or a game!",
      "Evidence: Whistle, breathing hard, sweaty, water break!",
      "PRACTICE SCENARIO 2: 🎂",
      "'Mom hid something behind her back. She had a big smile. The house smelled like vanilla and frosting. Everyone said \"Shh!\" when footsteps approached.'",
      "What can you infer?",
      "It's probably someone's BIRTHDAY surprise!",
      "Evidence: Hiding something, cake smell, everyone quiet, surprise element!",
      "PRACTICE SCENARIO 3: 🌙",
      "'Owl hooted in the distance. The street lights flickered on. Stars began to appear in the darkening sky.'",
      "What can you infer?",
      "It's becoming nighttime - evening/dusk!",
      "Evidence: Owl (nocturnal), lights turning on, stars appearing, darkening!",
      "MAKING INFERENCES ABOUT CAUSE & EFFECT: ⚡",
      "Sometimes you infer WHY something happened!",
      "TEXT: 'The ground was wet. Puddles were everywhere.'",
      "EFFECT: Ground is wet",
      "INFERRED CAUSE: It probably rained recently!",
      "TEXT: 'Everyone in class was yawning.'",
      "EFFECT: Students yawning",
      "INFERRED CAUSE: Maybe they're tired, boring lesson, or early morning!",
      "VISUALIZING HELPS: 🎨",
      "Create a PICTURE in your mind as you read!",
      "This helps you notice clues!",
      "Imagine the scene - what do you see, hear, smell?",
      "Your mental picture reveals inferences!",
      "INFERENCE STRATEGY: 3 STEPS! 🪜",
      "STEP 1: FIND THE CLUES!",
      "What does the text tell you?",
      "Underline or note important details!",
      "STEP 2: THINK ABOUT WHAT YOU KNOW!",
      "What do you already know about this situation?",
      "Connect text to your experiences!",
      "STEP 3: PUT IT TOGETHER!",
      "Combine text clues + your knowledge = inference!",
      "Check: Does it make sense?",
      "Remember: Good readers are always inferring! 🔍",
      "The more you practice, the easier it gets!",
      "Look for clues, think about what you know, and make smart guesses!",
      "Reading becomes more fun when you're a detective! 🕵️‍♀️"
    ],
    questions: [
      {
        question: "Sarah looked at her empty plate and frowned. What can you infer?",
        options: ["She's full", "She wanted more food", "She doesn't like plates", "She's tired"],
        correctAnswer: 1,
        explanation: "You can infer Sarah wanted more food! Empty plate + frowning = disappointed there's no more. Great detective work!"
      },
      {
        question: "What is an inference?",
        options: ["Reading the title", "A smart guess based on clues", "The main idea", "A vocabulary word"],
        correctAnswer: 1,
        explanation: "An inference is a smart guess based on CLUES from the text plus what you already know! It's reading between the lines!"
      },
      {
        question: "'Tom shivered and pulled his coat tighter.' What can you infer?",
        options: ["It's cold", "He's hot", "He's hungry", "He likes coats"],
        correctAnswer: 0,
        explanation: "You can infer it's COLD! Shivering and pulling coat tighter are clues that someone is trying to stay warm!"
      },
      {
        question: "What two things do you need to make an inference?",
        options: ["Title and pictures", "Text clues and your knowledge", "Main idea and details", "Beginning and end"],
        correctAnswer: 1,
        explanation: "You need TEXT CLUES + YOUR BACKGROUND KNOWLEDGE! Together they help you figure out what's not directly stated!"
      },
      {
        question: "'The team high-fived and cheered. They held up a trophy.' What can you infer?",
        options: ["They lost", "They won", "They're practicing", "They're angry"],
        correctAnswer: 1,
        explanation: "You can infer they WON! Cheering and holding a trophy are clues of victory and happiness!"
      },
      {
        question: "What's the difference between an inference and a random guess?",
        options: ["No difference", "Inferences use text evidence", "Guesses are always right", "Inferences are shorter"],
        correctAnswer: 1,
        explanation: "Inferences use TEXT EVIDENCE and clues! Random guesses have no support. Inferences MUST be based on what's in the text!"
      },
      {
        question: "'Mom hid something behind her back and smiled. The house smelled like cake.' What can you infer?",
        options: ["Mom is baking bread", "It's probably someone's birthday", "Mom is hiding vegetables", "It's time for dinner"],
        correctAnswer: 1,
        explanation: "You can infer it's probably someone's BIRTHDAY! Clues: hiding something (surprise), smiling, cake smell - all point to a birthday celebration!"
      },
      {
        question: "Making inferences is like being a:",
        options: ["Chef", "Detective", "Artist", "Athlete"],
        correctAnswer: 1,
        explanation: "Making inferences is like being a DETECTIVE! You look for clues in the text and figure out information that's not directly stated!"
      }
    ]
  },
  503: {
    id: 503,
    title: 'Story Elements',
    icon: '📚',
    description: 'Parts that make up a story',
    content: [
      "Welcome to the world of STORIES! 📚 Let's explore what makes them work!",
      "Every story has INGREDIENTS - like a recipe!",
      "These ingredients are called STORY ELEMENTS!",
      "Understanding them helps you read better and write better stories!",
      "THE 5 MAIN STORY ELEMENTS: 🌟",
      "1. CHARACTERS 👥",
      "2. SETTING 🏙️",
      "3. PLOT 📈",
      "4. CONFLICT (PROBLEM) ⚡",
      "5. THEME/MESSAGE 💭",
      "Let's explore each one!",
      "ELEMENT #1: CHARACTERS! 👥",
      "Characters are the WHO of the story!",
      "They're the people, animals, or creatures in the story!",
      "MAIN CHARACTER (protagonist): The story is ABOUT them!",
      "Also called the HERO or main person!",
      "Example: Harry Potter, Katniss, Matilda!",
      "SUPPORTING CHARACTERS: Help or interact with main character!",
      "Friends, family, teachers, neighbors!",
      "ANTAGONIST: Works AGAINST the main character!",
      "The villain or person causing problems!",
      "Example: Voldemort, the Evil Queen!",
      "Note: Not all stories have a villain!",
      "CHARACTER TRAITS: What are they LIKE?",
      "Brave, shy, funny, smart, kind, mean, curious!",
      "Traits explain WHY characters do things!",
      "A brave character faces danger!",
      "A curious character asks questions!",
      "ELEMENT #2: SETTING! 🏙️",
      "Setting is the WHERE and WHEN of the story!",
      "WHERE: Location!",
      "A school, a castle, a forest, outer space, underwater!",
      "A city, small town, farm, magical land!",
      "Be specific: Not just \"a house\" but \"an old creaky house on a hill\"!",
      "WHEN: Time!",
      "Modern day, past (historical), future!",
      "A specific year like 1920, or time period like Medieval times!",
      "Time of day: morning, midnight!",
      "Season: winter, summer!",
      "WHY SETTING MATTERS:",
      "Setting affects what can happen!",
      "A space station story is different from a farm story!",
      "Winter setting = snowstorms possible!",
      "Medieval setting = no phones or cars!",
      "Setting creates MOOD (feeling)!",
      "Dark forest = spooky!",
      "Sunny beach = happy, relaxed!",
      "ELEMENT #3: PLOT! 📈",
      "Plot is WHAT HAPPENS in the story!",
      "It's the SEQUENCE of events!",
      "Every plot follows a pattern - PLOT STRUCTURE!",
      "THE PLOT MOUNTAIN: ⛰️",
      "1. BEGINNING (Exposition):",
      "Introduces characters and setting!",
      "Shows normal life before the adventure!",
      "Example: Harry lives with mean relatives!",
      "2. RISING ACTION:",
      "Problem appears!",
      "Things start happening!",
      "Tension builds!",
      "Characters try to solve problem!",
      "Example: Harry goes to Hogwarts, learns about Voldemort!",
      "This is usually the LONGEST part!",
      "3. CLIMAX (The Peak!):",
      "The MOST EXCITING part!",
      "The BIG moment!",
      "The turning point!",
      "Characters face the biggest challenge!",
      "Example: Final battle or big confrontation!",
      "4. FALLING ACTION:",
      "Things wind down after the climax!",
      "Consequences of the big moment!",
      "Loose ends start tying up!",
      "5. RESOLUTION (Ending/Conclusion):",
      "Problem is SOLVED!",
      "New normal is established!",
      "Characters have learned or changed!",
      "Example: Hero wins, peace is restored!",
      "ELEMENT #4: CONFLICT (The Problem!) ⚡",
      "Conflict is the PROBLEM or CHALLENGE!",
      "Without conflict, there's NO STORY!",
      "Conflict drives the plot forward!",
      "TYPES OF CONFLICT:",
      "1. CHARACTER vs CHARACTER:",
      "Fighting against another person!",
      "Hero vs Villain!",
      "Example: Harry vs Voldemort!",
      "2. CHARACTER vs NATURE:",
      "Fighting against natural forces!",
      "Storms, animals, wilderness!",
      "Example: Surviving on a deserted island!",
      "3. CHARACTER vs SELF:",
      "INTERNAL struggle - fighting own fears, doubts, or decisions!",
      "Overcoming shyness, making hard choices!",
      "Example: Character deciding whether to tell the truth!",
      "4. CHARACTER vs SOCIETY:",
      "Fighting against rules, traditions, or groups!",
      "Standing up for what's right!",
      "Example: Fighting for equality!",
      "5. CHARACTER vs TECHNOLOGY:",
      "Fighting against machines or AI!",
      "Example: Robots taking over!",
      "6. CHARACTER vs SUPERNATURAL:",
      "Fighting against magic, ghosts, gods!",
      "Example: Battling a curse!",
      "Stories can have MULTIPLE conflicts!",
      "ELEMENT #5: THEME/MESSAGE! 💭",
      "Theme is the BIG IDEA or LESSON of the story!",
      "What's the story REALLY about?",
      "Not just plot - the deeper meaning!",
      "Common themes:",
      "- Friendship is important",
      "- Be yourself",
      "- Good vs Evil",
      "- Don't judge by appearances",
      "- Hard work pays off",
      "- Family matters",
      "- Courage in the face of fear",
      "- Never give up",
      "Theme is usually NOT stated directly!",
      "You figure it out from the story!",
      "Ask: What did the character learn?",
      "What message does the author want ME to know?",
      "HOW ELEMENTS WORK TOGETHER: 🤝",
      "All 5 elements connect!",
      "CHARACTERS face a CONFLICT...",
      "...in a specific SETTING...",
      "...through a series of events (PLOT)...",
      "...that reveals a THEME!",
      "Change ONE element, the whole story changes!",
      "EXAMPLE STORY BREAKDOWN: 🐷",
      "The Three Little Pigs!",
      "CHARACTERS: Three pigs, big bad wolf",
      "SETTING: Countryside, three different houses",
      "PLOT: Pigs build houses, wolf tries to blow them down, brick house survives!",
      "CONFLICT: Pigs vs Wolf (character vs character)",
      "THEME: Hard work and planning pay off! Quality over speed!",
      "OTHER STORY ELEMENTS: 📝",
      "POINT OF VIEW: Who's telling the story?",
      "First person: \"I went to the store\" (character telling)",
      "Third person: \"She went to the store\" (narrator telling)",
      "TONE: The feeling/attitude of the story!",
      "Funny, serious, scary, mysterious!",
      "MOOD: The feeling YOU get reading it!",
      "Happy, tense, sad, excited!",
      "ANALYZING CHARACTERS: 🔬",
      "To understand characters, look at:",
      "1. What they SAY (dialogue)",
      "2. What they DO (actions)",
      "3. What they THINK (internal thoughts)",
      "4. What OTHERS say about them",
      "5. How they CHANGE through the story!",
      "DYNAMIC characters CHANGE!",
      "Learn lessons, grow, become different!",
      "STATIC characters STAY THE SAME!",
      "Don't change much through the story!",
      "READING LIKE A DETECTIVE: 🔍",
      "As you read, ask yourself:",
      "- WHO is this story about?",
      "- WHERE and WHEN does it happen?",
      "- WHAT problem do they face?",
      "- WHAT happens (events)?",
      "- HOW is it resolved?",
      "- WHAT's the lesson?",
      "This helps you understand and remember stories!",
      "WHY STORY ELEMENTS MATTER: ✨",
      "Understanding elements makes you a BETTER READER!",
      "You notice more details!",
      "You understand author's choices!",
      "Makes reading MORE FUN!",
      "Helps you WRITE better stories too!",
      "You know what ingredients to include!",
      "Remember: Every great story has these elements! 📚✨"
    ],
    questions: [
      {
        question: "What do we call the people or animals in a story?",
        options: ["Setting", "Plot", "Characters", "Theme"],
        correctAnswer: 2,
        explanation: "CHARACTERS are the people or animals in a story! They're the WHO - the story is about them!"
      },
      {
        question: "What is the setting?",
        options: ["The main character", "Where and when the story happens", "The problem", "The ending"],
        correctAnswer: 1,
        explanation: "Setting is WHERE and WHEN the story takes place! Location and time period!"
      },
      {
        question: "What are the three main parts of plot structure?",
        options: ["Happy, sad, scary", "Beginning, middle, end", "Characters, setting, theme", "Title, author, pages"],
        correctAnswer: 1,
        explanation: "Plot has BEGINNING (introduction), MIDDLE (rising action & climax), and END (resolution)! That's the story's structure!"
      },
      {
        question: "What is the conflict in a story?",
        options: ["The setting", "The problem or challenge", "The main character", "The happy ending"],
        correctAnswer: 1,
        explanation: "Conflict is the PROBLEM or CHALLENGE characters must face! It drives the story forward. No conflict = no story!"
      },
      {
        question: "What is the theme?",
        options: ["The title", "The big lesson or message", "Where it takes place", "The first sentence"],
        correctAnswer: 1,
        explanation: "Theme is the BIG LESSON or MESSAGE of the story! It's the deeper meaning, like 'hard work pays off' or 'be kind to others'!"
      },
      {
        question: "The most exciting part of the story is called the:",
        options: ["Beginning", "Climax", "Setting", "Character"],
        correctAnswer: 1,
        explanation: "The CLIMAX is the most exciting part - the peak of the plot mountain! It's the big moment when the main action happens!"
      },
      {
        question: "If a character is fighting against a storm, what type of conflict is it?",
        options: ["Character vs Character", "Character vs Nature", "Character vs Self", "Character vs Society"],
        correctAnswer: 1,
        explanation: "Character vs NATURE! Fighting against natural forces like storms, animals, or wilderness!"
      },
      {
        question: "What's the difference between a protagonist and antagonist?",
        options: ["No difference", "Protagonist is the hero, antagonist works against them", "They're both villains", "Protagonist is the setting"],
        correctAnswer: 1,
        explanation: "Protagonist is the MAIN CHARACTER (hero), and antagonist works AGAINST them (often the villain)! They're opposites!"
      }
    ]
  },
  504: {
    id: 504,
    title: 'Context Clues',
    icon: '🔑',
    description: 'Figuring out word meanings',
    content: [
      "Time to become a WORD DETECTIVE! 🔍 Let's learn about CONTEXT CLUES!",
      "Have you ever read a word you don't know?",
      "You don't always need a dictionary!",
      "The words AROUND it can help you figure it out!",
      "WHAT ARE CONTEXT CLUES? 🤔",
      "Context = the words and sentences AROUND an unknown word!",
      "Clues = hints that help you figure out the meaning!",
      "Context clues are like puzzle pieces!",
      "They help you solve the mystery of what a word means!",
      "WHY USE CONTEXT CLUES? 💡",
      "Stopping to look up EVERY word slows you down!",
      "Context clues keep you reading!",
      "They help you learn new vocabulary naturally!",
      "Good readers use context clues all the time!",
      "You become a SMARTER, FASTER reader!",
      "TYPES OF CONTEXT CLUES: 🔑",
      "There are 5 MAIN types!",
      "TYPE 1: DEFINITION/EXPLANATION CLUES! 📖",
      "The text TELLS you what the word means!",
      "The definition is right there in the sentence!",
      "Look for clue words: is, are, means, refers to, is called!",
      "Example 1:",
      "'A herbivore is an animal that eats only plants.'",
      "The sentence DEFINES herbivore!",
      "Herbivore = plant-eating animal!",
      "Example 2:",
      "'Photosynthesis, the process plants use to make food from sunlight...'",
      "The comma + explanation tells you what photosynthesis means!",
      "Example 3:",
      "'An archipelago, which is a group of islands...'",
      "The phrase 'which is' signals a definition!",
      "TYPE 2: SYNONYM CLUES! 🔄",
      "A synonym (similar meaning word) is nearby!",
      "Look for clue words: or, like, as, similar to!",
      "Example 1:",
      "'The enormous, huge building towered over us.'",
      "Enormous and huge mean the same!",
      "Both mean VERY BIG!",
      "Example 2:",
      "'She was elated, or extremely happy, about her grade.'",
      "'Or' signals a synonym!",
      "Elated = extremely happy!",
      "Example 3:",
      "'The frigid, freezing water made them shiver.'",
      "Frigid = freezing = very cold!",
      "TYPE 3: ANTONYM CLUES! ⚖️",
      "An antonym (opposite word) helps you figure it out!",
      "Look for clue words: unlike, but, however, instead, although, rather than!",
      "Example 1:",
      "'Unlike her tidy room, mine was chaotic.'",
      "'Unlike' signals opposite!",
      "Tidy = neat, so chaotic = MESSY!",
      "Example 2:",
      "'He wasn't timid like his brother. He was bold and confident.'",
      "Timid is the opposite of bold!",
      "Timid = shy, not confident!",
      "Example 3:",
      "'The movie wasn't boring. It was captivating from start to finish.'",
      "Captivating is opposite of boring!",
      "Captivating = very interesting, holds your attention!",
      "TYPE 4: EXAMPLE CLUES! 📋",
      "Examples are given to explain the word!",
      "Look for clue words: such as, like, for example, including, for instance!",
      "Example 1:",
      "'Reptiles, such as snakes, lizards, and turtles, are cold-blooded.'",
      "'Such as' introduces examples!",
      "Reptiles = animals like snakes, lizards, turtles!",
      "Example 2:",
      "'She loved citrus fruits like oranges, lemons, and grapefruits.'",
      "The examples tell you citrus = fruits like oranges!",
      "Example 3:",
      "'The store sells utensils including forks, spoons, and knives.'",
      "Utensils = eating tools like forks and spoons!",
      "TYPE 5: INFERENCE/GENERAL CONTEXT CLUES! 🧩",
      "NO direct clue, but you can FIGURE IT OUT from the situation!",
      "Read the whole sentence and sentences around it!",
      "Example 1:",
      "'After walking through the storm, his clothes were drenched. He needed to change immediately.'",
      "No direct definition of 'drenched'...",
      "But storm + need to change = drenched means VERY WET!",
      "Example 2:",
      "'The ancient artifact was discovered buried deep underground. Scientists believe it's thousands of years old.'",
      "Context: buried, thousands of years old!",
      "Ancient = VERY OLD!",
      "Example 3:",
      "'She tried to conceal the gift behind her back when he entered the room.'",
      "Context: hiding something behind back!",
      "Conceal = HIDE!",
      "STRATEGY: THE 4-STEP PROCESS! 🪜",
      "STEP 1: STOP at the unknown word!",
      "Don't skip it! Acknowledge you don't know it!",
      "STEP 2: READ the whole sentence!",
      "Look for clues in the same sentence!",
      "STEP 3: READ sentences AROUND it!",
      "Look before and after for more clues!",
      "STEP 4: MAKE A SMART GUESS!",
      "Put your guess in place of the word!",
      "Does it make sense?",
      "PRACTICE EXAMPLE 1: 🌊",
      "'The tsunami, a massive wave caused by underwater earthquakes, destroyed the coastal town.'",
      "Unknown word: tsunami",
      "Type of clue: DEFINITION!",
      "'a massive wave caused by underwater earthquakes' defines it!",
      "Tsunami = huge wave from earthquake!",
      "PRACTICE EXAMPLE 2: 🏃",
      "'After the marathon, she felt exhausted. She could barely stand and needed to rest.'",
      "Unknown word: exhausted",
      "Type of clue: INFERENCE/CONTEXT!",
      "Clues: after long run, barely stand, needed rest!",
      "Exhausted = VERY TIRED!",
      "PRACTICE EXAMPLE 3: 🎨",
      "'The painting was immaculate - not a single flaw or imperfection.'",
      "Unknown word: immaculate",
      "Type of clue: SYNONYM/EXPLANATION!",
      "'not a single flaw or imperfection' = PERFECT!",
      "Immaculate = perfect, flawless!",
      "PRACTICE EXAMPLE 4: 🦁",
      "'Unlike the timid rabbit, the lion was ferocious.'",
      "Unknown word: ferocious",
      "Type of clue: ANTONYM!",
      "'Unlike timid' signals opposite!",
      "Timid = shy, so ferocious = FIERCE, AGGRESSIVE!",
      "TIPS FOR USING CONTEXT CLUES: 💡",
      "TIP 1: Look for PUNCTUATION clues!",
      "Commas, dashes, parentheses often set off definitions!",
      "Example: 'The habitat (the place where an animal lives) was destroyed.'",
      "TIP 2: Pay attention to CLUE WORDS!",
      "Words like 'means', 'or', 'such as', 'unlike' signal clues!",
      "TIP 3: Read the FULL paragraph!",
      "Sometimes the clue isn't in the same sentence!",
      "TIP 4: SUBSTITUTE your guess!",
      "Replace the word with your guess - does the sentence still make sense?",
      "TIP 5: Use what you ALREADY KNOW!",
      "Connect new words to things you already know!",
      "WHEN CONTEXT ISN'T ENOUGH: 📚",
      "Sometimes context clues don't give enough information!",
      "That's okay!",
      "You can:",
      "- Keep reading - more clues might come!",
      "- Ask someone!",
      "- Look it up in a dictionary!",
      "But TRY context clues first!",
      "BUILDING VOCABULARY: 📈",
      "Every time you use context clues...",
      "You're LEARNING a new word!",
      "Your vocabulary GROWS!",
      "The more you read, the more words you learn!",
      "The more words you know, the easier reading becomes!",
      "MULTIPLE MEANING WORDS: 🔀",
      "Some words have DIFFERENT meanings!",
      "'Bat' = flying animal OR sports equipment!",
      "Context tells you WHICH meaning!",
      "'The bat flew at night.' = animal!",
      "'He swung the bat.' = sports equipment!",
      "PRACTICE MAKES PERFECT: ⭐",
      "The more you practice finding context clues...",
      "The FASTER and EASIER it becomes!",
      "Eventually, you do it automatically!",
      "Without even thinking about it!",
      "You become a SUPER READER! 🦸",
      "Remember: The words around a mystery word are your CLUES! 🔍✨"
    ],
    questions: [
      {
        question: "'The dog was famished - he hadn't eaten in two days!' What does famished mean?",
        options: ["Happy", "Very hungry", "Tired", "Angry"],
        correctAnswer: 1,
        explanation: "The clue 'hadn't eaten in two days' tells us famished means VERY HUNGRY! That's an inference clue from context!"
      },
      {
        question: "What are context clues?",
        options: ["Dictionary definitions", "Words around unknown words that help", "Hard words", "The main idea"],
        correctAnswer: 1,
        explanation: "Context clues are HINTS from words AROUND an unknown word that help you figure out its meaning! They're detective clues!"
      },
      {
        question: "'The weather was frigid, not warm at all.' What does frigid mean?",
        options: ["Very hot", "Very cold", "Rainy", "Windy"],
        correctAnswer: 1,
        explanation: "The ANTONYM clue 'not warm at all' tells us frigid means VERY COLD! 'Not warm' = cold!"
      },
      {
        question: "What type of clue is this? 'Nocturnal animals, such as owls and bats, are active at night.'",
        options: ["Definition", "Example", "Antonym", "Synonym"],
        correctAnswer: 1,
        explanation: "This is an EXAMPLE clue! 'Such as' introduces examples - owls and bats are examples of nocturnal animals (active at night)!"
      },
      {
        question: "'A carnivore is an animal that eats meat.' What type of context clue is this?",
        options: ["Example", "Antonym", "Definition", "Inference"],
        correctAnswer: 2,
        explanation: "This is a DEFINITION clue! The sentence directly DEFINES what carnivore means using 'is'!"
      },
      {
        question: "Which word signals a synonym clue?",
        options: ["Unlike", "However", "Or", "Such as"],
        correctAnswer: 2,
        explanation: "'Or' often signals a SYNONYM clue! Example: 'She was elated, or very happy.' It connects similar meanings!"
      },
      {
        question: "'Unlike his messy desk, hers was organized.' What does organized mean?",
        options: ["Messy", "Neat and tidy", "Big", "Colorful"],
        correctAnswer: 1,
        explanation: "'Unlike' signals an ANTONYM clue! If his is messy and hers is UNLIKE his, then organized means NEAT AND TIDY - the opposite!"
      },
      {
        question: "What should you do FIRST when you find an unknown word?",
        options: ["Skip it", "Look it up immediately", "Read the whole sentence for clues", "Give up"],
        correctAnswer: 2,
        explanation: "FIRST, read the whole sentence for context clues! Then read sentences around it. Try to figure it out BEFORE looking it up!"
      }
    ]
  },
  505: {
    id: 505,
    title: 'Summarizing Texts',
    icon: '📝',
    description: 'Retelling in your own words',
    content: [
      "Let's learn the SUPER SKILL of summarizing! 📝✨",
      "Summarizing is like being a movie trailer editor!",
      "You share the IMPORTANT parts without telling EVERYTHING!",
      "It's one of the MOST important reading skills!",
      "WHAT IS A SUMMARY? 🤔",
      "A summary is a SHORT version of a text!",
      "Written in YOUR OWN WORDS!",
      "Includes ONLY the most important information!",
      "Think of it as the 'greatest hits' of what you read!",
      "A summary is MUCH SHORTER than the original!",
      "Original text: 3 pages → Summary: 1 paragraph!",
      "WHY DO WE SUMMARIZE? 💡",
      "Shows you UNDERSTOOD what you read!",
      "Helps you REMEMBER important information!",
      "Useful for studying and taking notes!",
      "Helps explain things to others quickly!",
      "Teachers use summaries to check your understanding!",
      "In real life: summaries help communicate quickly!",
      "SUMMARY vs RETELLING: What's the Difference? 📚",
      "RETELLING: Includes ALL details, in order!",
      "Like retelling a whole movie scene by scene!",
      "Longer!",
      "SUMMARY: Only MAIN POINTS!",
      "Like a movie trailer - highlights only!",
      "Much shorter!",
      "Example:",
      "Retelling: Tells every event in 'The Three Little Pigs'!",
      "Summary: Three pigs build houses. Wolf blows down straw and stick houses. Brick house survives. Lesson: Hard work pays off!",
      "WHAT TO INCLUDE IN A SUMMARY: ✅",
      "1. MAIN IDEA or MAIN MESSAGE!",
      "What's it MOSTLY about?",
      "2. KEY POINTS or KEY EVENTS!",
      "The most important facts or happenings!",
      "3. MAIN CHARACTERS (for stories)!",
      "Who is the story about?",
      "4. THE OUTCOME/CONCLUSION!",
      "How did it end? What was learned?",
      "WHAT TO LEAVE OUT: ❌",
      "1. Small DETAILS!",
      "Don't need every little fact!",
      "2. EXAMPLES (usually)!",
      "Unless they're super important!",
      "3. Your OPINIONS!",
      "Summary = what the text says, not what you think!",
      "4. Exact QUOTES (usually)!",
      "Use your own words!",
      "5. REPETITIVE information!",
      "If the text says something multiple times, say it once!",
      "SUMMARIZING FICTION (STORIES): 📖",
      "Use the 5 W's and H!",
      "WHO: Who are the main characters?",
      "WHAT: What happened? What's the main problem?",
      "WHERE: Where does it take place? (if important)",
      "WHEN: When does it happen? (if important)",
      "WHY: Why did things happen?",
      "HOW: How was the problem solved?",
      "Story Summary Formula:",
      "[CHARACTER] wanted [GOAL] but [PROBLEM], so [SOLUTION], and then [ENDING]!",
      "Example:",
      "'Cinderella wanted to go to the ball but had no nice clothes, so her fairy godmother helped, and then she met the prince!'",
      "SUMMARIZING NON-FICTION (INFORMATIONAL TEXTS): 📰",
      "Focus on MAIN IDEA + KEY DETAILS!",
      "Non-Fiction Summary Formula:",
      "This text is about [TOPIC]. [Main point 1]. [Main point 2]. [Main point 3]. [Conclusion].",
      "Example:",
      "'This article is about recycling. Recycling reduces waste. It saves natural resources. It helps protect the environment. Everyone should recycle!'",
      "THE SOMEBODY-WANTED-BUT-SO-THEN METHOD: 🎯",
      "Great for stories!",
      "SOMEBODY: Who's the main character?",
      "WANTED: What did they want/need?",
      "BUT: What problem did they face?",
      "SO: What did they do about it?",
      "THEN: What was the result/ending?",
      "Example: Little Red Riding Hood",
      "SOMEBODY: Little Red Riding Hood",
      "WANTED: To visit Grandma",
      "BUT: A wolf tricked her and went to Grandma's first",
      "SO: She was careful and realized it wasn't Grandma",
      "THEN: A woodcutter saved them!",
      "THE 5-STEP SUMMARIZING PROCESS: 🪜",
      "STEP 1: READ the text carefully!",
      "Read ALL of it! Don't skip!",
      "STEP 2: IDENTIFY the main idea!",
      "What's the BIG picture?",
      "STEP 3: FIND key supporting details!",
      "What are the most important facts or events?",
      "STEP 4: WRITE in your own words!",
      "Don't copy sentences from the text!",
      "STEP 5: CHECK your summary!",
      "Is it accurate? Short? In your own words?",
      "PRACTICE PASSAGE 1: 🌱",
      "Original text:",
      "'Plants need several things to grow. They need sunlight to make food through photosynthesis. They need water to stay hydrated and transport nutrients. They need soil to anchor roots and provide minerals. They also need air, specifically carbon dioxide, for photosynthesis. Temperature matters too - most plants grow best in moderate temperatures. With all these elements, plants can grow strong and healthy!'",
      "Summary:",
      "'Plants need sunlight, water, soil, air, and moderate temperature to grow healthy.'",
      "Short! Main ideas only! Own words!",
      "PRACTICE PASSAGE 2: 🏀",
      "Original text:",
      "'Marcus loved basketball more than anything. Every day after school, he practiced shooting hoops in his driveway. His dream was to make the school team, but he wasn't very tall. Many people told him he was too short. But Marcus didn't give up. He practiced harder than anyone else. When tryouts came, he impressed the coaches with his skills and determination. He made the team! Marcus learned that hard work beats natural talent.'",
      "Summary:",
      "'Marcus wanted to make the basketball team but people said he was too short. He practiced hard and impressed the coaches with his skills. He made the team and learned hard work pays off.'",
      "Includes: Character, goal, problem, solution, lesson!",
      "COMMON MISTAKES TO AVOID: ⚠️",
      "Mistake 1: TOO LONG!",
      "Your summary shouldn't be almost as long as the original!",
      "If original is 1 page, summary should be a few sentences!",
      "Mistake 2: COPYING word-for-word!",
      "Use YOUR OWN WORDS! Paraphrase!",
      "Mistake 3: Adding YOUR OWN IDEAS!",
      "Summary = what the TEXT says, not your opinions!",
      "Don't add: 'I think...' or 'In my opinion...'",
      "Mistake 4: Including TOO MANY DETAILS!",
      "Leave out the small stuff!",
      "Mistake 5: Missing the MAIN IDEA!",
      "Always include what it's MOSTLY about!",
      "USING YOUR OWN WORDS (Paraphrasing): 🔄",
      "Don't just copy sentences!",
      "Change the words while keeping the meaning!",
      "Original: 'The enormous elephant trumpeted loudly.'",
      "Paraphrased: 'The huge elephant made a loud noise.'",
      "Tips for paraphrasing:",
      "- Use synonyms (big instead of enormous)",
      "- Change sentence structure",
      "- Simplify complex language",
      "CHECKING YOUR SUMMARY: ✅",
      "Ask yourself these questions:",
      "1. Is it SHORTER than the original?",
      "2. Did I include the MAIN IDEA?",
      "3. Did I include KEY POINTS only?",
      "4. Did I use MY OWN WORDS?",
      "5. Does it make sense on its own?",
      "6. Did I leave out small details?",
      "7. Did I leave out my opinions?",
      "If you answered YES to all → Great summary! 🎉",
      "SUMMARY LENGTH: How Long? 📏",
      "It depends on the original!",
      "SHORT TEXT (1 paragraph) → 1-2 sentences",
      "MEDIUM TEXT (1 page) → 3-5 sentences",
      "LONG TEXT (chapter/article) → 1 paragraph",
      "BOOK → A few paragraphs",
      "Rule of thumb: Summary should be about 1/4 to 1/5 the length!",
      "SUMMARIZING DIFFERENT TEXT TYPES: 📚",
      "NARRATIVE (stories): Focus on plot and characters!",
      "EXPOSITORY (explains): Focus on main idea and key facts!",
      "PERSUASIVE (convinces): Focus on the argument and main reasons!",
      "PROCEDURAL (how-to): Focus on the main steps!",
      "DESCRIPTIVE: Focus on what's being described and key features!",
      "REAL-WORLD USES: 🌍",
      "Book reports: Summary of what you read!",
      "Research: Summarizing sources!",
      "Social media: TLDR (Too Long; Didn't Read) summaries!",
      "Work: Executive summaries of reports!",
      "News: Headlines are mini-summaries!",
      "Conversations: Catching someone up quickly!",
      "THE 'HEADLINE' TRICK: 📰",
      "Imagine you're writing a HEADLINE for the text!",
      "Headlines capture the main idea in few words!",
      "That's like a 1-sentence summary!",
      "Then expand it to a few sentences for a full summary!",
      "SUMMARY = UNDERSTANDING: 🧠",
      "If you can summarize something well...",
      "It means you TRULY UNDERSTOOD it!",
      "Summarizing forces you to think about what's important!",
      "It's active reading, not passive!",
      "Practice summarizing everything you read!",
      "TV shows, movies, articles, books, conversations!",
      "Remember: Keep it SHORT, ACCURATE, and in YOUR OWN WORDS! 📝✨"
    ],
    questions: [
      {
        question: "What is a summary?",
        options: ["Copying the whole text", "A short version with main ideas only", "Your opinion about the text", "The longest paragraph"],
        correctAnswer: 1,
        explanation: "A summary is a SHORT version that includes only the MAIN IDEAS, written in your own words!"
      },
      {
        question: "Should you include small details in a summary?",
        options: ["Yes, every single detail", "No, only main points", "Only if they're interesting", "Only at the end"],
        correctAnswer: 1,
        explanation: "NO! Summaries include only MAIN POINTS and important information. Leave out small details!"
      },
      {
        question: "How long should a summary be compared to the original text?",
        options: ["Same length", "Much shorter", "Longer", "Just slightly shorter"],
        correctAnswer: 1,
        explanation: "A summary should be MUCH SHORTER than the original - typically about 1/4 to 1/5 the length!"
      },
      {
        question: "What should you use when writing a summary?",
        options: ["The author's exact words", "Your own words", "Another book", "Only pictures"],
        correctAnswer: 1,
        explanation: "Use YOUR OWN WORDS! Don't copy sentences from the text - that's called paraphrasing!"
      },
      {
        question: "For a story summary, what should you include?",
        options: ["Every single event", "Main characters, problem, and solution", "Just the beginning", "Your favorite part"],
        correctAnswer: 1,
        explanation: "Include the MAIN CHARACTERS, the PROBLEM they faced, and the SOLUTION/ending! Use WHO, WHAT, HOW!"
      },
      {
        question: "What's the difference between a retelling and a summary?",
        options: ["No difference", "Retelling includes all details; summary only main points", "Summary is longer", "Retelling is shorter"],
        correctAnswer: 1,
        explanation: "RETELLING includes ALL details in order. SUMMARY includes only MAIN POINTS! Summary is much shorter!"
      },
      {
        question: "What is the SOMEBODY-WANTED-BUT-SO-THEN method used for?",
        options: ["Summarizing stories", "Writing poetry", "Spelling words", "Reading fast"],
        correctAnswer: 0,
        explanation: "The SOMEBODY-WANTED-BUT-SO-THEN method helps you summarize STORIES by identifying character, goal, problem, action, and outcome!"
      },
      {
        question: "Should you include your opinions in a summary?",
        options: ["Yes, always", "No, stick to what the text says", "Only at the end", "Only if you disagree"],
        correctAnswer: 1,
        explanation: "NO! Summaries include what the TEXT says, not your opinions or thoughts. Keep it objective and factual!"
      }
    ]
  },
  // Grammar & Writing (601-605)
  601: {
    id: 601,
    title: 'Parts of Speech',
    icon: '🔤',
    description: 'Different types of words',
    content: [
      "Welcome to the building blocks of language! 🔤 Let's learn PARTS OF SPEECH!",
      "Every word in English has a JOB in a sentence!",
      "That job is called its PART OF SPEECH!",
      "There are 8 main parts of speech!",
      "Understanding them helps you speak and write better!",
      "Think of parts of speech like players on a team - each has a role!",
      "PART #1: NOUNS! 📦",
      "Nouns name people, places, things, or ideas!",
      "If you can see it, touch it, or think about it - it's probably a noun!",
      "PEOPLE: mom, teacher, doctor, Maria, children!",
      "PLACES: school, park, Mexico, bedroom, ocean!",
      "THINGS: dog, car, book, apple, chair!",
      "IDEAS: love, freedom, happiness, courage, time!",
      "TYPES OF NOUNS:",
      "COMMON NOUNS: General names (not capitalized) - dog, city, book!",
      "PROPER NOUNS: Specific names (capitalized) - Spot, Paris, Harry Potter!",
      "CONCRETE NOUNS: Things you can touch - table, tree, water!",
      "ABSTRACT NOUNS: Ideas you can't touch - peace, joy, wisdom!",
      "PART #2: PRONOUNS! 👤",
      "Pronouns REPLACE nouns so we don't repeat them!",
      "Instead of saying 'Sarah said Sarah loves Sarah's cat'...",
      "We say: 'Sarah said she loves her cat!'",
      "SUBJECT PRONOUNS: I, you, he, she, it, we, they!",
      "These DO the action: 'SHE runs.' 'THEY play.'",
      "OBJECT PRONOUNS: me, you, him, her, it, us, them!",
      "These RECEIVE the action: 'Give it to HIM.' 'Tell THEM.'",
      "POSSESSIVE PRONOUNS: mine, yours, his, hers, ours, theirs!",
      "Show ownership: 'That book is MINE!'",
      "PART #3: VERBS! 🏃",
      "Verbs show ACTION or STATE OF BEING!",
      "They're the 'doing' or 'being' words!",
      "ACTION VERBS: Show what someone/something DOES!",
      "Run, jump, eat, swim, think, write, laugh, dance!",
      "Physical actions: kick, throw, build!",
      "Mental actions: believe, know, understand!",
      "LINKING VERBS (STATE OF BEING): Connect subject to description!",
      "Am, is, are, was, were, be, being, been!",
      "'She IS happy.' (IS links 'she' to 'happy')",
      "'They WERE tired.' (WERE links 'they' to 'tired')",
      "HELPING VERBS: Help the main verb!",
      "Can, could, will, would, should, may, might, must, have, has, had!",
      "'I WILL go.' (WILL helps 'go')",
      "'She HAS eaten.' (HAS helps 'eaten')",
      "PART #4: ADJECTIVES! 🎨",
      "Adjectives DESCRIBE nouns and pronouns!",
      "They tell: WHAT KIND? HOW MANY? WHICH ONE?",
      "WHAT KIND: big dog, red car, happy child, scary movie!",
      "HOW MANY: three apples, many people, few mistakes!",
      "WHICH ONE: that book, this pen, those cookies!",
      "Adjectives make writing MORE INTERESTING!",
      "Without adjectives: 'I saw a dog.'",
      "With adjectives: 'I saw a HUGE, FURRY, BROWN dog!'",
      "Adjectives usually come BEFORE the noun!",
      "'The TALL tree' not 'The tree TALL'!",
      "PART #5: ADVERBS! ⚡",
      "Adverbs describe VERBS, ADJECTIVES, or OTHER ADVERBS!",
      "They tell: HOW? WHEN? WHERE? HOW MUCH?",
      "Many adverbs end in -LY!",
      "DESCRIBING VERBS (How?):",
      "'She ran QUICKLY.' (How did she run? Quickly!)",
      "'He spoke SOFTLY.' (How did he speak? Softly!)",
      "DESCRIBING ADJECTIVES (How much?):",
      "'The VERY tall building.' (How tall? VERY tall!)",
      "'She's EXTREMELY happy.' (How happy? EXTREMELY happy!)",
      "WHEN: now, later, soon, yesterday, always, never!",
      "'We will go SOON.'",
      "WHERE: here, there, everywhere, outside, away!",
      "'Put it THERE.'",
      "HOW OFTEN: always, never, sometimes, often, rarely!",
      "'He ALWAYS helps.'",
      "PART #6: PREPOSITIONS! 🌉",
      "Prepositions show RELATIONSHIPS between words!",
      "They show position, direction, or time!",
      "Common prepositions: in, on, at, by, with, from, to, under, over, between, through!",
      "LOCATION/POSITION:",
      "'The cat is ON the table.'",
      "'The book is UNDER the bed.'",
      "'Stand BETWEEN your friends.'",
      "DIRECTION:",
      "'She walked TO school.'",
      "'He ran THROUGH the park.'",
      "TIME:",
      "'Meet me AT noon.'",
      "'We'll go IN the morning.'",
      "Prepositions are always part of a PREPOSITIONAL PHRASE!",
      "Preposition + Noun/Pronoun: 'in the box', 'with her', 'under the bridge'!",
      "PART #7: CONJUNCTIONS! 🔗",
      "Conjunctions CONNECT words, phrases, or sentences!",
      "They're the 'glue' that holds ideas together!",
      "COORDINATING CONJUNCTIONS: and, but, or, nor, for, yet, so!",
      "Remember FANBOYS: For, And, Nor, But, Or, Yet, So!",
      "'I like pizza AND pasta.' (connects two things)",
      "'She's tired BUT happy.' (shows contrast)",
      "'Do you want tea OR coffee?' (shows choice)",
      "SUBORDINATING CONJUNCTIONS: because, although, since, if, when, while, after, before!",
      "'I stayed home BECAUSE I was sick.'",
      "'ALTHOUGH it rained, we played outside.'",
      "PART #8: INTERJECTIONS! 😮",
      "Interjections express STRONG FEELINGS or EMOTIONS!",
      "They're usually followed by an exclamation point!",
      "Wow! Ouch! Hey! Yay! Oops! Uh-oh! Hooray! Oh no!",
      "'WOW! That's amazing!'",
      "'OUCH! That hurt!'",
      "'YAY! We won!'",
      "Interjections can stand alone or start sentences!",
      "HOW PARTS OF SPEECH WORK TOGETHER: 🤝",
      "All 8 parts build sentences!",
      "Example sentence: 'The quick brown fox quietly jumped over the lazy dog yesterday.'",
      "Let's break it down:",
      "THE = article (special adjective)",
      "QUICK, BROWN, LAZY = adjectives (describe nouns)",
      "FOX, DOG = nouns (naming words)",
      "QUIETLY = adverb (describes how fox jumped)",
      "JUMPED = verb (action)",
      "OVER = preposition (shows relationship)",
      "THE = article",
      "YESTERDAY = adverb (when it happened)",
      "ARTICLES: Special Adjectives! 📰",
      "A, AN, THE are articles!",
      "THE = specific (the cat means a specific cat)",
      "A/AN = not specific (a cat means any cat)",
      "Use AN before vowel sounds: an apple, an hour!",
      "Use A before consonant sounds: a book, a dog!",
      "IDENTIFYING PARTS OF SPEECH: 🔍",
      "To identify a word's part of speech, ask:",
      "1. What job does it do in THIS sentence?",
      "2. What does it tell me?",
      "SAME WORD, DIFFERENT JOBS:",
      "Some words can be different parts of speech!",
      "LIGHT:",
      "Noun: 'Turn on the light.'",
      "Verb: 'Please light the candles.'",
      "Adjective: 'The box is light in weight.'",
      "Context determines the part of speech!",
      "WHY PARTS OF SPEECH MATTER: ✨",
      "Understanding them helps you:",
      "- Write clearer sentences!",
      "- Use proper grammar!",
      "- Expand vocabulary!",
      "- Understand how language works!",
      "- Become a better reader and writer!",
      "PRACTICE SENTENCE: 🎯",
      "'The excited children quickly ran outside and played happily.'",
      "THE = article",
      "EXCITED = adjective (describes children)",
      "CHILDREN = noun (who?)",
      "QUICKLY = adverb (how they ran)",
      "RAN = verb (action)",
      "OUTSIDE = adverb (where)",
      "AND = conjunction (connects two verbs)",
      "PLAYED = verb (action)",
      "HAPPILY = adverb (how they played)",
      "Remember: Every word has a job, and together they create meaning! 🔤✨"
    ],
    questions: [
      {
        question: "What part of speech is the word 'happy'?",
        options: ["Noun", "Verb", "Adjective", "Pronoun"],
        correctAnswer: 2,
        explanation: "'Happy' DESCRIBES how someone feels - it's an ADJECTIVE! Adjectives describe nouns!"
      },
      {
        question: "What do verbs show?",
        options: ["Names of things", "Action or being", "Descriptions", "Connections"],
        correctAnswer: 1,
        explanation: "Verbs show ACTION (run, jump) or STATE OF BEING (is, are, was, were)! They're the 'doing' or 'being' words!"
      },
      {
        question: "Which word is a pronoun?",
        options: ["Dog", "Run", "She", "Happy"],
        correctAnswer: 2,
        explanation: "'She' is a PRONOUN - it replaces a person's name! Pronouns replace nouns so we don't repeat them!"
      },
      {
        question: "What part of speech are words like 'in', 'on', and 'under'?",
        options: ["Nouns", "Verbs", "Prepositions", "Adjectives"],
        correctAnswer: 2,
        explanation: "These are PREPOSITIONS! They show relationships like position, direction, or time between words!"
      },
      {
        question: "What connects words or sentences together?",
        options: ["Nouns", "Conjunctions", "Adverbs", "Pronouns"],
        correctAnswer: 1,
        explanation: "CONJUNCTIONS connect words or sentences! Words like 'and', 'but', 'or', 'because' are conjunctions - they're the glue!"
      },
      {
        question: "Which word is an adverb? 'The dog barked loudly.'",
        options: ["Dog", "Barked", "Loudly", "The"],
        correctAnswer: 2,
        explanation: "'Loudly' is an ADVERB! It describes HOW the dog barked. Adverbs often end in -ly and describe verbs!"
      },
      {
        question: "What do adjectives describe?",
        options: ["Verbs", "Nouns and pronouns", "Other adjectives only", "Prepositions"],
        correctAnswer: 1,
        explanation: "Adjectives describe NOUNS and PRONOUNS! They tell what kind, how many, or which one!"
      },
      {
        question: "'Wow! That's amazing!' What part of speech is 'Wow'?",
        options: ["Noun", "Verb", "Interjection", "Adjective"],
        correctAnswer: 2,
        explanation: "'Wow' is an INTERJECTION! Interjections express strong feelings or emotions. They usually have exclamation points!"
      }
    ]
  },

};
