interface Question {
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

interface TopicLesson {
  id: number;
  title: string;
  icon: string;
  description: string;
  content: string[];
  questions: Question[];
}

export const lessons: { [key: number]: TopicLesson } = {
  602: {
    id: 602,
    title: 'Sentence Structure',
    icon: '📐',
    description: 'How sentences are built',
    content: [
      "Time to build SENTENCES! 📐 Let's learn how they're structured!",
      "Sentences are like buildings - they need a strong foundation!",
      "Understanding structure makes you a better writer!",
      "THE FOUNDATION: Complete Sentences! 🏗️",
      "A COMPLETE sentence must have TWO parts!",
      "PART 1: THE SUBJECT!",
      "The subject tells WHO or WHAT the sentence is about!",
      "It answers: Who did it? or What is it?",
      "Examples:",
      "'The CAT jumped.' (Who jumped? The cat!)",
      "'MY SISTER loves reading.' (Who loves reading? My sister!)",
      "'THE STORM caused damage.' (What caused damage? The storm!)",
      "PART 2: THE PREDICATE!",
      "The predicate tells WHAT the subject does or is!",
      "It contains the VERB and gives information about the subject!",
      "Examples:",
      "'The cat JUMPED OVER THE FENCE.' (What did the cat do?)",
      "'My sister LOVES READING.' (What does sister do?)",
      "'The storm CAUSED DAMAGE.' (What did storm do?)",
      "PUTTING IT TOGETHER: Subject + Predicate = Complete Sentence! ✅",
      "'Dogs bark.' (Dogs = subject, bark = predicate)",
      "'The teacher explained the lesson.' (The teacher = subject, explained the lesson = predicate)",
      "FRAGMENTS: Incomplete Sentences! ❌",
      "A FRAGMENT is missing a subject OR predicate!",
      "Fragment: 'Ran to the store.' (Who ran? Missing subject!)",
      "Fixed: 'SHE ran to the store.'",
      "Fragment: 'The big brown dog.' (What about the dog? Missing predicate!)",
      "Fixed: 'The big brown dog BARKED.'",
      "Always check: Do I have WHO/WHAT and WHAT HAPPENS?",
      "THE 4 SENTENCE TYPES: 🎯",
      "TYPE 1: SIMPLE SENTENCES! 🔵",
      "Simple = ONE independent clause!",
      "Independent clause = complete thought (subject + predicate)!",
      "Examples:",
      "'Birds fly.'",
      "'The children played in the park.'",
      "'I love chocolate ice cream.'",
      "Simple doesn't mean SHORT!",
      "'The enormous elephant with the long trunk slowly walked through the dense jungle.' (Still simple - one subject, one verb!)",
      "TYPE 2: COMPOUND SENTENCES! 🔵🔵",
      "Compound = TWO independent clauses joined together!",
      "Think: Simple sentence + Conjunction + Simple sentence!",
      "Use FANBOYS conjunctions: For, And, Nor, But, Or, Yet, So!",
      "Examples:",
      "'I wanted pizza, BUT my brother wanted tacos.'",
      "(Sentence 1: I wanted pizza)",
      "(Sentence 2: my brother wanted tacos)",
      "'The sun was shining, AND the birds were singing.'",
      "'Do you want juice, OR would you prefer water?'",
      "PRO TIP: Use a COMMA before the conjunction!",
      "'She studied hard, so she passed the test.' ✅",
      "'She studied hard so she passed the test.' ❌ (Missing comma!)",
      "TYPE 3: COMPLEX SENTENCES! 🔵🔴",
      "Complex = ONE independent clause + ONE (or more) dependent clause!",
      "INDEPENDENT clause: Can stand alone - complete thought!",
      "DEPENDENT clause: CANNOT stand alone - incomplete thought!",
      "Dependent clauses start with subordinating conjunctions!",
      "Common ones: because, although, since, when, if, while, after, before, until!",
      "Examples:",
      "'BECAUSE it rained, we stayed inside.'",
      "(Because it rained = dependent - can't stand alone)",
      "(we stayed inside = independent - complete thought)",
      "'We stayed inside BECAUSE it rained.' (Same sentence, different order!)",
      "'WHEN the bell rings, class is over.'",
      "'I'll go to the park IF it stops raining.'",
      "COMMA RULE: If dependent clause comes FIRST, use a comma!",
      "'Although I was tired, I finished my homework.' ✅",
      "'I finished my homework although I was tired.' (No comma needed!)",
      "TYPE 4: COMPOUND-COMPLEX SENTENCES! 🔵🔵🔴",
      "The ULTIMATE combination!",
      "Compound-Complex = TWO+ independent clauses + ONE+ dependent clause!",
      "Example:",
      "'WHEN the movie ended, we left the theater, AND we went to dinner.'",
      "(When the movie ended = dependent)",
      "(we left the theater = independent)",
      "(we went to dinner = independent)",
      "These are for advanced writers!",
      "SUBJECT-VERB AGREEMENT: They Must Match! 🤝",
      "Singular subject → singular verb!",
      "'The dog RUNS.' (One dog = singular)",
      "Plural subject → plural verb!",
      "'The dogs RUN.' (Multiple dogs = plural)",
      "Common mistakes:",
      "❌ 'The dog run fast.'",
      "✅ 'The dog RUNS fast.'",
      "❌ 'The dogs runs fast.'",
      "✅ 'The dogs RUN fast.'",
      "Tricky situation - Don't be fooled!",
      "'The box of cookies IS on the table.'",
      "(Subject is BOX, not cookies! Box is singular!)",
      "SENTENCE PATTERNS: 📊",
      "PATTERN 1: Subject + Verb",
      "'Birds fly.'",
      "PATTERN 2: Subject + Verb + Object",
      "'I eat pizza.'",
      "(I = subject, eat = verb, pizza = object - what I eat!)",
      "PATTERN 3: Subject + Verb + Indirect Object + Direct Object",
      "'Mom gave ME a present.'",
      "(Me = indirect object - who received, present = direct object - what was given)",
      "PATTERN 4: Subject + Linking Verb + Complement",
      "'She is HAPPY.'",
      "(Is = linking verb, happy = complement - describes she)",
      "VARYING SENTENCE LENGTH: Mix It Up! 🎨",
      "Good writing uses DIFFERENT sentence lengths!",
      "ALL SHORT sentences: Choppy! Boring! Not good!",
      "ALL LONG sentences become hard to read and you lose track of the meaning because it just goes on and on and on!",
      "MIX THEM:",
      "'The dog ran. He was very excited. His owner had just come home, and he couldn't wait to greet her!'",
      "(Short. Short. Long!)",
      "This creates RHYTHM and keeps readers interested!",
      "STARTING SENTENCES: Don't Be Boring! 🌟",
      "Don't start every sentence the same way!",
      "BORING: 'I went to the store. I bought milk. I came home. I made cookies.'",
      "BETTER: 'I went to the store. After buying milk, I came home. Then I made cookies!'",
      "Ways to start sentences:",
      "- With the subject: 'The cat meowed.'",
      "- With an adverb: 'Quickly, she ran.'",
      "- With a prepositional phrase: 'In the morning, we left.'",
      "- With a dependent clause: 'Because it rained, we stayed inside.'",
      "TRANSITION WORDS: Connect Your Ideas! 🌉",
      "Transitions help sentences flow together!",
      "ADDING: also, furthermore, in addition, moreover!",
      "'I like pizza. FURTHERMORE, I enjoy pasta.'",
      "CONTRASTING: however, but, on the other hand, although!",
      "'I wanted to go. HOWEVER, it was too late.'",
      "CAUSE/EFFECT: therefore, because, consequently, as a result!",
      "'It rained. THEREFORE, the game was canceled.'",
      "TIME: first, next, then, finally, meanwhile!",
      "'FIRST, crack the eggs. THEN, mix them.'",
      "COMMON SENTENCE ERRORS: ⚠️",
      "ERROR 1: RUN-ON SENTENCES!",
      "Two sentences joined without punctuation or conjunction!",
      "❌ 'I love reading I go to the library every week.'",
      "✅ 'I love reading. I go to the library every week.'",
      "OR ✅ 'I love reading, so I go to the library every week.'",
      "ERROR 2: COMMA SPLICES!",
      "Two sentences joined with ONLY a comma!",
      "❌ 'I was tired, I went to bed.'",
      "✅ 'I was tired, SO I went to bed.' (Add conjunction!)",
      "OR ✅ 'I was tired. I went to bed.' (Use period!)",
      "ERROR 3: FRAGMENTS!",
      "Incomplete thoughts!",
      "❌ 'Because I was hungry.'",
      "✅ 'Because I was hungry, I ate lunch.'",
      "PRACTICE SENTENCE ANALYSIS: 🔍",
      "Sentence: 'Although it was raining, the kids played outside, and they had fun.'",
      "Type: COMPOUND-COMPLEX!",
      "'Although it was raining' = dependent clause",
      "'the kids played outside' = independent clause",
      "'they had fun' = independent clause",
      "Parts:",
      "Subject 1: 'the kids'",
      "Verb 1: 'played'",
      "Subject 2: 'they'",
      "Verb 2: 'had'",
      "Conjunction: 'and'",
      "WRITING STRONG SENTENCES: 💪",
      "1. Keep subject close to verb!",
      "Weak: 'The dog, who was brown and furry and had a long tail, barked.'",
      "Strong: 'The brown, furry dog with a long tail barked.'",
      "2. Use active voice when possible!",
      "Passive: 'The ball was thrown by John.'",
      "Active: 'John threw the ball.' (More direct!)",
      "3. Be specific!",
      "Vague: 'The thing was good.'",
      "Specific: 'The chocolate cake was delicious!'",
      "4. Eliminate unnecessary words!",
      "Wordy: 'Due to the fact that'",
      "Better: 'Because'",
      "Remember: Strong structure = Clear communication! 📐✨"
    ],
    questions: [
      {
        question: "What two parts does every complete sentence need?",
        options: ["Noun and verb", "Subject and predicate", "Beginning and end", "Capital and period"],
        correctAnswer: 1,
        explanation: "Every complete sentence needs a SUBJECT (who/what) and PREDICATE (what they do/are)! These two parts make a complete thought!"
      },
      {
        question: "In 'The dog barked loudly,' what is the subject?",
        options: ["The dog", "Barked", "Loudly", "Barked loudly"],
        correctAnswer: 0,
        explanation: "'The dog' is the subject - it tells WHO the sentence is about! The predicate is 'barked loudly' - what the dog did!"
      },
      {
        question: "What is a compound sentence?",
        options: ["A very long sentence", "Two independent clauses joined together", "A sentence with adjectives", "A sentence with no verb"],
        correctAnswer: 1,
        explanation: "A compound sentence has TWO independent clauses joined by a conjunction (and, but, or, so, etc.)! Example: 'I ran, AND she jumped.'"
      },
      {
        question: "Which is a sentence fragment (INCORRECT)?",
        options: ["Birds fly.", "Ran to the store.", "She is happy.", "Dogs bark loudly."],
        correctAnswer: 1,
        explanation: "'Ran to the store' is a FRAGMENT - it's missing the SUBJECT! Who ran? We need: 'SHE ran to the store.'"
      },
      {
        question: "What should you put before a FANBOYS conjunction in a compound sentence?",
        options: ["Period", "Comma", "Question mark", "Nothing"],
        correctAnswer: 1,
        explanation: "Put a COMMA before FANBOYS conjunctions (For, And, Nor, But, Or, Yet, So) in compound sentences! Example: 'I studied, BUT I still failed.'"
      },
      {
        question: "What is a run-on sentence?",
        options: ["A sentence about running", "A very long sentence", "Two sentences joined without proper punctuation", "A sentence with no subject"],
        correctAnswer: 2,
        explanation: "A run-on sentence is TWO sentences joined WITHOUT proper punctuation or conjunction! Example (WRONG): 'I ran she walked.' FIX: 'I ran, AND she walked.'"
      },
      {
        question: "'Because it rained' - Is this a complete sentence?",
        options: ["Yes", "No, it's a dependent clause", "Yes, it has a verb", "No, it needs a question mark"],
        correctAnswer: 1,
        explanation: "'Because it rained' is a DEPENDENT CLAUSE - it cannot stand alone! It needs an independent clause: 'Because it rained, we stayed inside.'"
      },
      {
        question: "In 'The box of cookies IS on the table,' why is 'is' correct?",
        options: ["It sounds better", "The subject 'box' is singular", "Cookies is plural", "It's a rule"],
        correctAnswer: 1,
        explanation: "The subject is 'BOX' (singular), not 'cookies'! Subject and verb must AGREE: singular subject = singular verb. Don't be fooled by prepositional phrases!"
      }
    ]
  },
  603: {
    id: 603,
    title: 'Punctuation Rules',
    icon: '❓',
    description: 'Using marks correctly',
    content: [
      "Welcome to PUNCTUATION POWER! ❓ Let's master the marks!",
      "Punctuation marks are like traffic signals for readers!",
      "They tell you when to stop, pause, or change tone!",
      "Without punctuation, writing would be confusing!",
      "Let's explore ALL the important marks!",
      "MARK #1: PERIOD (.) 🛑",
      "The period is a FULL STOP!",
      "Use periods to end STATEMENTS (telling sentences)!",
      "'The sky is blue.'",
      "'I love reading books.'",
      "'Today is Monday.'",
      "Also use periods after ABBREVIATIONS!",
      "'Dr. Smith' (Doctor)",
      "'Mr. Jones' (Mister)",
      "'etc.' (et cetera - and so on)",
      "And in INITIALS!",
      "'J.K. Rowling'",
      "MARK #2: QUESTION MARK (?) ❓",
      "Question marks end sentences that ASK something!",
      "'What time is it?'",
      "'Where are you going?'",
      "'Did you finish your homework?'",
      "Only use for DIRECT questions!",
      "Direct: 'Are you coming?' ✅",
      "Indirect: 'She asked if you are coming.' (No question mark!) ✅",
      "MARK #3: EXCLAMATION POINT (!) 😮",
      "Shows STRONG EMOTION or emphasis!",
      "Excitement: 'We won the game!'",
      "Surprise: 'I can't believe it!'",
      "Warning/Command: 'Watch out!'",
      "Anger: 'Stop that right now!'",
      "Don't OVERUSE them!",
      "One is enough! Not multiple!!!! (looks unprofessional!)",
      "MARK #4: COMMA (,) ⏸️",
      "Commas are PAUSES - mini breaks!",
      "They have MANY uses!",
      "COMMA USE #1: Lists!",
      "Separate items in a series (list)!",
      "'I bought apples, oranges, bananas, and grapes.'",
      "Note the comma before 'and' - that's called the OXFORD COMMA!",
      "'Red, white, and blue' (Oxford comma used)",
      "Some people skip it, but it's clearer with it!",
      "COMMA USE #2: After Introductory Words/Phrases!",
      "'Yes, I would like some.'",
      "'However, I disagree.'",
      "'In the morning, we'll leave.'",
      "'After dinner, we played games.'",
      "COMMA USE #3: Compound Sentences!",
      "Before coordinating conjunctions (FANBOYS)!",
      "'I wanted pizza, but she wanted tacos.'",
      "'He studied hard, so he passed the test.'",
      "COMMA USE #4: Setting Off Names!",
      "When directly addressing someone!",
      "'Mom, can you help me?'",
      "'I think, Sarah, that you're right.'",
      "'Let's go, everyone!'",
      "COMMA USE #5: Dates and Addresses!",
      "'July 4, 1776' (between day and year)",
      "'I live in Austin, Texas.' (between city and state)",
      "COMMA USE #6: Non-Essential Information!",
      "'My brother, who lives in Paris, is visiting.'",
      "(The phrase 'who lives in Paris' is extra info!)",
      "MARK #5: APOSTROPHE (') 📍",
      "Apostrophes have TWO main jobs!",
      "JOB #1: Show POSSESSION (ownership)!",
      "SINGULAR ownership: Add 's!",
      "'The dog's toy' (toy belonging to the dog)",
      "'Sarah's book' (book belonging to Sarah)",
      "'James's car' (Yes, even with s-names!)",
      "PLURAL ownership (when plural ends in s): Add just '!",
      "'The dogs' toys' (toys belonging to multiple dogs)",
      "'The students' lockers' (lockers belonging to students)",
      "PLURAL ownership (when plural doesn't end in s): Add 's!",
      "'The children's playground'",
      "'The women's restroom'",
      "JOB #2: CONTRACTIONS!",
      "Combine two words by removing letters!",
      "The apostrophe shows where letters are MISSING!",
      "'Do not' → 'Don't'",
      "'I am' → 'I'm'",
      "'They are' → 'They're'",
      "'Cannot' → 'Can't'",
      "'Will not' → 'Won't' (weird one!)",
      "'It is' → 'It's'",
      "COMMON MISTAKE: Its vs It's!",
      "'It's' = 'It is' (contraction)",
      "'Its' = belonging to it (possession - NO apostrophe!)",
      "'It's raining.' (It is raining) ✅",
      "'The dog wagged its tail.' (tail belonging to dog) ✅",
      "MARK #6: QUOTATION MARKS (\" \") 💬",
      "Show someone's EXACT words!",
      "Dialogue/Speech:",
      "'\"Help me!\" she cried.'",
      "'He said, \"I love pizza.\"'",
      "Put periods and commas INSIDE the quotes!",
      "'She said, \"Hello.\"' ✅ (period inside)",
      "'She said, \"Hello\". ❌ (period outside - wrong!)",
      "Put question marks and exclamation points inside IF they're part of the quote!",
      "'Did she say, \"I'm leaving\"?' (Question is outside the quote)",
      "'She asked, \"Are you coming?\"' (Question is inside the quote)",
      "Also use for TITLES of short works!",
      "Articles: 'I read \"The Best Day Ever.\"'",
      "Short stories: '\"The Gift of the Magi\"'",
      "Poems: '\"The Road Not Taken\"'",
      "Songs: '\"Happy Birthday\"'",
      "MARK #7: COLON (:) 📋",
      "Introduces a list or explanation!",
      "LISTS:",
      "'You'll need the following: pencil, paper, and eraser.'",
      "'I visited three cities: Paris, London, and Rome.'",
      "EXPLANATIONS:",
      "'Here's the problem: we're out of time.'",
      "TIME:",
      "'3:30 PM'",
      "Don't use after a verb or preposition!",
      "❌ 'My favorite colors are: red, blue, green.'",
      "✅ 'My favorite colors are red, blue, and green.'",
      "✅ 'I like three colors: red, blue, and green.'",
      "MARK #8: SEMICOLON (;) 🔗",
      "Connects closely related sentences!",
      "'I love reading; books are my favorite.'",
      "(Two related thoughts - could be separate sentences!)",
      "Also separates items in complex lists!",
      "'I've visited Austin, Texas; Portland, Oregon; and Miami, Florida.'",
      "(When list items have commas, use semicolons!)",
      "MARK #9: DASH (—) and HYPHEN (-) ➖",
      "DASH (—): Sudden break or emphasis!",
      "'I was walking—then I saw something amazing—a shooting star!'",
      "'She's kind, smart, and funny—the perfect friend!'",
      "HYPHEN (-): Joins words!",
      "Compound numbers: 'twenty-one'",
      "Compound adjectives: 'well-known author'",
      "'My ten-year-old brother'",
      "MARK #10: PARENTHESES () 📦",
      "Add extra information!",
      "'My teacher (Mr. Johnson) is nice.'",
      "'The event (scheduled for noon) was canceled.'",
      "The sentence should make sense without the parentheses!",
      "MARK #11: ELLIPSIS (...) 💭",
      "Shows something is missing or trailing off!",
      "MISSING WORDS (in quotes):",
      "'To be or not to be... that is the question.'",
      "TRAILING OFF/PAUSE:",
      "'I don't know... maybe we should wait?'",
      "'Well... I suppose you're right.'",
      "Use THREE DOTS only! Not two, not five!",
      "CAPITALIZATION RULES: (Bonus!) 🔠",
      "Since we're talking about punctuation...",
      "Capitalize:",
      "1. First word of a sentence!",
      "2. The pronoun 'I'!",
      "3. Proper nouns (names): 'Sarah', 'Mexico', 'Monday'!",
      "4. Titles when used with names: 'Dr. Smith', 'President Lincoln'!",
      "5. First word in a quote: 'She said, \"Hello.\"'",
      "COMMON PUNCTUATION MISTAKES: ⚠️",
      "MISTAKE #1: Comma splices!",
      "❌ 'I love reading, I go to the library.'",
      "✅ 'I love reading. I go to the library.'",
      "OR ✅ 'I love reading, so I go to the library.'",
      "MISTAKE #2: Missing apostrophes in contractions!",
      "❌ 'Dont go there.'",
      "✅ 'Don't go there.'",
      "MISTAKE #3: Confusing: your/you're, their/there/they're, its/it's!",
      "Your = belonging to you",
      "You're = you are",
      "Their = belonging to them",
      "There = place",
      "They're = they are",
      "Its = belonging to it",
      "It's = it is",
      "MISTAKE #4: Overusing exclamation points!!!",
      "One is enough!",
      "PRACTICE MAKES PERFECT: ✍️",
      "Read a lot! Notice how authors use punctuation!",
      "When you write, ask: Does this make sense? Where should readers pause?",
      "Punctuation guides your readers through your ideas!",
      "Remember: Proper punctuation makes you a clearer writer! ❓✨"
    ],
    questions: [
      {
        question: "Which punctuation mark ends a question?",
        options: ["Period", "Comma", "Question mark", "Exclamation point"],
        correctAnswer: 2,
        explanation: "QUESTION MARKS (?) end sentences that ASK something! 'Where are you going?'"
      },
      {
        question: "What do we use to separate items in a list?",
        options: ["Periods", "Commas", "Question marks", "Apostrophes"],
        correctAnswer: 1,
        explanation: "COMMAS separate items in a list! 'I bought apples, oranges, and bananas.'"
      },
      {
        question: "What does an apostrophe show in 'cat's toy'?",
        options: ["Multiple cats", "Ownership", "A question", "An action"],
        correctAnswer: 1,
        explanation: "The apostrophe shows OWNERSHIP - the toy belongs to the cat! For singular ownership, add 's!"
      },
      {
        question: "Which is correct?",
        options: ["Its raining.", "It's raining.", "Its' raining.", "Itsraining."],
        correctAnswer: 1,
        explanation: "'It's' means 'it is' (contraction)! 'Its' shows possession (no apostrophe). So: 'It's raining' = 'It is raining.'"
      },
      {
        question: "Where do periods and commas go with quotation marks?",
        options: ["Outside the quotes", "Inside the quotes", "Before the quotes", "It doesn't matter"],
        correctAnswer: 1,
        explanation: "Periods and commas go INSIDE quotation marks! 'She said, \"Hello.\"' NOT 'She said, \"Hello\".' This is the American rule!"
      },
      {
        question: "What does a colon introduce?",
        options: ["A question", "A list or explanation", "Ownership", "A pause"],
        correctAnswer: 1,
        explanation: "A COLON (:) introduces a LIST or EXPLANATION! 'You'll need: pencil, paper, eraser.' Or 'Here's the issue: we're late.'"
      },
      {
        question: "Which shows a contraction correctly?",
        options: ["Do'nt", "Don't", "Dont'", "Dont"],
        correctAnswer: 1,
        explanation: "'Don't' is correct! It's a contraction of 'do not' - the apostrophe replaces the missing 'o'!"
      },
      {
        question: "What punctuation shows strong emotion?",
        options: ["Period", "Comma", "Exclamation point", "Semicolon"],
        correctAnswer: 2,
        explanation: "EXCLAMATION POINTS (!) show strong emotion like excitement, surprise, or urgency! 'We won!' 'Watch out!'"
      }
    ]
  },
  604: {
    id: 604,
    title: 'Paragraph Writing',
    icon: '📄',
    description: 'Organizing your ideas',
    content: [
      "Let's build the PERFECT PARAGRAPH! 📄 The foundation of all writing!",
      "A paragraph is like a mini-essay!",
      "It's a group of sentences about ONE main idea!",
      "Mastering paragraphs makes you a GREAT writer!",
      "WHAT IS A PARAGRAPH? 🤔",
      "A paragraph = collection of sentences working together!",
      "They all support ONE main idea or topic!",
      "Usually 5-8 sentences (but can vary!)",
      "Has a clear beginning, middle, and end!",
      "THE 3-PART STRUCTURE: 🏗️",
      "Every good paragraph has THREE parts!",
      "PART 1: TOPIC SENTENCE! 🎯",
      "The FIRST sentence in the paragraph!",
      "States the MAIN IDEA - what the paragraph is about!",
      "It's like a mini-thesis for your paragraph!",
      "Examples of topic sentences:",
      "'Dogs make excellent pets for many reasons.'",
      "'Summer is the best season of the year.'",
      "'Learning to ride a bike requires practice and patience.'",
      "Notice: Each tells you EXACTLY what the paragraph will discuss!",
      "TIP: The topic sentence should be CLEAR and SPECIFIC!",
      "Weak: 'This is about animals.' (Too vague!)",
      "Strong: 'Golden retrievers are gentle, loyal family dogs.' (Specific!)",
      "PART 2: SUPPORTING SENTENCES! 🌟",
      "The MIDDLE of the paragraph!",
      "These sentences PROVE, EXPLAIN, or DESCRIBE the main idea!",
      "Usually 3-6 sentences!",
      "They provide:",
      "- Facts and statistics",
      "- Examples and illustrations",
      "- Reasons and explanations",
      "- Details and descriptions",
      "- Personal experiences",
      "Example: If topic sentence is 'Dogs make excellent pets'...",
      "Supporting sentence 1: 'They are loyal and loving companions.'",
      "Supporting sentence 2: 'Dogs provide protection for your home.'",
      "Supporting sentence 3: 'Playing with dogs encourages exercise.'",
      "Supporting sentence 4: 'Taking care of a dog teaches responsibility.'",
      "Each sentence SUPPORTS the main idea!",
      "PART 3: CONCLUDING SENTENCE! 🎬",
      "The LAST sentence!",
      "Wraps up the paragraph!",
      "Restates the main idea in a NEW way!",
      "Can summarize the key points!",
      "Can provide a final thought or conclusion!",
      "Examples:",
      "'For all these reasons, dogs truly are wonderful pets.'",
      "'Clearly, summer offers the most enjoyable activities.'",
      "'With practice, anyone can master bike riding.'",
      "DON'T just copy the topic sentence word-for-word!",
      "Say it differently or add a final insight!",
      "PUTTING IT ALL TOGETHER: Example Paragraph! 📝",
      "Let's see a complete paragraph:",
      "[TOPIC SENTENCE] 'Pizza is one of the most popular foods in America.'",
      "[SUPPORTING] 'People of all ages enjoy its delicious taste.'",
      "[SUPPORTING] 'Pizza restaurants can be found in almost every town.'",
      "[SUPPORTING] 'It's easy to customize with your favorite toppings.'",
      "[SUPPORTING] 'Whether for parties or casual dinners, pizza works for any occasion.'",
      "[CONCLUDING] 'No wonder Americans eat approximately 3 billion pizzas each year!'",
      "See how it flows? One main idea, supported details, strong ending!",
      "UNITY: Stay on Topic! 🎯",
      "UNITY means all sentences relate to the SAME topic!",
      "Don't wander off to other ideas!",
      "BAD EXAMPLE (lacks unity):",
      "'Dogs make great pets. They are loyal. Cats are independent. Dogs need exercise. I like ice cream.'",
      "Wait - cats? Ice cream? Off topic!",
      "GOOD EXAMPLE (has unity):",
      "'Dogs make great pets. They are loyal companions. Dogs love to play with their owners. They provide security for homes. Truly, dogs are wonderful animals.'",
      "Everything relates to dogs as pets!",
      "COHERENCE: Flow Smoothly! 🌊",
      "COHERENCE means sentences connect logically!",
      "Ideas flow from one to the next!",
      "Use TRANSITION WORDS to connect ideas!",
      "ADDING information: also, furthermore, in addition, moreover, additionally!",
      "'Dogs are loyal. FURTHERMORE, they are protective.'",
      "SHOWING EXAMPLES: for example, for instance, such as!",
      "'Many breeds work as service dogs. FOR EXAMPLE, German Shepherds often help police.'",
      "CONTRASTING: however, but, on the other hand, although, yet!",
      "'Dogs need attention. HOWEVER, they give love in return.'",
      "CAUSE/EFFECT: therefore, because, as a result, consequently!",
      "'Dogs need exercise. THEREFORE, owners stay active too.'",
      "TIME ORDER: first, next, then, finally, after, before!",
      "'FIRST, get a leash. THEN, attach it to the collar.'",
      "PARAGRAPH TYPES: Different Purposes! 📋",
      "TYPE 1: NARRATIVE Paragraphs (tell a story!)!",
      "Share an experience or event!",
      "Use chronological (time) order!",
      "Example topic: 'My first day of school was unforgettable.'",
      "TYPE 2: DESCRIPTIVE Paragraphs (paint a picture!)!",
      "Describe a person, place, thing, or experience!",
      "Use sensory details (sight, sound, smell, touch, taste)!",
      "Example topic: 'The old house on the hill looked haunted.'",
      "TYPE 3: EXPOSITORY Paragraphs (explain or inform!)!",
      "Give facts and information!",
      "Explain how something works or what something means!",
      "Example topic: 'Photosynthesis is how plants make food.'",
      "TYPE 4: PERSUASIVE Paragraphs (convince!)!",
      "Try to convince readers of your opinion!",
      "Give reasons and evidence!",
      "Example topic: 'Schools should have longer recess times.'",
      "INDENT OR NOT? 📐",
      "In handwritten or typed papers: INDENT the first line!",
      "Move it about 5 spaces (or 1 tab) to the right!",
      "This signals: NEW PARAGRAPH!",
      "In online writing: Often skip a line between paragraphs instead!",
      "PARAGRAPH LENGTH: How Long? 📏",
      "No exact rule, but typically 5-8 sentences!",
      "ACADEMIC writing: Often longer (7-12 sentences)!",
      "ONLINE writing: Often shorter (3-5 sentences - easier to read on screens)!",
      "RULE OF THUMB: One main idea = one paragraph!",
      "If you switch to a new idea, start a NEW paragraph!",
      "WHEN TO START A NEW PARAGRAPH: 🆕",
      "1. When you change TOPICS!",
      "'Paragraph 1: About dogs' → 'Paragraph 2: About cats'",
      "2. When you change TIME!",
      "'Paragraph 1: Morning activities' → 'Paragraph 2: Afternoon activities'",
      "3. When you change SPEAKERS (in dialogue)!",
      "Each new person speaking gets a new paragraph!",
      "4. When you change LOCATION!",
      "'Paragraph 1: At school' → 'Paragraph 2: At home'",
      "5. To emphasize something IMPORTANT!",
      "Sometimes one sentence gets its own paragraph for impact!",
      "COMMON PARAGRAPH MISTAKES: ⚠️",
      "MISTAKE #1: No clear topic sentence!",
      "Readers don't know what the paragraph is about!",
      "MISTAKE #2: Not enough support!",
      "Topic sentence with only 1-2 supporting sentences - needs MORE!",
      "MISTAKE #3: Going off-topic!",
      "Including sentences that don't relate to the main idea!",
      "MISTAKE #4: No concluding sentence!",
      "Paragraph just stops abruptly!",
      "MISTAKE #5: All sentences the same length!",
      "Makes writing boring! Mix short and long sentences!",
      "PRACTICE CHECKLIST: ✅",
      "Before calling a paragraph done, check:",
      "□ Do I have a clear topic sentence?",
      "□ Do all sentences relate to the main idea?",
      "□ Do I have enough supporting details (3-6)?",
      "□ Did I use transition words?",
      "□ Do I have a concluding sentence?",
      "□ Does everything flow logically?",
      "□ Did I indent (if required)?",
      "BUILDING TO LONGER WRITING: 📚",
      "Master paragraphs = master essays!",
      "An essay is just multiple paragraphs working together!",
      "Introduction paragraph",
      "Body paragraphs (supporting points)",
      "Conclusion paragraph",
      "Each paragraph = one main idea!",
      "REAL-WORLD PARAGRAPH EXAMPLE: 🌍",
      "Topic: Why exercise is important",
      "[TOPIC] 'Regular exercise provides numerous health benefits.'",
      "[SUPPORT 1] 'First, it strengthens your heart and improves cardiovascular health.'",
      "[SUPPORT 2] 'Additionally, exercise helps maintain a healthy weight.'",
      "[SUPPORT 3] 'It also reduces stress and improves mood by releasing endorphins.'",
      "[SUPPORT 4] 'Furthermore, regular physical activity strengthens bones and muscles.'",
      "[CONCLUDE] 'For all these reasons, making exercise part of your daily routine is one of the best decisions for your health.'",
      "Perfect structure! Topic → Support → Conclusion!",
      "Remember: One paragraph, one idea, three parts! 📄✨"
    ],
    questions: [
      {
        question: "What does a topic sentence do?",
        options: ["Ends the paragraph", "States the main idea", "Gives details", "Asks a question"],
        correctAnswer: 1,
        explanation: "The topic sentence STATES THE MAIN IDEA - it tells what the whole paragraph is about! It's the first sentence!"
      },
      {
        question: "What do supporting sentences do?",
        options: ["Start the paragraph", "Give details and examples", "End the paragraph", "Ask questions"],
        correctAnswer: 1,
        explanation: "Supporting sentences GIVE DETAILS AND EXAMPLES that prove, explain, or describe the main idea! They're the middle of the paragraph!"
      },
      {
        question: "How many main ideas should a paragraph have?",
        options: ["One", "Two", "As many as possible", "None"],
        correctAnswer: 0,
        explanation: "A paragraph should focus on ONE main idea! If you have a new idea, start a NEW paragraph. This is called unity!"
      },
      {
        question: "Which transition word shows you're adding information?",
        options: ["However", "Furthermore", "Because", "Before"],
        correctAnswer: 1,
        explanation: "'Furthermore' adds information! Others: also, additionally, moreover. 'However' contrasts, 'because' shows cause, 'before' shows time!"
      },
      {
        question: "What's the last sentence in a paragraph called?",
        options: ["Topic sentence", "Supporting sentence", "Concluding sentence", "Opening sentence"],
        correctAnswer: 2,
        explanation: "The CONCLUDING SENTENCE wraps up the paragraph! It restates the main idea in a new way or provides a final thought!"
      },
      {
        question: "What does 'unity' mean in paragraph writing?",
        options: ["Using big words", "All sentences relate to one topic", "Writing long sentences", "Starting with capital letters"],
        correctAnswer: 1,
        explanation: "UNITY means all sentences relate to the SAME TOPIC! Don't include unrelated ideas. Stay focused on your main idea!"
      },
      {
        question: "How many supporting sentences should a paragraph typically have?",
        options: ["1", "2", "3-6", "20"],
        correctAnswer: 2,
        explanation: "Typically 3-6 supporting sentences! Enough to fully explain and support your main idea, but not so many that you're off-topic!"
      },
      {
        question: "When should you start a new paragraph?",
        options: ["Never", "When you change topics or ideas", "After every sentence", "Only on new pages"],
        correctAnswer: 1,
        explanation: "Start a NEW PARAGRAPH when you change TOPICS, time, location, or speakers! One main idea = one paragraph!"
      }
    ]
  },
  605: {
    id: 605,
    title: 'Editing & Revising',
    icon: '✏️',
    description: 'Making your writing better',
    content: [
      "Welcome to the FINAL POLISH! ✏️ Let's make your writing SHINE!",
      "Writing is a PROCESS - nobody writes perfectly the first time!",
      "Even famous authors revise and edit multiple times!",
      "This is where good writing becomes GREAT writing!",
      "THE WRITING PROCESS: 5 Steps! 📝",
      "STEP 1: PREWRITING (Planning)",
      "Brainstorm ideas, organize thoughts!",
      "STEP 2: DRAFTING (Writing)",
      "Get your ideas down - don't worry about perfection!",
      "STEP 3: REVISING (Improving content)",
      "Change ideas, add details, reorganize!",
      "STEP 4: EDITING (Fixing mistakes)",
      "Correct spelling, grammar, punctuation!",
      "STEP 5: PUBLISHING (Sharing)",
      "Share your final, polished work!",
      "Today we focus on steps 3 & 4: REVISING and EDITING!",
      "REVISING vs EDITING: What's the Difference? 🤔",
      "People often confuse these!",
      "REVISING = BIG changes!",
      "Focus on: IDEAS, CONTENT, ORGANIZATION!",
      "Think: Making it better!",
      "EDITING = SMALL changes!",
      "Focus on: SPELLING, GRAMMAR, PUNCTUATION, CAPITALIZATION!",
      "Think: Making it correct!",
      "Remember: REVISE FIRST, then EDIT!",
      "Why? No point fixing spelling in a sentence you might delete!",
      "REVISING: Improving Your Writing! 🔄",
      "Revising means RE-SEEING your work!",
      "Look at it with fresh eyes!",
      "WHAT TO CHECK WHEN REVISING:",
      "1. CONTENT: Do I have enough information?",
      "Is anything missing?",
      "Do I need more examples or details?",
      "Should I add or remove information?",
      "2. ORGANIZATION: Does it flow logically?",
      "Is everything in the right order?",
      "Does each paragraph focus on one idea?",
      "Are my ideas connected with transitions?",
      "3. CLARITY: Is it easy to understand?",
      "Will readers understand what I mean?",
      "Am I being specific enough?",
      "4. WORD CHOICE: Are these the best words?",
      "Can I use stronger verbs?",
      "Weak: 'The dog went across the street.'",
      "Stronger: 'The dog dashed across the street!'",
      "Am I repeating words too much?",
      "5. AUDIENCE: Is it right for my readers?",
      "Writing for classmates vs writing for adults - different!",
      "Am I explaining things they might not know?",
      "6. PURPOSE: Does it achieve my goal?",
      "If persuading: Are my arguments strong?",
      "If explaining: Is it clear?",
      "If entertaining: Is it engaging?",
      "REVISING TECHNIQUES: 🛠️",
      "TECHNIQUE #1: Add Details!",
      "Weak: 'The house was old.'",
      "Better: 'The house had peeling paint, cracked windows, and a sagging roof.'",
      "TECHNIQUE #2: Delete Unnecessary Info!",
      "Cut sentences that don't support your main idea!",
      "If it doesn't add value - delete it!",
      "TECHNIQUE #3: Rearrange Sentences!",
      "Move sentences around for better flow!",
      "Put your strongest point first or last!",
      "TECHNIQUE #4: Combine Sentences!",
      "Choppy: 'The cat ran. It was fast. It was black.'",
      "Better: 'The fast black cat ran.'",
      "TECHNIQUE #5: Split Long Sentences!",
      "Too long: 'I went to the store and bought milk and eggs and bread and then I came home and made breakfast.'",
      "Better: 'I went to the store. I bought milk, eggs, and bread. Then I came home and made breakfast.'",
      "TECHNIQUE #6: Replace Weak Words!",
      "Weak verbs: go, went, said, got, have",
      "Strong verbs: raced, whispered, grabbed, possess!",
      "Overused adjectives: good, bad, nice, pretty",
      "Better adjectives: excellent, terrible, delightful, stunning!",
      "REVISING QUESTIONS TO ASK: 🤷",
      "□ Does my introduction hook readers?",
      "□ Is my main idea clear?",
      "□ Do all paragraphs support my main idea?",
      "□ Did I include enough details and examples?",
      "□ Do I use transition words to connect ideas?",
      "□ Does my conclusion wrap things up well?",
      "□ Did I stay on topic throughout?",
      "□ Is my writing interesting and engaging?",
      "EDITING: Fixing Mistakes! 🔍",
      "Now that content is good, fix the technical stuff!",
      "WHAT TO CHECK WHEN EDITING:",
      "1. SPELLING:",
      "Check every word carefully!",
      "Use spell-check BUT also read carefully - it misses some errors!",
      "'Their', 'there', and 'they're' are all spelled correctly but mean different things!",
      "2. GRAMMAR:",
      "Subject-verb agreement: 'The dog runs' not 'The dog run'",
      "Verb tenses: Stay consistent!",
      "Pronoun agreement: 'She' not 'they' for one person!",
      "Complete sentences: No fragments!",
      "3. PUNCTUATION:",
      "Periods at the end of statements!",
      "Commas in lists and compound sentences!",
      "Apostrophes for contractions and possession!",
      "Quotation marks for dialogue!",
      "4. CAPITALIZATION:",
      "First word of sentences!",
      "Proper nouns (names of people, places)!",
      "The pronoun 'I'!",
      "5. SENTENCE STRUCTURE:",
      "No run-on sentences!",
      "No comma splices!",
      "Vary sentence length!",
      "EDITING TECHNIQUES: 🛠️",
      "TECHNIQUE #1: Read Out Loud!",
      "THE BEST EDITING TRICK!",
      "You'll hear mistakes you missed when reading silently!",
      "Awkward phrases stand out!",
      "Missing words become obvious!",
      "TECHNIQUE #2: Read Backwards!",
      "Start at the last sentence, work to first!",
      "Helps catch spelling errors!",
      "You focus on individual words, not meaning!",
      "TECHNIQUE #3: Print It Out!",
      "Easier to spot errors on paper than screen!",
      "Use a different color pen to mark mistakes!",
      "TECHNIQUE #4: Take a Break!",
      "Don't edit immediately after writing!",
      "Wait hours or even a day!",
      "Fresh eyes catch more errors!",
      "TECHNIQUE #5: Use a Checklist!",
      "Go through once for EACH item!",
      "Once for spelling, once for punctuation, etc.!",
      "Don't try to catch everything at once!",
      "TECHNIQUE #6: Get Help!",
      "Ask someone else to read it!",
      "Fresh eyes catch things you miss!",
      "Peer editing = swapping papers with classmates!",
      "EDITING MARKS: Proofreading Symbols! ✏️",
      "Professional editors use special marks!",
      "Delete: Cross out with line",
      "Add: Use caret (^) mark",
      "New paragraph: ¶ symbol",
      "Capitalize: Three lines under letter",
      "Lowercase: Slash through capital",
      "These help mark changes clearly!",
      "COMMON MISTAKES TO LOOK FOR: ⚠️",
      "1. HOMOPHONES (sound alike, spelled different):",
      "Their/there/they're",
      "Your/you're",
      "Its/it's",
      "To/too/two",
      "2. COMMONLY MISSPELLED WORDS:",
      "A lot (NOT 'alot'!)",
      "Definitely (NOT 'definately'!)",
      "Because",
      "Separate",
      "3. COMMA ERRORS:",
      "Missing commas in compound sentences",
      "Comma splices (joining sentences with just comma)",
      "Missing commas after introductory words",
      "4. APOSTROPHE ERRORS:",
      "Its vs it's confusion",
      "Unnecessary apostrophes: 'The dog's bark' (ownership) vs 'The dogs bark' (plural)",
      "5. SENTENCE FRAGMENTS:",
      "Incomplete thoughts missing subject or verb!",
      "6. RUN-ON SENTENCES:",
      "Two sentences without proper punctuation!",
      "THE EDITING CHECKLIST: ✅",
      "Go through your paper multiple times:",
      "PASS 1 - Spelling:",
      "□ Checked every word?",
      "□ Used dictionary for unsure words?",
      "□ Watched for homophones?",
      "PASS 2 - Grammar:",
      "□ Subject-verb agreement?",
      "□ Consistent verb tenses?",
      "□ Complete sentences only?",
      "PASS 3 - Punctuation:",
      "□ Periods, commas, apostrophes correct?",
      "□ Quotation marks used properly?",
      "□ No run-ons or comma splices?",
      "PASS 4 - Capitalization:",
      "□ Sentence beginnings?",
      "□ Proper nouns?",
      "□ The word 'I'?",
      "PASS 5 - Format:",
      "□ Name and date (if required)?",
      "□ Title?",
      "□ Paragraphs indented?",
      "□ Neat and legible?",
      "PEER EDITING: Help Each Other! 🤝",
      "Peer editing = students editing each other's work!",
      "BENEFITS:",
      "- Fresh eyes catch mistakes!",
      "- Learn from others' writing!",
      "- Get new ideas!",
      "HOW TO BE A GOOD PEER EDITOR:",
      "1. Be KIND and HELPFUL!",
      "Say what's good first!",
      "'I love your opening sentence!'",
      "2. Be SPECIFIC!",
      "Not: 'This is confusing.'",
      "Better: 'Can you add more details about the character?'",
      "3. Ask QUESTIONS!",
      "'What did you mean here?'",
      "'Can you explain this more?'",
      "4. Give SUGGESTIONS, not commands!",
      "'Maybe you could...'",
      "'What if you tried...'",
      "5. Focus on BIG issues first!",
      "Ideas and organization before tiny spelling errors!",
      "SELF-EDITING vs PROFESSIONAL EDITING: 📚",
      "Self-editing: You edit your own work!",
      "Hard because you know what you MEANT to say!",
      "That's why taking breaks helps!",
      "Professional editing: Others edit for you!",
      "Book editors, newspaper editors!",
      "Even they edit multiple times!",
      "PRACTICE EXAMPLE: Before and After! 🔄",
      "BEFORE (First Draft):",
      "'yesterday I went to the stor. I buyed milk and egg and bread. it was fun. Then I come home.'",
      "AFTER (Revised & Edited):",
      "'Yesterday, I went to the grocery store. I bought milk, eggs, and bread for the week. Shopping with my mom was fun because she let me pick out my favorite cereal. When we finished, we drove home and unpacked everything.'",
      "Changes made:",
      "- Fixed spelling and capitalization",
      "- Fixed grammar ('buyed' → 'bought', 'come' → 'came')",
      "- Added details (grocery store, for the week, with mom)",
      "- Improved organization and flow",
      "- Added more interesting information (cereal, unpacked)",
      "FINAL TIPS: 💡",
      "1. Don't rush! Quality takes time!",
      "2. Multiple passes catch more errors!",
      "3. Read out loud - SERIOUSLY, it works!",
      "4. Don't rely only on spell-check!",
      "5. Fresh eyes are valuable - take breaks!",
      "6. Be proud of your hard work!",
      "Remember: GREAT writers aren't born - they REVISE and EDIT! ✏️✨",
      "Your first draft is just the beginning!",
      "Polish makes your writing SHINE!"
    ],
    questions: [
      {
        question: "What is revising?",
        options: ["Fixing spelling", "Changing ideas and organization", "Adding periods", "Copying over"],
        correctAnswer: 1,
        explanation: "Revising is changing and improving IDEAS and ORGANIZATION! It's about making content better - adding details, rearranging, clarifying!"
      },
      {
        question: "What is editing?",
        options: ["Writing the first draft", "Fixing mistakes in spelling and grammar", "Choosing a topic", "Reading someone else's work"],
        correctAnswer: 1,
        explanation: "Editing is fixing MISTAKES in spelling, grammar, punctuation, and capitalization! It's making your writing correct!"
      },
      {
        question: "Which should you do FIRST?",
        options: ["Edit", "Revise", "Publish", "Both at same time"],
        correctAnswer: 1,
        explanation: "REVISE FIRST, then edit! Why? No point fixing spelling in a sentence you might delete during revising!"
      },
      {
        question: "What's the BEST trick for catching mistakes?",
        options: ["Read it silently very fast", "Read it out loud", "Don't read it again", "Just use spell-check"],
        correctAnswer: 1,
        explanation: "Reading OUT LOUD is the BEST trick! You'll hear mistakes you missed when reading silently. Awkward phrases and missing words become obvious!"
      },
      {
        question: "What should you look for when REVISING?",
        options: ["Only spelling", "Ideas, organization, clarity", "Only punctuation", "Just capital letters"],
        correctAnswer: 1,
        explanation: "When REVISING, look at IDEAS, ORGANIZATION, and CLARITY! Do you have enough details? Does it flow? Is it clear? Save grammar for editing!"
      },
      {
        question: "What helps you edit better?",
        options: ["Editing immediately after writing", "Never taking breaks", "Taking a break before editing", "Editing while watching TV"],
        correctAnswer: 2,
        explanation: "Taking a BREAK before editing helps! Wait hours or a day. Fresh eyes catch more mistakes than tired eyes that just finished writing!"
      },
      {
        question: "What's peer editing?",
        options: ["Editing alone", "Students editing each other's work", "Only teachers editing", "Computers editing"],
        correctAnswer: 1,
        explanation: "Peer editing is students editing EACH OTHER'S work! Fresh eyes catch mistakes. Plus you learn from others' writing!"
      },
      {
        question: "Which is a strong verb replacement for 'went'?",
        options: ["Goed", "Dashed", "Go", "Went quickly"],
        correctAnswer: 1,
        explanation: "'Dashed' is a strong verb! It's specific and vivid. Better than weak 'went'. Other strong options: raced, sprinted, hurried, wandered!"
      }
    ]
  },
  // Ancient Civilizations (701-705)
  701: {
    id: 701,
    title: 'Ancient Egypt',
    icon: '🔺',
    description: 'Land of pyramids and pharaohs',
    content: [
      "Welcome to ANCIENT EGYPT! 🔺 Step back 5,000 years in time!",
      "Imagine a land of golden deserts, mighty pyramids, and powerful rulers!",
      "Ancient Egypt was one of the GREATEST civilizations EVER!",
      "It lasted over 3,000 years - longer than any other ancient civilization!",
      "Let's explore this amazing world!",
      "THE NILE RIVER: Egypt's Lifeline! 🌊",
      "Egypt is in AFRICA, in the desert!",
      "But one AMAZING river flows through it: The NILE!",
      "The Nile is the LONGEST river in the world!",
      "It flows over 4,000 miles from south to north!",
      "Ancient Egyptians called Egypt 'The Gift of the Nile'!",
      "Why? Because without the Nile, Egypt would be all desert!",
      "Every year, the Nile FLOODED!",
      "This wasn't bad - it was GOOD!",
      "The floods brought rich, black soil!",
      "Perfect for growing crops!",
      "Egyptians grew wheat, barley, vegetables, and flax for cloth!",
      "The Nile also provided fish and water!",
      "It was their highway - boats traveled up and down!",
      "TIMELINE: Egypt's Long History! 📅",
      "Ancient Egypt lasted from about 3100 BCE to 30 BCE!",
      "That's over 3,000 years!",
      "Divided into three main periods:",
      "OLD KINGDOM (2686-2181 BCE): The Pyramid Age!",
      "MIDDLE KINGDOM (2055-1650 BCE): Art and literature flourished!",
      "NEW KINGDOM (1550-1077 BCE): Egypt's most powerful time!",
      "Plus two 'intermediate periods' in between!",
      "And the LATE PERIOD when other powers ruled!",
      "Finally ended when Rome conquered Egypt in 30 BCE!",
      "PHARAOHS: The God-Kings! 👑",
      "Egypt's rulers were called PHARAOHS!",
      "Pharaoh means 'Great House'!",
      "Pharaohs weren't just kings - Egyptians believed they were GODS!",
      "They had absolute power over everything!",
      "Pharaohs made all the laws!",
      "They owned all the land!",
      "They controlled the army!",
      "They were also high priests of the temples!",
      "FAMOUS PHARAOHS:",
      "KHUFU: Built the Great Pyramid!",
      "HATSHEPSUT: A powerful female pharaoh!",
      "Ruled as a man, even wore a fake beard!",
      "AKHENATEN: Tried to change Egypt's religion!",
      "TUTANKHAMUN (King Tut): Became pharaoh at age 9!",
      "Died young, but his tomb was found intact in 1922!",
      "RAMESSES II: Ruled for 66 years!",
      "Built more monuments than any other pharaoh!",
      "CLEOPATRA VII: Last pharaoh of Egypt!",
      "Pharaohs wore special symbols of power:",
      "DOUBLE CROWN: Combined crowns of Upper and Lower Egypt!",
      "FALSE BEARD: Sign of divinity!",
      "CROOK AND FLAIL: Symbols of kingship!",
      "THE PYRAMIDS: Tombs for Eternity! 🔺",
      "Pyramids are Egypt's most famous monuments!",
      "They were TOMBS for pharaohs!",
      "Built to protect the pharaoh's body forever!",
      "THE GREAT PYRAMID OF GIZA:",
      "Built for Pharaoh Khufu around 2560 BCE!",
      "Originally 481 feet tall - tallest building for 3,800 years!",
      "Made of 2.3 MILLION stone blocks!",
      "Each block weighs 2.5 to 15 tons!",
      "Took about 20 years to build!",
      "HOW DID THEY BUILD THEM?",
      "No machines, no wheels, no iron tools!",
      "Workers used copper tools and stone hammers!",
      "Stones were cut from quarries!",
      "Moved on wooden sleds and rollers!",
      "Probably used ramps to lift blocks!",
      "Required thousands of workers!",
      "Not slaves - paid workers!",
      "Amazing engineering for 4,500 years ago!",
      "OTHER FAMOUS PYRAMIDS:",
      "The BENT PYRAMID: Changed angles halfway up!",
      "The RED PYRAMID: First successful smooth pyramid!",
      "STEP PYRAMID of Djoser: Oldest pyramid, looked like stairs!",
      "The pyramids at Giza also include the SPHINX!",
      "Giant statue with a lion's body and human head!",
      "Guards the pyramids!",
      "HIEROGLYPHICS: Picture Writing! 📜",
      "Egyptians invented their own writing: HIEROGLYPHICS!",
      "'Hieros' = sacred, 'glyphos' = carving!",
      "Used pictures and symbols to represent sounds and words!",
      "Over 700 different symbols!",
      "TYPES OF HIEROGLYPHS:",
      "Some pictures = the thing shown (owl = owl)!",
      "Some pictures = sounds (like letters)!",
      "Some pictures = ideas (sun = day or light)!",
      "Written in rows or columns!",
      "Could be read left to right OR right to left!",
      "How to tell? Animals face the START of the line!",
      "WHAT DID THEY WRITE ON?",
      "Stone monuments and temple walls!",
      "PAPYRUS - paper made from reeds!",
      "Cut papyrus stems into strips!",
      "Pressed them together in layers!",
      "Dried in the sun!",
      "This is where our word 'paper' comes from!",
      "CRACKING THE CODE:",
      "For 1,400 years, no one could read hieroglyphics!",
      "In 1799, soldiers found the ROSETTA STONE!",
      "Same message in three languages: hieroglyphics, demotic, and GREEK!",
      "Jean-François Champollion decoded it in 1822!",
      "Now we can read ancient Egyptian writing!",
      "MUMMIES: Preserved for Eternity! 🏺",
      "Egyptians believed in LIFE AFTER DEATH!",
      "The body needed to be preserved!",
      "So they created MUMMIES!",
      "THE MUMMIFICATION PROCESS:",
      "Took 70 days!",
      "STEP 1: Wash body in palm wine!",
      "STEP 2: Remove organs (except heart)!",
      "Brain removed through nose!",
      "Organs stored in special jars called CANOPIC JARS!",
      "STEP 3: Cover body in natron (salt) for 40 days!",
      "This dried out the body!",
      "STEP 4: Wrap in linen bandages!",
      "Could use 20 layers and hundreds of yards!",
      "STEP 5: Place in decorated coffin!",
      "Rich people had multiple nested coffins!",
      "WHY MUMMIFY?",
      "Egyptians believed the soul needed the body in the afterlife!",
      "The person's 'ka' (life force) would return to the body!",
      "WHO WAS MUMMIFIED?",
      "Pharaohs and nobles, definitely!",
      "But also regular people if family could afford it!",
      "Even animals were mummified!",
      "Cats, dogs, birds, crocodiles - as offerings to gods!",
      "EGYPTIAN RELIGION: Many Gods! 🌟",
      "Egyptians believed in MANY gods!",
      "Over 2,000 different gods and goddesses!",
      "MAJOR GODS:",
      "RA (Re): Sun god, most important!",
      "Shown with falcon head and sun disk!",
      "OSIRIS: God of the afterlife!",
      "Judge of the dead!",
      "ISIS: Goddess of magic and motherhood!",
      "Wife of Osiris!",
      "ANUBIS: God of mummification!",
      "Shown with jackal head!",
      "HORUS: Sky god, protector of pharaoh!",
      "Shown with falcon head!",
      "THOTH: God of wisdom and writing!",
      "Shown with ibis bird head!",
      "BASTET: Cat goddess of home and protection!",
      "Many gods had ANIMAL heads and human bodies!",
      "THE AFTERLIFE:",
      "Egyptians believed in a paradise after death!",
      "Called the FIELD OF REEDS!",
      "But you had to pass a test!",
      "Your HEART was weighed against a feather!",
      "The feather represented truth and justice!",
      "If your heart was light (you were good), you entered paradise!",
      "If heavy (you were bad), a monster ate your heart!",
      "TEMPLES: Houses of the Gods! 🏛️",
      "Huge stone temples honored the gods!",
      "KARNAK: One of the largest religious buildings ever!",
      "Giant columns, statues, obelisks!",
      "Only priests could enter inner areas!",
      "Temples were very wealthy and powerful!",
      "EGYPTIAN SOCIETY: Who's Who? 👥",
      "Egyptian society was a pyramid shape!",
      "TOP: PHARAOH - the god-king!",
      "LEVEL 2: NOBLES and PRIESTS - advisors, temple workers!",
      "LEVEL 3: SCRIBES - writers and record keepers!",
      "Important job! Required years of training!",
      "LEVEL 4: CRAFTSMEN and MERCHANTS - skilled workers!",
      "LEVEL 5: FARMERS - most Egyptians!",
      "BOTTOM: SLAVES - prisoners of war!",
      "Most Egyptians were farmers!",
      "They farmed land owned by pharaoh or temples!",
      "Paid taxes in grain!",
      "DAILY LIFE IN ANCIENT EGYPT: 🏠",
      "HOMES: Made of mud bricks!",
      "Flat roofs for sleeping on hot nights!",
      "CLOTHING: Light linen clothes - Egypt was HOT!",
      "Men: kilts or loincloths!",
      "Women: simple dresses!",
      "FOOD: Bread and beer (from barley)!",
      "Fish, vegetables, fruit!",
      "Rich people: meat, honey, fancy bread!",
      "BEAUTY: Egyptians loved makeup!",
      "Both men and women wore black eyeliner!",
      "Protected eyes from sun and flies!",
      "Wigs were fashionable!",
      "CHILDREN: Played with toys - dolls, balls, spinning tops!",
      "Learned trades from parents!",
      "Only rich boys went to scribe school!",
      "EGYPTIAN ACHIEVEMENTS: 🌟",
      "CALENDAR: 365-day calendar!",
      "12 months of 30 days, plus 5 extra days!",
      "MATHEMATICS: Used for building, surveying, taxes!",
      "Knew geometry and fractions!",
      "MEDICINE: Advanced for their time!",
      "Performed surgery!",
      "Created medical texts describing treatments!",
      "ASTRONOMY: Studied the stars!",
      "Aligned pyramids to stars!",
      "ENGINEERING: Master builders!",
      "Pyramids, temples, irrigation systems!",
      "ART: Beautiful paintings and sculptures!",
      "Followed strict rules - pharaohs always largest!",
      "Figures shown from side!",
      "PAPYRUS: Invented paper!",
      "Changed the world!",
      "THE END OF ANCIENT EGYPT: 😢",
      "Egypt's power declined over time!",
      "Foreign invaders conquered it!",
      "Persians, Greeks, finally Romans!",
      "In 30 BCE, Cleopatra VII died!",
      "Egypt became part of the Roman Empire!",
      "But Egyptian culture influenced Greece and Rome!",
      "And it still fascinates us today!",
      "EGYPT'S LEGACY TODAY: ✨",
      "We still use their calendar system!",
      "Paper came from papyrus!",
      "Egyptian art inspires modern artists!",
      "Egyptian architecture influences buildings worldwide!",
      "Tourists visit pyramids and temples!",
      "Museums display Egyptian treasures!",
      "King Tut's tomb is world-famous!",
      "Egyptian mythology appears in books and movies!",
      "Ancient Egypt reminds us that great civilizations can last thousands of years! 🔺👑"
    ],
    questions: [
      {
        question: "What were the kings of Egypt called?",
        options: ["Presidents", "Pharaohs", "Emperors", "Princes"],
        correctAnswer: 1,
        explanation: "The rulers of ancient Egypt were called PHARAOHS! They were considered god-kings with absolute power. The word means 'Great House'!"
      },
      {
        question: "What were pyramids used for?",
        options: ["Schools", "Tombs for pharaohs", "Stores", "Homes"],
        correctAnswer: 1,
        explanation: "Pyramids were giant TOMBS built for pharaohs! They protected the pharaoh's body for the afterlife. The Great Pyramid took 20 years to build!"
      },
      {
        question: "What river was ancient Egypt built around?",
        options: ["Amazon", "Mississippi", "Nile", "Thames"],
        correctAnswer: 2,
        explanation: "Ancient Egypt developed along the NILE RIVER! It's the longest river in the world. Annual floods brought rich soil for farming. Egyptians called Egypt 'The Gift of the Nile'!"
      },
      {
        question: "What was Egyptian picture writing called?",
        options: ["Alphabet", "Hieroglyphics", "Cursive", "Emojis"],
        correctAnswer: 1,
        explanation: "Egyptian writing was called HIEROGLYPHICS! It used over 700 pictures and symbols. The Rosetta Stone helped us decode it in 1822!"
      },
      {
        question: "Why did Egyptians make mummies?",
        options: ["For fun", "To scare enemies", "To preserve bodies for afterlife", "For decoration"],
        correctAnswer: 2,
        explanation: "Egyptians made mummies to PRESERVE bodies for the AFTERLIFE! They believed the soul needed the body. The process took 70 days and involved removing organs and wrapping in linen!"
      },
      {
        question: "What material did Egyptians invent to write on?",
        options: ["Plastic", "Papyrus", "Cotton", "Wood"],
        correctAnswer: 1,
        explanation: "Egyptians invented PAPYRUS - the first paper! Made from reeds pressed together and dried. Our word 'paper' comes from 'papyrus'!"
      },
      {
        question: "Who was the last pharaoh of Egypt?",
        options: ["King Tut", "Cleopatra VII", "Ramesses II", "Khufu"],
        correctAnswer: 1,
        explanation: "CLEOPATRA VII was the last pharaoh! When she died in 30 BCE, Egypt became part of the Roman Empire, ending 3,000 years of pharaonic rule!"
      },
      {
        question: "What happens if your heart was 'light' in the afterlife test?",
        options: ["You were punished", "You entered paradise", "You became a mummy", "You returned to Earth"],
        correctAnswer: 1,
        explanation: "If your heart was LIGHT (you were good), you entered paradise - the Field of Reeds! Your heart was weighed against a feather representing truth. If heavy, a monster ate it!"
      }
    ]
  },

};
