interface Question {
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

interface TopicLesson {
  id: number;
  title: string;
  icon: string;
  description: string;
  content: string[];
  questions: Question[];
}

export const lessons: { [key: number]: TopicLesson } = {
  702: {
    id: 702,
    title: 'Ancient Greece',
    icon: '🏺',
    description: 'Birthplace of democracy',
    content: [
      "Welcome to ANCIENT GREECE! 🏺 Where democracy, philosophy, and the Olympics were born!",
      "Get ready to explore one of the most influential civilizations EVER!",
      "Greece shaped art, government, science, and thinking for all time!",
      "Let's visit this incredible ancient world!",
      "ANCIENT GREECE: The Basics! 🗺️",
      "Ancient Greece wasn't ONE country!",
      "It was made up of many CITY-STATES!",
      "Each city-state was like its own mini-country!",
      "The most famous: ATHENS and SPARTA!",
      "Greece is in southeastern Europe!",
      "Lots of islands and mountains!",
      "Surrounded by Mediterranean, Aegean, and Ionian seas!",
      "Greeks were excellent sailors and traders!",
      "Greek civilization thrived from about 800 BCE to 146 BCE!",
      "THE CITY-STATES: Independent Powers! 🏛️",
      "CITY-STATE = polis (that's Greek!)!",
      "Each polis included a city and surrounding farmland!",
      "Each had its own government, laws, army, and money!",
      "Sometimes they fought each other!",
      "Sometimes they united against common enemies!",
      "ATHENS: The Intellectual Center! 🎭",
      "Athens valued EDUCATION, ART, and DEMOCRACY!",
      "Home of famous philosophers!",
      "Built the beautiful PARTHENON temple!",
      "Dedicated to goddess Athena!",
      "Athenians loved debate and learning!",
      "Boys went to school to learn reading, writing, music, and sports!",
      "SPARTA: The Military Machine! ⚔️",
      "Sparta valued STRENGTH and DISCIPLINE!",
      "All about military training!",
      "Boys entered military training at age 7!",
      "Lived in barracks until age 30!",
      "Spartan warriors were FIERCE!",
      "Even Spartan girls trained in athletics!",
      "Athens vs Sparta = brains vs brawn!",
      "DEMOCRACY: Power to the People! 🗳️",
      "Athens invented DEMOCRACY around 508 BCE!",
      "Democracy = 'rule by the people'!",
      "'Demos' = people, 'kratos' = power!",
      "Male citizens could vote on laws!",
      "They gathered at the Assembly to debate!",
      "This was DIRECT democracy - everyone voted directly!",
      "(Today we have REPRESENTATIVE democracy - we elect people to vote for us!)",
      "BUT: Not everyone could participate!",
      "Women couldn't vote!",
      "Slaves couldn't vote!",
      "Foreigners couldn't vote!",
      "Still, it was revolutionary for the time!",
      "Modern democracies copied this idea!",
      "GREEK MYTHOLOGY: Gods and Goddesses! ⚡",
      "Greeks believed in MANY gods!",
      "The gods lived on MOUNT OLYMPUS - Greece's highest mountain!",
      "Gods were like super-powered humans - they had emotions, fought, fell in love!",
      "THE TWELVE OLYMPIANS:",
      "ZEUS: King of gods, god of sky and thunder!",
      "Threw lightning bolts!",
      "HERA: Queen of gods, goddess of marriage!",
      "Zeus's wife (and sister)!",
      "POSEIDON: God of the sea!",
      "Carried a trident, caused earthquakes!",
      "ATHENA: Goddess of wisdom and war strategy!",
      "Born from Zeus's head - fully grown and armored!",
      "APOLLO: God of sun, music, poetry, healing!",
      "ARTEMIS: Goddess of hunt and moon!",
      "Apollo's twin sister!",
      "ARES: God of war (the violent kind)!",
      "APHRODITE: Goddess of love and beauty!",
      "HEPHAESTUS: God of fire and blacksmithing!",
      "Made weapons for the gods!",
      "HERMES: Messenger god, god of travelers!",
      "Wore winged sandals!",
      "DEMETER: Goddess of harvest and agriculture!",
      "DIONYSUS: God of wine and celebration!",
      "Greeks told amazing MYTHS about these gods!",
      "Heroes like Hercules, Perseus, Odysseus!",
      "THE OLYMPIC GAMES: Athletic Competition! 🏅",
      "Started in 776 BCE in Olympia, Greece!",
      "Held every 4 years - just like today!",
      "A religious festival honoring ZEUS!",
      "ALL Greek city-states declared a truce during games!",
      "Even if they were at war, they stopped fighting!",
      "ANCIENT OLYMPIC EVENTS:",
      "Running races (short and long distance)!",
      "Wrestling!",
      "Boxing!",
      "Pentathlon (5 events: running, jumping, discus, javelin, wrestling)!",
      "Chariot racing!",
      "Only MEN could compete!",
      "Athletes competed NAKED!",
      "(That's why women couldn't watch!)!",
      "Winners got olive wreaths - not medals!",
      "Great honor for their city-state!",
      "Modern Olympics restarted in 1896!",
      "GREEK PHILOSOPHY: Love of Wisdom! 💭",
      "Philosophy = 'love of wisdom'!",
      "Greek thinkers asked BIG questions!",
      "What is truth? What is justice? How should we live?",
      "THE GREAT PHILOSOPHERS:",
      "SOCRATES (469-399 BCE):",
      "Asked questions to help people think!",
      "Famous saying: 'Know thyself!'",
      "Believed in questioning everything!",
      "Executed for 'corrupting' young minds!",
      "PLATO (428-348 BCE):",
      "Student of Socrates!",
      "Founded The Academy - like a university!",
      "Wrote about ideal government and justice!",
      "Famous work: 'The Republic'!",
      "ARISTOTLE (384-322 BCE):",
      "Student of Plato!",
      "Teacher of Alexander the Great!",
      "Studied EVERYTHING: logic, science, politics, ethics!",
      "Said: 'We are what we repeatedly do!'",
      "These three shaped Western thought forever!",
      "GREEK ACHIEVEMENTS: Science & Math! 🔬",
      "Greeks made HUGE advances!",
      "MATHEMATICS:",
      "PYTHAGORAS: The Pythagorean theorem (a² + b² = c²)!",
      "EUCLID: Father of geometry!",
      "Used logic and proofs!",
      "SCIENCE:",
      "HIPPOCRATES: Father of medicine!",
      "Said doctors should 'do no harm'!",
      "ARCHIMEDES: Brilliant mathematician and inventor!",
      "Discovered principles of levers and pulleys!",
      "Shouted 'Eureka!' ('I found it!') in his bath!",
      "ASTRONOMY:",
      "Greeks knew Earth was round!",
      "Studied stars and planets!",
      "ERATOSTHENES calculated Earth's circumference!",
      "GREEK ART & ARCHITECTURE: Beauty in Balance! 🏛️",
      "Greeks valued BEAUTY, HARMONY, and PROPORTION!",
      "ARCHITECTURE:",
      "Built stunning marble temples!",
      "Three column styles: Doric (simple), Ionic (scrolls), Corinthian (fancy leaves)!",
      "THE PARTHENON: Athens's most famous temple!",
      "Built for goddess Athena!",
      "Perfect proportions!",
      "SCULPTURE:",
      "Made realistic statues of gods and humans!",
      "Showed ideal human form!",
      "Famous: Venus de Milo, Discobolus (discus thrower)!",
      "POTTERY:",
      "Black and red figure pottery!",
      "Showed myths and daily life!",
      "GREEK THEATER: Drama is Born! 🎭",
      "Greeks INVENTED theater!",
      "Plays performed at festivals!",
      "TWO TYPES:",
      "TRAGEDY: Serious plays about heroes and fate!",
      "Famous writers: Sophocles, Euripides, Aeschylus!",
      "COMEDY: Funny plays making fun of politicians!",
      "Famous writer: Aristophanes!",
      "Actors wore MASKS to show emotions!",
      "Only men could be actors!",
      "Open-air amphitheaters held thousands!",
      "We still use these words: drama, theater, comedy, tragedy!",
      "THE PERSIAN WARS: Greece vs Empire! ⚔️",
      "Persia was a HUGE empire!",
      "Much bigger and stronger than Greek city-states!",
      "But Greece fought back!",
      "FAMOUS BATTLES:",
      "MARATHON (490 BCE): Athens defeated Persia!",
      "A messenger ran 26 miles to bring news - that's why we have marathons!",
      "THERMOPYLAE (480 BCE): 300 Spartans held off Persian army!",
      "Bought time for Greece to prepare!",
      "SALAMIS (480 BCE): Greek ships defeated Persian fleet!",
      "Greece's unity and determination won!",
      "ALEXANDER THE GREAT: World Conqueror! 👑",
      "Born 356 BCE in Macedonia (northern Greece)!",
      "Son of King Philip II!",
      "Tutored by ARISTOTLE!",
      "Became king at age 20!",
      "Conquered the Persian Empire!",
      "Created empire from Greece to India!",
      "Never lost a battle!",
      "Spread Greek culture everywhere (Hellenistic period)!",
      "Died at age 32 - maybe poisoned!",
      "One of history's greatest military leaders!",
      "DAILY LIFE IN ANCIENT GREECE: 🏠",
      "HOMES: Simple, made of mud bricks!",
      "Rooms built around central courtyard!",
      "FOOD: Bread, olives, cheese, fish!",
      "Wine mixed with water!",
      "Honey for sweetness (no sugar!)!",
      "CLOTHING: Simple tunics and togas!",
      "Men wore short tunics!",
      "Women wore long dresses (peplos or chiton)!",
      "EDUCATION: Only for boys from wealthy families!",
      "Learned reading, writing, music, athletics!",
      "Girls stayed home, learned household skills!",
      "GREEK LANGUAGE & ALPHABET: 📖",
      "Greeks developed their own alphabet!",
      "Based on Phoenician alphabet!",
      "24 letters - we still use some!",
      "Alpha, Beta, Gamma, Delta... (sound familiar?)!",
      "Many English words come from Greek!",
      "Democracy, philosophy, theater, athlete, Olympic!",
      "THE LEGACY OF GREECE: ✨",
      "Ancient Greece ended when Rome conquered it in 146 BCE!",
      "But Greek influence NEVER died!",
      "Romans copied Greek culture!",
      "Renaissance scholars studied Greek texts!",
      "GREECE GAVE US:",
      "Democracy and citizenship!",
      "Philosophy and logic!",
      "Scientific method!",
      "Olympic Games!",
      "Theater and drama!",
      "Beautiful architecture!",
      "Mythology and literature!",
      "Foundation of Western civilization!",
      "We still study Plato and Aristotle!",
      "We still admire the Parthenon!",
      "We still compete in the Olympics!",
      "Ancient Greece shaped the modern world! 🏺⚡"
    ],
    questions: [
      {
        question: "What type of government did Athens invent?",
        options: ["Monarchy", "Democracy", "Dictatorship", "Empire"],
        correctAnswer: 1,
        explanation: "Athens invented DEMOCRACY around 508 BCE! Democracy means 'rule by the people.' Male citizens could vote directly on laws at the Assembly!"
      },
      {
        question: "What famous games did Greece create?",
        options: ["World Cup", "Super Bowl", "Olympic Games", "World Series"],
        correctAnswer: 2,
        explanation: "Ancient Greece created the OLYMPIC GAMES in 776 BCE! Held every 4 years in Olympia to honor Zeus. Modern Olympics restarted in 1896!"
      },
      {
        question: "Where did Greeks believe their gods lived?",
        options: ["Under the sea", "Mount Olympus", "In temples", "In caves"],
        correctAnswer: 1,
        explanation: "Greeks believed their gods lived on MOUNT OLYMPUS - Greece's highest mountain! The twelve Olympians included Zeus, Athena, Poseidon, and others!"
      },
      {
        question: "Who were the three great Greek philosophers?",
        options: ["Zeus, Hera, Apollo", "Socrates, Plato, Aristotle", "Homer, Virgil, Ovid", "Pericles, Leonidas, Philip"],
        correctAnswer: 1,
        explanation: "The three great philosophers were SOCRATES, PLATO, and ARISTOTLE! Socrates questioned everything, Plato founded The Academy, and Aristotle tutored Alexander the Great!"
      },
      {
        question: "What were Greek city-states called?",
        options: ["Polis", "Forum", "Agora", "Acropolis"],
        correctAnswer: 0,
        explanation: "Greek city-states were called POLIS! Each was independent with its own government, laws, and army. Athens and Sparta were the most famous!"
      },
      {
        question: "Who conquered from Greece to India?",
        options: ["Julius Caesar", "Alexander the Great", "Pericles", "Leonidas"],
        correctAnswer: 1,
        explanation: "ALEXANDER THE GREAT conquered from Greece to India! He became king at 20, never lost a battle, and spread Greek culture everywhere. He died at 32!"
      },
      {
        question: "What did Spartan society focus on?",
        options: ["Art and poetry", "Trade and money", "Military and strength", "Philosophy and debate"],
        correctAnswer: 2,
        explanation: "Sparta focused on MILITARY and STRENGTH! Boys entered training at age 7 and lived in barracks until 30. Spartan warriors were the most feared in Greece!"
      },
      {
        question: "What battle features 300 Spartans?",
        options: ["Marathon", "Salamis", "Thermopylae", "Troy"],
        correctAnswer: 2,
        explanation: "The Battle of THERMOPYLAE (480 BCE) featured 300 Spartans! They held off the massive Persian army, buying time for Greece to prepare. A legendary last stand!"
      }
    ]
  },
  703: {
    id: 703,
    title: 'Ancient Rome',
    icon: '🏛️',
    description: 'Empire that ruled the world',
    content: [
      "Welcome to ANCIENT ROME! 🏛️ The empire that ruled the world!",
      "From a tiny city to the greatest empire in history!",
      "Rome shaped law, language, architecture, and government!",
      "Let's explore this mighty civilization!",
      "THE RISE OF ROME: From Village to Empire! 📈",
      "Rome started as a small village in Italy!",
      "Founded (according to legend) in 753 BCE by ROMULUS!",
      "Located on the Tiber River!",
      "Started with just 7 hills!",
      "THREE PERIODS OF ROMAN HISTORY:",
      "ROMAN KINGDOM (753-509 BCE): Ruled by kings!",
      "ROMAN REPUBLIC (509-27 BCE): Ruled by elected officials!",
      "ROMAN EMPIRE (27 BCE-476 CE): Ruled by emperors!",
      "At its height, Rome controlled 2.3 million square miles!",
      "From Britain to Egypt, from Spain to Syria!",
      "Over 50 million people lived in the empire!",
      "THE ROMAN REPUBLIC: Power to the Senate! 🏛️",
      "In 509 BCE, Romans overthrew their king!",
      "Created a REPUBLIC - 'res publica' = 'public thing'!",
      "Citizens elected leaders!",
      "THE GOVERNMENT:",
      "Two CONSULS: Top leaders, elected for 1 year!",
      "SENATE: 300 wealthy men who advised and made laws!",
      "ASSEMBLIES: Regular citizens who voted!",
      "CHECKS AND BALANCES: Sound familiar? U.S. copied this!",
      "This system worked for almost 500 years!",
      "ROMAN SOCIETY: Who's Who? 👥",
      "Society was divided into classes!",
      "PATRICIANS: Rich, powerful families!",
      "Owned most land!",
      "Held government positions!",
      "PLEBEIANS: Common people!",
      "Farmers, craftsmen, merchants!",
      "Most of the population!",
      "Could eventually hold office too!",
      "SLAVES: Prisoners of war or debtors!",
      "Did hard labor!",
      "Some educated slaves became teachers!",
      "Could sometimes buy freedom!",
      "Roman CITIZENSHIP was valuable!",
      "Citizens had rights and protections!",
      "Could vote and serve in army!",
      "JULIUS CAESAR: The Famous General! ⚔️",
      "Born 100 BCE into patrician family!",
      "Brilliant military general!",
      "Conquered GAUL (modern France)!",
      "Wrote 'The Gallic Wars' about his campaigns!",
      "Famous saying: 'Veni, vidi, vici' = 'I came, I saw, I conquered'!",
      "Became too powerful for the Senate!",
      "Crossed the Rubicon River with his army!",
      "(Illegal - meant civil war!)!",
      "Saying 'crossing the Rubicon' = passing point of no return!",
      "Became DICTATOR of Rome!",
      "Made reforms: calendar, citizenship, public works!",
      "ASSASSINATED on March 15, 44 BCE!",
      "Stabbed 23 times by senators!",
      "Famous last words: 'Et tu, Brute?' = 'And you, Brutus?'!",
      "THE ROMAN EMPIRE: Age of Emperors! 👑",
      "After Caesar's death, civil wars erupted!",
      "His adopted son Octavian won!",
      "Became AUGUSTUS - first Roman Emperor!",
      "Ruled 27 BCE - 14 CE!",
      "Brought PAX ROMANA - 'Roman Peace'!",
      "200 years of stability and prosperity!",
      "FAMOUS EMPERORS:",
      "AUGUSTUS: First emperor, brought peace!",
      "NERO: Supposedly 'fiddled while Rome burned'!",
      "Blamed Christians for the great fire!",
      "TRAJAN: Empire reached its largest size!",
      "HADRIAN: Built Hadrian's Wall in Britain!",
      "MARCUS AURELIUS: Philosopher-emperor!",
      "Wrote 'Meditations'!",
      "CONSTANTINE: Made Christianity legal!",
      "Moved capital to Constantinople!",
      "Not all emperors were good - some were crazy or cruel!",
      "THE ROMAN ARMY: Military Machine! ⚔️",
      "The Roman army was UNSTOPPABLE!",
      "ORGANIZATION:",
      "LEGION: About 5,000 soldiers!",
      "CENTURY: 80 soldiers led by a centurion!",
      "Highly trained and disciplined!",
      "ROMAN SOLDIER (LEGIONARY):",
      "Wore metal helmet and armor!",
      "Carried short sword (gladius) and dagger!",
      "Large rectangular shield!",
      "Marched 20 miles a day in full gear!",
      "Built camps every night!",
      "TACTICS:",
      "TESTUDO ('tortoise'): Soldiers formed protective shell with shields!",
      "Roman army conquered most of the known world!",
      "Roads helped them move quickly!",
      "ROMAN ENGINEERING: Master Builders! 🏗️",
      "Romans were AMAZING builders!",
      "ROADS:",
      "Built 50,000 miles of roads!",
      "Saying: 'All roads lead to Rome'!",
      "Allowed army to move fast!",
      "Helped trade!",
      "Many still exist today!",
      "AQUEDUCTS:",
      "Carried water to cities!",
      "Used gravity and arches!",
      "Some were 50+ miles long!",
      "Pont du Gard in France still stands!",
      "THE COLOSSEUM:",
      "Huge arena in Rome!",
      "Held 50,000 spectators!",
      "Gladiators fought here!",
      "Also naval battles (flooded the floor!)!",
      "Still standing today - most iconic Roman building!",
      "OTHER ACHIEVEMENTS:",
      "Invented CONCRETE!",
      "Built domes and arches!",
      "PANTHEON: Dome stood for 2,000 years!",
      "Public baths with hot and cold rooms!",
      "Indoor plumbing and sewers!",
      "ROMAN LAW: Foundation of Justice! ⚖️",
      "Romans created detailed legal system!",
      "TWELVE TABLES: First written laws (450 BCE)!",
      "Posted in forum for all to see!",
      "KEY PRINCIPLES:",
      "Innocent until proven guilty!",
      "Right to defend yourself!",
      "Laws apply equally to all citizens!",
      "Roman law influenced modern legal systems!",
      "U.S. law, European law based on Roman principles!",
      "LATIN: The Language of Rome! 📖",
      "Romans spoke LATIN!",
      "All official documents in Latin!",
      "Used throughout the empire!",
      "LATIN'S LEGACY:",
      "Many English words come from Latin!",
      "Aqua = water (aquarium, aquatic)!",
      "Terra = earth (terrain, territory)!",
      "Video = I see (television, video)!",
      "ROMANCE LANGUAGES evolved from Latin:",
      "Italian, French, Spanish, Portuguese, Romanian!",
      "Scientists still use Latin names!",
      "Legal and medical terms use Latin!",
      "ROMAN RELIGION: Many Gods! 🏛️",
      "Romans worshiped many gods!",
      "Copied most from Greek gods!",
      "Just changed the names!",
      "MAJOR GODS:",
      "JUPITER (Zeus): King of gods!",
      "JUNO (Hera): Queen of gods!",
      "MARS (Ares): God of war - very important to Romans!",
      "VENUS (Aphrodite): Goddess of love!",
      "NEPTUNE (Poseidon): God of sea!",
      "MINERVA (Athena): Goddess of wisdom!",
      "Built temples to honor gods!",
      "Sacrificed animals to please them!",
      "Emperors were declared GODS after death!",
      "CHRISTIANITY:",
      "Started during Roman Empire!",
      "Romans persecuted Christians at first!",
      "CONSTANTINE made it legal in 313 CE!",
      "Christianity became official religion by 380 CE!",
      "Changed Western civilization forever!",
      "GLADIATORS: Fight for Entertainment! ⚔️",
      "Gladiators = professional fighters!",
      "Fought in arenas for crowds!",
      "TYPES OF GLADIATORS:",
      "Wore different armor, used different weapons!",
      "RETIARIUS: Net and trident!",
      "MURMILLO: Sword and large shield!",
      "THRAEX: Curved sword and small shield!",
      "WHO WERE THEY?",
      "Slaves, prisoners, or volunteers!",
      "Could win freedom through victories!",
      "Successful gladiators became celebrities!",
      "FIGHTS:",
      "Fought animals or each other!",
      "Not always to death - good gladiators were expensive!",
      "Crowd decided fate with thumbs up or down!",
      "(Probably not how movies show it!)!",
      "DAILY LIFE IN ROME: 🏠",
      "HOMES:",
      "Rich: Large houses (domus) with courtyards!",
      "Poor: Apartment buildings (insulae) - crowded, dangerous!",
      "FOOD:",
      "Breakfast: Bread, cheese, olives!",
      "Lunch: Light meal!",
      "Dinner (cena): Main meal!",
      "Rich people had elaborate feasts!",
      "Reclined on couches while eating!",
      "ENTERTAINMENT:",
      "CIRCUS MAXIMUS: Chariot racing!",
      "Held 250,000 people!",
      "Fans were passionate - like sports today!",
      "Public baths: Social gathering places!",
      "Theater performances!",
      "CLOTHING:",
      "TOGA: Large draped cloth for citizens!",
      "Complex to wear - showed you didn't do manual labor!",
      "TUNIC: Simple dress-like garment for everyone!",
      "ROMAN EDUCATION: 📚",
      "Only wealthy boys got formal education!",
      "STAGES:",
      "Age 7-11: Basic reading, writing, arithmetic!",
      "Age 12-15: Grammar, literature, Greek!",
      "Age 16+: Rhetoric (public speaking), philosophy, law!",
      "Girls mostly learned at home!",
      "Household skills, sometimes reading!",
      "FAMOUS ROMAN WRITERS:",
      "VIRGIL: Wrote 'The Aeneid' - epic poem!",
      "OVID: Wrote 'Metamorphoses' - myths and legends!",
      "CICERO: Orations and philosophy!",
      "THE FALL OF ROME: Empire's End! 😢",
      "By 200s CE, problems were growing!",
      "CAUSES OF DECLINE:",
      "TOO BIG: Hard to defend borders!",
      "ECONOMIC PROBLEMS: Inflation, heavy taxes!",
      "POLITICAL INSTABILITY: Too many emperors, civil wars!",
      "INVASIONS: Barbarian tribes attacking!",
      "Goths, Vandals, Huns!",
      "MILITARY WEAKNESS: Army not as strong!",
      "DIVISION OF EMPIRE:",
      "Emperor Diocletian split empire in 285 CE!",
      "Western Empire (Rome)!",
      "Eastern Empire (Constantinople)!",
      "Easier to govern!",
      "THE FINAL COLLAPSE:",
      "476 CE: Western Roman Empire fell!",
      "Barbarian leader Odoacer deposed last emperor!",
      "Rome sacked, fell into ruins!",
      "BUT - Eastern Roman Empire (BYZANTINE) lasted until 1453!",
      "Almost 1,000 more years!",
      "ROME'S LEGACY: Still With Us Today! ✨",
      "Roman Empire ended, but influence never did!",
      "ROME GAVE US:",
      "GOVERNMENT: Republic system, senate, checks and balances!",
      "U.S. government modeled on Rome!",
      "LAW: Innocent until proven guilty, written laws!",
      "LANGUAGE: Latin root of many languages!",
      "ARCHITECTURE: Arches, domes, concrete!",
      "Many buildings copy Roman style!",
      "U.S. Capitol looks Roman!",
      "ENGINEERING: Roads, aqueducts, sewers!",
      "CALENDAR: July (Julius Caesar), August (Augustus)!",
      "PHRASES: We still say 'crossing the Rubicon,' 'Veni, vidi, vici'!",
      "ALPHABET: We use the Roman alphabet!",
      "Rome reminds us that even great empires can fall!",
      "But their ideas and achievements live forever! 🏛️👑"
    ],
    questions: [
      {
        question: "What language did Romans speak?",
        options: ["Greek", "Latin", "English", "French"],
        correctAnswer: 1,
        explanation: "Ancient Romans spoke LATIN! Many English words come from Latin. The Romance languages (Italian, French, Spanish) evolved from Latin!"
      },
      {
        question: "What was the name of Rome's famous arena?",
        options: ["Parthenon", "Colosseum", "Stadium", "Forum"],
        correctAnswer: 1,
        explanation: "The COLOSSEUM was Rome's huge arena! It held 50,000 spectators and hosted gladiator fights, animal hunts, and even mock naval battles!"
      },
      {
        question: "Who was a famous Roman leader?",
        options: ["Pharaoh Tutankhamun", "Julius Caesar", "Alexander the Great", "King Arthur"],
        correctAnswer: 1,
        explanation: "JULIUS CAESAR was a famous Roman general and leader! He conquered Gaul, became dictator, and was assassinated on March 15, 44 BCE. 'Et tu, Brute?'!"
      },
      {
        question: "What were the three periods of Roman history?",
        options: ["Old, Middle, New", "Kingdom, Republic, Empire", "Ancient, Classical, Modern", "Bronze, Iron, Steel"],
        correctAnswer: 1,
        explanation: "The three periods were KINGDOM, REPUBLIC, and EMPIRE! Kingdom (753-509 BCE), Republic (509-27 BCE), Empire (27 BCE-476 CE)!"
      },
      {
        question: "What formation did Roman soldiers use for protection?",
        options: ["Phalanx", "Testudo", "Legion", "Century"],
        correctAnswer: 1,
        explanation: "TESTUDO means 'tortoise'! Soldiers formed a protective shell with their shields - protected from arrows and projectiles from all sides!"
      },
      {
        question: "Who was Rome's first emperor?",
        options: ["Julius Caesar", "Nero", "Augustus", "Constantine"],
        correctAnswer: 2,
        explanation: "AUGUSTUS was Rome's first emperor! Born Octavian, he was Julius Caesar's adopted son. Ruled 27 BCE-14 CE and brought Pax Romana - Roman Peace!"
      },
      {
        question: "When did the Western Roman Empire fall?",
        options: ["100 CE", "476 CE", "1000 CE", "1453 CE"],
        correctAnswer: 1,
        explanation: "The Western Roman Empire fell in 476 CE! The last emperor was deposed by barbarian leader Odoacer. The Eastern Empire lasted until 1453!"
      },
      {
        question: "What did Romans invent for building?",
        options: ["Steel", "Concrete", "Plastic", "Glass"],
        correctAnswer: 1,
        explanation: "Romans invented CONCRETE! This allowed them to build amazing structures like the Pantheon's dome, which stood for 2,000 years!"
      }
    ]
  },
  704: {
    id: 704,
    title: 'Ancient China',
    icon: '🐉',
    description: 'Land of inventions and dynasties',
    content: [
      "Welcome to ANCIENT CHINA! 🐉 One of the world's oldest civilizations!",
      "A land of emperors, inventions, and incredible achievements!",
      "Chinese civilization has continued for over 4,000 years!",
      "Let's explore this amazing ancient culture!",
      "ANCIENT CHINA: The Basics! 🗺️",
      "China is in EAST ASIA!",
      "One of the world's OLDEST continuous civilizations!",
      "Started around 2070 BCE!",
      "Developed along two major rivers:",
      "YELLOW RIVER (Huang He) in the north!",
      "YANGTZE RIVER in the south!",
      "Rivers provided water and rich soil!",
      "Mountains and deserts isolated China!",
      "This helped Chinese culture develop uniquely!",
      "DYNASTIES: Ruling Families! 👑",
      "China was ruled by DYNASTIES!",
      "Dynasty = family that rules for generations!",
      "When one dynasty fell, another took over!",
      "MAJOR DYNASTIES:",
      "XIA DYNASTY (2070-1600 BCE): Possibly legendary!",
      "SHANG DYNASTY (1600-1046 BCE): First confirmed dynasty!",
      "ZHOU DYNASTY (1046-256 BCE): Longest dynasty!",
      "QIN DYNASTY (221-206 BCE): United China!",
      "First Emperor Qin Shi Huang!",
      "HAN DYNASTY (206 BCE-220 CE): Golden age!",
      "Expanded empire, Silk Road!",
      "TANG DYNASTY (618-907 CE): Another golden age!",
      "Poetry, art flourished!",
      "Each dynasty left its mark on history!",
      "THE MANDATE OF HEAVEN: Divine Right! ⭐",
      "Chinese emperors ruled by 'MANDATE OF HEAVEN'!",
      "Mandate = permission or approval!",
      "The gods chose the emperor!",
      "If emperor ruled well: Peace, prosperity!",
      "If emperor ruled poorly: Natural disasters, rebellions!",
      "This meant the emperor LOST the mandate!",
      "Another family could take over!",
      "This explained why dynasties changed!",
      "Justified rebellions against bad rulers!",
      "THE FIRST EMPEROR: Qin Shi Huang! 👑",
      "QIN SHI HUANG unified China in 221 BCE!",
      "Before him, China was many separate states!",
      "He conquered them all!",
      "Became first Emperor of unified China!",
      "HIS ACHIEVEMENTS:",
      "STANDARDIZED everything!",
      "One writing system for all of China!",
      "One currency (money)!",
      "One system of weights and measures!",
      "Started building the GREAT WALL!",
      "Connected existing walls!",
      "Built network of roads!",
      "BUT: He was also harsh!",
      "Burned books he didn't like!",
      "Forced people to work on projects!",
      "TERRACOTTA ARMY:",
      "Buried with 8,000 life-size clay soldiers!",
      "Each face is unique!",
      "To protect him in afterlife!",
      "Discovered in 1974 by farmers!",
      "THE GREAT WALL: Longest Wall Ever! 🧱",
      "THE GREAT WALL OF CHINA!",
      "Built to protect from northern invaders!",
      "Especially the Mongols!",
      "FACTS:",
      "Over 13,000 miles long!",
      "That's more than halfway around Earth!",
      "Built over many centuries!",
      "Started in 7th century BCE!",
      "Most famous parts built during Ming Dynasty (1368-1644)!",
      "Made of stone, brick, wood, earth!",
      "30 feet high in places!",
      "Wide enough for horses at top!",
      "Had watchtowers for guards!",
      "MYTH: You can see it from space!",
      "Actually, you can't - it's too narrow!",
      "Took millions of workers to build!",
      "Some died during construction!",
      "CHINESE INVENTIONS: Changed the World! 💡",
      "Ancient China invented SO MANY things!",
      "THE FOUR GREAT INVENTIONS:",
      "1. PAPER (105 CE):",
      "Invented by Cai Lun!",
      "Made from tree bark, hemp, rags!",
      "Replaced expensive bamboo and silk!",
      "Spread to rest of world via Silk Road!",
      "2. PRINTING (868 CE):",
      "WOODBLOCK PRINTING first!",
      "Carved characters into wood blocks!",
      "Inked and pressed onto paper!",
      "Later: MOVABLE TYPE (1040)!",
      "Individual characters could be rearranged!",
      "3. GUNPOWDER (9th century):",
      "Accidentally discovered by alchemists!",
      "Looking for immortality potion!",
      "Used for fireworks first!",
      "Then weapons: bombs, rockets, cannons!",
      "Changed warfare forever!",
      "4. COMPASS (11th century):",
      "Used magnetite (lodestone)!",
      "Helped ships navigate!",
      "Made ocean exploration possible!",
      "OTHER CHINESE INVENTIONS:",
      "Silk production (kept secret for centuries!)!",
      "Porcelain (fine china)!",
      "Tea cultivation and preparation!",
      "Kites (used in military signaling)!",
      "Fireworks and rockets!",
      "Wheelbarrow!",
      "Seismograph (earthquake detector)!",
      "Paper money!",
      "CONFUCIUS: The Great Teacher! 📚",
      "CONFUCIUS (Kong Fuzi) lived 551-479 BCE!",
      "One of China's greatest philosophers!",
      "His ideas shaped Chinese culture for 2,500 years!",
      "CONFUCIANISM: His Teaching!",
      "Not a religion - a philosophy of how to live!",
      "KEY IDEAS:",
      "RESPECT: Honor parents, elders, ancestors!",
      "EDUCATION: Learning makes you better!",
      "RELATIONSHIPS: Treat others with kindness!",
      "DUTY: Everyone has responsibilities!",
      "FIVE KEY RELATIONSHIPS:",
      "Ruler and subject!",
      "Parent and child!",
      "Husband and wife!",
      "Older and younger sibling!",
      "Friend and friend!",
      "FAMOUS SAYINGS:",
      "'Our greatest glory is not in never falling, but in rising every time we fall!'",
      "'Real knowledge is to know the extent of one's ignorance!'",
      "Influenced government, education, family life!",
      "Confucian values still important in China today!",
      "THE SILK ROAD: Highway of Trade! 🐫",
      "The SILK ROAD wasn't one road!",
      "Network of trade routes!",
      "Connected China to Mediterranean!",
      "Over 4,000 miles long!",
      "WHY 'SILK ROAD'?",
      "China's most valuable export: SILK!",
      "Made from silkworm cocoons!",
      "Chinese kept method secret for centuries!",
      "Silk was worth its weight in gold!",
      "WHAT WAS TRADED?",
      "FROM CHINA: Silk, porcelain, tea, spices, paper!",
      "TO CHINA: Gold, silver, wool, glass, horses!",
      "BUT ALSO:",
      "Ideas and inventions traveled!",
      "Religions spread (Buddhism came to China this way)!",
      "Mathematical concepts!",
      "Stories and culture!",
      "DANGERS:",
      "Bandits and robbers!",
      "Harsh deserts and mountains!",
      "Took months or years to travel!",
      "Most valuable trade route in ancient world!",
      "CHINESE WRITING: Characters! ✍️",
      "Chinese writing uses CHARACTERS!",
      "Not an alphabet - each character = word or idea!",
      "ORACLE BONES:",
      "Earliest Chinese writing (1200 BCE)!",
      "Questions carved on animal bones!",
      "Bones heated until they cracked!",
      "Cracks interpreted as answers from gods!",
      "MODERN CHINESE:",
      "Over 50,000 characters exist!",
      "Need about 3,000-4,000 for everyday use!",
      "Same writing system for thousands of years!",
      "Chinese invented writing brush and ink!",
      "CALLIGRAPHY = art of beautiful writing!",
      "Very respected skill!",
      "CHINESE SOCIETY: Order and Hierarchy! 👥",
      "Society had clear structure!",
      "TOP: EMPEROR - Son of Heaven!",
      "LEVEL 2: NOBLES - Landowners, relatives of emperor!",
      "LEVEL 3: SCHOLARS/OFFICIALS - Ran government!",
      "Took difficult exams!",
      "LEVEL 4: FARMERS - Backbone of society!",
      "Produced food!",
      "Respected for feeding everyone!",
      "LEVEL 5: ARTISANS - Craftspeople!",
      "Made goods!",
      "LEVEL 6: MERCHANTS - Lowest class!",
      "Made money from others' work!",
      "Not respected despite wealth!",
      "BOTTOM: SLAVES - Small number!",
      "FAMILY was central to Chinese life!",
      "Multi-generational households!",
      "Respect for elders essential!",
      "Ancestor worship important!",
      "ACHIEVEMENTS IN ART & CULTURE: 🎨",
      "ARCHITECTURE:",
      "Pagodas - multi-tiered towers!",
      "Forbidden City - emperor's palace in Beijing!",
      "Great Wall!",
      "ART:",
      "Landscape paintings - mountains, water, mist!",
      "Ink painting on silk or paper!",
      "Bronze vessels!",
      "Jade carvings (jade was precious)!",
      "POETRY:",
      "Golden age during Tang Dynasty!",
      "Famous poets: Li Bai, Du Fu!",
      "PORCELAIN:",
      "Fine, translucent ceramic!",
      "Called 'china' in English!",
      "Exported worldwide!",
      "CHINESE SCIENCE & TECHNOLOGY: 🔬",
      "Advanced in many fields!",
      "ASTRONOMY:",
      "Detailed star maps!",
      "Tracked comets and eclipses!",
      "Created accurate calendar!",
      "MEDICINE:",
      "Acupuncture - needles at specific points!",
      "Herbal remedies!",
      "Understood blood circulation!",
      "MATHEMATICS:",
      "Used decimal system!",
      "Negative numbers!",
      "Advanced algebra!",
      "ENGINEERING:",
      "Complex irrigation systems!",
      "Suspension bridges!",
      "CHINA'S LEGACY TODAY: ✨",
      "Ancient China's influence is EVERYWHERE!",
      "MODERN CHINA:",
      "World's most populous country!",
      "Many traditions continue!",
      "Confucian values still important!",
      "WHAT CHINA GAVE THE WORLD:",
      "Paper - foundation of written knowledge!",
      "Printing - spread of information!",
      "Gunpowder - changed warfare!",
      "Compass - enabled exploration!",
      "Silk, tea, porcelain!",
      "Fireworks - celebrations worldwide!",
      "Philosophy and wisdom!",
      "CULTURAL IMPACT:",
      "Chinese New Year celebrated globally!",
      "Kung fu and martial arts!",
      "Chinese food worldwide!",
      "Traditional Chinese medicine!",
      "Art and calligraphy!",
      "Ancient China was a powerhouse of innovation!",
      "Its inventions and ideas shaped the entire world! 🐉✨"
    ],
    questions: [
      {
        question: "What did China build to protect from invaders?",
        options: ["Pyramids", "Great Wall of China", "Colosseum", "Parthenon"],
        correctAnswer: 1,
        explanation: "The GREAT WALL OF CHINA was built to protect from northern invaders! Over 13,000 miles long - more than halfway around Earth!"
      },
      {
        question: "Which did ancient China NOT invent?",
        options: ["Paper", "Gunpowder", "The wheel", "The compass"],
        correctAnswer: 2,
        explanation: "Ancient China invented PAPER, GUNPOWDER, and the COMPASS (the Four Great Inventions plus printing), but the wheel was invented earlier in Mesopotamia!"
      },
      {
        question: "What were Chinese ruling families called?",
        options: ["Pharaohs", "Dynasties", "Republics", "Kingdoms"],
        correctAnswer: 1,
        explanation: "Chinese ruling families were called DYNASTIES! Famous dynasties include Qin, Han, and Tang. Each dynasty ruled until it lost the Mandate of Heaven!"
      },
      {
        question: "Who was China's great philosopher and teacher?",
        options: ["Buddha", "Confucius", "Lao Tzu", "Sun Tzu"],
        correctAnswer: 1,
        explanation: "CONFUCIUS (551-479 BCE) was China's greatest philosopher! His teachings about respect, education, and relationships shaped Chinese culture for 2,500 years!"
      },
      {
        question: "What was China's most valuable export on the Silk Road?",
        options: ["Gold", "Spices", "Silk", "Tea"],
        correctAnswer: 2,
        explanation: "SILK was China's most valuable export! Made from silkworm cocoons, the method was kept secret for centuries. That's why the trade route was called the Silk Road!"
      },
      {
        question: "Who was the first emperor to unify China?",
        options: ["Confucius", "Qin Shi Huang", "Genghis Khan", "Sun Tzu"],
        correctAnswer: 1,
        explanation: "QIN SHI HUANG unified China in 221 BCE! He standardized writing, currency, and measurements. He was buried with the famous Terracotta Army!"
      },
      {
        question: "What did Chinese emperors have permission from?",
        options: ["The Senate", "The people", "Mandate of Heaven", "Foreign kings"],
        correctAnswer: 2,
        explanation: "Chinese emperors ruled by the MANDATE OF HEAVEN! If they ruled well, they kept it. Natural disasters or rebellions meant they'd lost the mandate!"
      },
      {
        question: "What are the Four Great Inventions of China?",
        options: ["Silk, tea, rice, jade", "Paper, printing, gunpowder, compass", "Wall, army, emperor, dynasty", "Dragon, phoenix, tiger, turtle"],
        correctAnswer: 1,
        explanation: "The Four Great Inventions are PAPER, PRINTING, GUNPOWDER, and the COMPASS! These inventions changed the entire world and spread via the Silk Road!"
      }
    ]
  },
  705: {
    id: 705,
    title: 'Ancient Maya',
    icon: '🌽',
    description: 'Mysterious pyramid builders of Central America',
    content: [
      "Welcome to the ANCIENT MAYA! 🌽 Masters of mathematics and astronomy!",
      "Deep in the jungles of Central America, an amazing civilization thrived!",
      "The Maya built towering pyramids, created accurate calendars, and developed advanced mathematics!",
      "Let's explore this mysterious ancient world!",
      "THE MAYA: Who Were They? 🗺️",
      "The Maya lived in MESOAMERICA!",
      "Mesoamerica = Middle America!",
      "Includes parts of modern-day Mexico, Guatemala, Belize, Honduras, El Salvador!",
      "NOT just one empire - many city-states!",
      "Each city-state had its own ruler!",
      "Sometimes traded, sometimes fought!",
      "TIMELINE:",
      "PRECLASSIC (2000 BCE-250 CE): Cities begin!",
      "CLASSIC PERIOD (250-900 CE): Golden age!",
      "Height of Maya power!",
      "POSTCLASSIC (900-1500s CE): Decline and Spanish arrival!",
      "Maya civilization lasted over 3,000 years!",
      "FAMOUS MAYA CITIES: 🏛️",
      "TIKAL: Powerful city with massive pyramids!",
      "In Guatemala!",
      "Pyramid over 200 feet tall!",
      "CHICHÉN ITZÁ: Famous for El Castillo pyramid!",
      "In Mexico's Yucatan!",
      "Tourist destination today!",
      "PALENQUE: Beautiful city with intricate carvings!",
      "COPÁN: Known for hieroglyphic stairway!",
      "Each city was independent - like Greek city-states!",
      "MAYA PYRAMIDS: Temples to the Gods! 🔺",
      "Maya built HUGE stepped pyramids!",
      "Not tombs like Egyptian pyramids!",
      "TEMPLES for worshiping gods!",
      "EL CASTILLO at Chichén Itzá:",
      "Also called Temple of Kukulkan!",
      "79 feet tall!",
      "365 steps - one for each day of year!",
      "AMAZING: During equinoxes, shadows look like serpent crawling down!",
      "Built with precise astronomical calculations!",
      "PYRAMID CONSTRUCTION:",
      "Made of limestone blocks!",
      "No metal tools - used stone tools!",
      "No wheels or pack animals!",
      "Everything carried by hand!",
      "Painted bright colors - red, blue, yellow!",
      "(Now weathered to gray stone)",
      "Temples on top for ceremonies!",
      "Kings performed rituals!",
      "MAYA WRITING: Hieroglyphs! 📜",
      "Maya developed most advanced writing in Americas!",
      "Used HIEROGLYPHS - pictures and symbols!",
      "Over 800 different glyphs!",
      "WHAT THEY WROTE ON:",
      "Stone monuments called STELAE!",
      "Recorded kings' achievements!",
      "Buildings and pyramids!",
      "CODICES - folded bark paper books!",
      "Only 4 original codices survive!",
      "Spanish destroyed most!",
      "WHAT THEY WROTE ABOUT:",
      "History of kings!",
      "Religious ceremonies!",
      "Astronomical observations!",
      "Calendar dates!",
      "DECODING MAYA WRITING:",
      "Lost for centuries after Spanish conquest!",
      "Scholars worked to decode it!",
      "Major breakthrough in 1950s!",
      "Now we can read most glyphs!",
      "MAYA CALENDAR: Time Keepers! 📅",
      "Maya were OBSESSED with time!",
      "Created multiple calendars!",
      "THE LONG COUNT:",
      "Tracked days from Maya creation date!",
      "August 11, 3114 BCE (in our calendar)!",
      "THE TZOLK'IN:",
      "260-day sacred calendar!",
      "Used for religious ceremonies!",
      "Named days and predicted fate!",
      "THE HAAB:",
      "365-day solar calendar!",
      "18 months of 20 days!",
      "Plus 5 unlucky days at end!",
      "CALENDAR ROUND:",
      "Combined Tzolk'in and Haab!",
      "52-year cycle!",
      "WHY SO ACCURATE?",
      "Maya were expert astronomers!",
      "Tracked sun, moon, Venus, stars!",
      "Predicted eclipses!",
      "More accurate than European calendars of the time!",
      "2012 'END OF WORLD':",
      "Long Count completed a cycle in 2012!",
      "Media panicked!",
      "But Maya saw it like odometer rolling over!",
      "New cycle begins - not end of world!",
      "MAYA MATHEMATICS: Number Masters! 🔢",
      "Maya had advanced math system!",
      "Used BASE 20 (we use base 10)!",
      "SYMBOLS:",
      "DOT = 1!",
      "BAR = 5!",
      "SHELL = 0!",
      "YES - Maya invented ZERO!",
      "Independently! (Like India)!",
      "One of only a few civilizations to do so!",
      "Crucial for math and calendar calculations!",
      "PLACE VALUE SYSTEM:",
      "Like ours but vertical!",
      "Bottom = ones!",
      "Next = twenties!",
      "Next = 400s!",
      "Could calculate huge numbers!",
      "Needed for astronomy!",
      "MAYA RELIGION: Gods Everywhere! 🌟",
      "Maya were polytheistic - many gods!",
      "Over 250 gods!",
      "Gods controlled everything!",
      "MAJOR GODS:",
      "ITZAMNÁ: Creator god, lord of heaven!",
      "KUKULKAN: Feathered serpent god!",
      "Most important!",
      "CHAAC: Rain god!",
      "Super important - farming depended on rain!",
      "IX CHEL: Moon goddess!",
      "K'INICH AJAW: Sun god!",
      "AH PUCH: Death god!",
      "Lord of the underworld (Xibalba)!",
      "HUMAN SACRIFICE:",
      "Yes, Maya practiced human sacrifice!",
      "Believed gods needed blood!",
      "Usually prisoners from war!",
      "Sometimes nobles volunteered!",
      "BLOODLETTING:",
      "Kings pierced themselves with thorns or stingray spines!",
      "Offered blood to gods!",
      "Part of religious duty!",
      "THE BALL GAME: Sacred Sport! ⚽",
      "PITZ (or pok-a-tok) was ritual ball game!",
      "Played on I-shaped court!",
      "RULES:",
      "Heavy rubber ball (3-8 pounds)!",
      "Can't use hands or feet!",
      "Use hips, elbows, knees!",
      "Try to get ball through stone ring high on wall!",
      "Super hard!",
      "RELIGIOUS MEANING:",
      "Game represented battle between light and dark!",
      "Life and death!",
      "Winners (or losers - sources disagree) sacrificed!",
      "Great honor!",
      "Ball courts found at every major city!",
      "MAYA ACHIEVEMENTS: 🎨",
      "ASTRONOMY:",
      "Tracked Venus with incredible accuracy!",
      "Built observatories!",
      "Understood eclipses!",
      "ARCHITECTURE:",
      "Pyramids without metal tools!",
      "Corbel arches (false arches)!",
      "Aligned buildings to stars!",
      "ART:",
      "Detailed stone carvings!",
      "Colorful murals!",
      "Jade masks and jewelry!",
      "AGRICULTURE:",
      "Cleared jungle for farming!",
      "Slash-and-burn technique!",
      "Terraced hillsides!",
      "Chinampas (floating gardens)!",
      "Grew CORN (maize) - staple food!",
      "Also beans, squash, cacao!",
      "MAYA SOCIETY: Kings and Commoners! 👑",
      "Hierarchical society!",
      "TOP: K'UHUL AJAW - Divine King!",
      "Intermediary between gods and people!",
      "Absolute power!",
      "LEVEL 2: NOBLES - Priests, warriors, officials!",
      "Ran government and religion!",
      "LEVEL 3: ARTISANS - Skilled craftspeople!",
      "Made pottery, jewelry, carvings!",
      "LEVEL 4: FARMERS - Most people!",
      "Grew food for everyone!",
      "Paid tribute to nobles!",
      "BOTTOM: SLAVES - War captives!",
      "Society revolved around king!",
      "DAILY LIFE IN MAYA CITIES: 🏠",
      "HOMES:",
      "Common people: Simple huts!",
      "Pole frame, thatched roof!",
      "One or two rooms!",
      "Nobles: Stone houses around courtyards!",
      "FOOD:",
      "CORN everything!",
      "Tortillas, tamales, pozole!",
      "Beans, squash, chili peppers!",
      "Turkey, deer, fish!",
      "CHOCOLATE:",
      "Yes! Maya discovered chocolate!",
      "Made drink from cacao beans!",
      "Frothy, bitter, spicy!",
      "For nobles and ceremonies!",
      "CLOTHING:",
      "Men: Loincloth, sometimes capes!",
      "Women: Long dresses!",
      "Nobles: Elaborate headdresses, jewelry, jaguar pelts!",
      "BEAUTY:",
      "Flattened heads as babies (sign of beauty)!",
      "Filed teeth, added jade!",
      "Cross-eyed considered attractive!",
      "Tattoos and body paint!",
      "THE MAYA COLLAPSE: Mystery! 😱",
      "Around 900 CE, Classic Maya civilization collapsed!",
      "Cities abandoned!",
      "Jungle reclaimed them!",
      "WHY? Still debated!",
      "POSSIBLE CAUSES:",
      "DROUGHT: Long dry period!",
      "Crops failed!",
      "OVERPOPULATION: Too many people!",
      "Exhausted resources!",
      "WARFARE: Constant fighting between cities!",
      "ENVIRONMENTAL DAMAGE: Deforestation!",
      "POLITICAL COLLAPSE: People lost faith in kings!",
      "Probably COMBINATION of factors!",
      "Not all Maya disappeared!",
      "Southern cities survived!",
      "NEW cities rose in north (Yucatan)!",
      "But Classic period ended!",
      "SPANISH CONQUEST: 😢",
      "1500s: Spanish conquistadors arrived!",
      "Brought diseases Maya had no immunity to!",
      "Smallpox killed millions!",
      "Spanish destroyed cities and books!",
      "Forced conversion to Christianity!",
      "Last independent Maya city fell in 1697!",
      "THE MAYA TODAY: Still Here! ✨",
      "MAYA DIDN'T DISAPPEAR!",
      "Over 7 MILLION Maya people live today!",
      "In Mexico, Guatemala, Belize, Honduras!",
      "Speak Maya languages!",
      "Over 30 different Maya languages!",
      "Keep traditional customs!",
      "MAYA LEGACY:",
      "Ancient cities are tourist destinations!",
      "Chichén Itzá is one of New Seven Wonders!",
      "Writing system decoded - we can read their history!",
      "Chocolate given to world!",
      "Advanced math and astronomy!",
      "Concept of zero!",
      "Accurate calendars!",
      "Beautiful art and architecture!",
      "The Maya civilization was one of the most advanced in ancient Americas! 🌽🔺"
    ],
    questions: [
      {
        question: "Where did the Maya civilization develop?",
        options: ["Egypt", "China", "Central America", "India"],
        correctAnswer: 2,
        explanation: "The Maya civilization developed in CENTRAL AMERICA (Mesoamerica)! Parts of modern Mexico, Guatemala, Belize, Honduras, and El Salvador!"
      },
      {
        question: "What were Maya pyramids used for?",
        options: ["Tombs", "Temples for worship", "Homes", "Storage"],
        correctAnswer: 1,
        explanation: "Maya pyramids were TEMPLES for worshiping gods! Kings performed ceremonies on top. They weren't tombs like Egyptian pyramids!"
      },
      {
        question: "What important mathematical concept did Maya invent?",
        options: ["Negative numbers", "Zero", "Pi", "Fractions"],
        correctAnswer: 1,
        explanation: "The Maya invented ZERO! One of only a few civilizations to do so independently. Essential for their advanced calendar calculations!"
      },
      {
        question: "What was the Maya sacred ball game called?",
        options: ["Soccer", "Pitz", "Basketball", "Tennis"],
        correctAnswer: 1,
        explanation: "The sacred ball game was called PITZ (or pok-a-tok)! Players used hips and elbows to hit heavy rubber ball through stone ring. It had religious meaning!"
      },
      {
        question: "What crop was most important to Maya?",
        options: ["Wheat", "Rice", "Corn (maize)", "Potatoes"],
        correctAnswer: 2,
        explanation: "CORN (maize) was the Maya staple food! They made tortillas, tamales, and pozole. Corn was central to their diet and culture!"
      },
      {
        question: "How many days in the Maya Haab calendar?",
        options: ["260", "365", "400", "100"],
        correctAnswer: 1,
        explanation: "The Haab was a 365-day solar calendar! It had 18 months of 20 days plus 5 unlucky days. The Maya also had a 260-day sacred calendar!"
      },
      {
        question: "What did Maya discover that we still enjoy?",
        options: ["Pizza", "Chocolate", "Ice cream", "Cheese"],
        correctAnswer: 1,
        explanation: "The Maya discovered CHOCOLATE! They made frothy, bitter drink from cacao beans. It was for nobles and ceremonies. They gave chocolate to the world!"
      },
      {
        question: "Are there still Maya people today?",
        options: ["No, they all disappeared", "Yes, over 7 million!", "Only a few hundred", "Only in museums"],
        correctAnswer: 1,
        explanation: "YES! Over 7 MILLION Maya people live today! In Mexico, Guatemala, Belize, and Honduras. They speak Maya languages and keep traditional customs!"
      }
    ]
  },
  // World Geography (801-805)
  801: {
    id: 801,
    title: 'Maps & Globes',
    icon: '🗺️',
    description: 'Tools for understanding Earth',
    content: [
      "Welcome to MAPS & GLOBES! 🗺️ Let's learn to read our world!",
      "Maps and globes are tools that help us see where things are!",
      "They're like magic windows showing our entire planet!",
      "Let's explore these amazing tools!",
      "WHAT IS A GLOBE? 🌍",
      "A GLOBE is a round, 3D model of Earth!",
      "It's a SPHERE - shaped like a ball!",
      "Shows Earth exactly as it looks from space!",
      "Most ACCURATE way to show our planet!",
      "WHY GLOBE IS ACCURATE:",
      "Earth is round, globe is round!",
      "Shows true distances and directions!",
      "Shows continents and oceans in correct sizes!",
      "You can spin it like real Earth!",
      "WHAT'S ON A GLOBE:",
      "CONTINENTS - big landmasses!",
      "OCEANS - huge bodies of water!",
      "COUNTRIES - different colors!",
      "Lines for latitude and longitude!",
      "WHAT IS A MAP? 🗺️",
      "A MAP is a flat picture of Earth or part of Earth!",
      "Problem: Earth is round, paper is flat!",
      "It's like trying to flatten an orange peel!",
      "So maps DISTORT (change) shapes or sizes a bit!",
      "But maps are SUPER useful!",
      "Easy to carry!",
      "Can fold in pocket!",
      "Can show just the part you need!",
      "Can focus on specific information!",
      "PARTS OF A MAP: 📋",
      "Good maps have several important parts!",
      "1. TITLE:",
      "Tells what the map shows!",
      "'Map of United States' or 'Downtown Boston'!",
      "2. COMPASS ROSE:",
      "Shows DIRECTIONS!",
      "N = North (top usually)!",
      "S = South (bottom)!",
      "E = East (right)!",
      "W = West (left)!",
      "Sometimes shows NE, NW, SE, SW too!",
      "(Northeast, Northwest, Southeast, Southwest)!",
      "3. KEY or LEGEND:",
      "Explains SYMBOLS on map!",
      "★ = Capital city!",
      "● = Other cities!",
      "✈ = Airport!",
      "⛰️ = Mountains!",
      "Different colors mean different things!",
      "Blue = Water!",
      "Green = Low land or forests!",
      "Brown = High land or deserts!",
      "4. SCALE:",
      "Shows how distances on map compare to real distances!",
      "Example: '1 inch = 100 miles'!",
      "Helps you measure real distances!",
      "CARDINAL DIRECTIONS: The Main Four! 🧭",
      "NORTH, SOUTH, EAST, WEST!",
      "These are CARDINAL directions!",
      "Tricks to remember:",
      "Never Eat Soggy Waffles!",
      "(N, E, S, W going clockwise)!",
      "North is usually at TOP of map!",
      "South is at BOTTOM!",
      "East is to the RIGHT!",
      "West is to the LEFT!",
      "THE EQUATOR: Earth's Belt! 🌍",
      "The EQUATOR is imaginary line around Earth's middle!",
      "Splits Earth into two halves!",
      "NORTHERN HEMISPHERE (top half)!",
      "SOUTHERN HEMISPHERE (bottom half)!",
      "It's at 0° latitude!",
      "Places near equator are HOT!",
      "Gets most direct sunlight!",
      "Countries on equator: Ecuador, Kenya, Indonesia!",
      "THE POLES: Earth's Top and Bottom! ❄️",
      "NORTH POLE: Earth's northernmost point!",
      "At top of globe!",
      "In Arctic Ocean!",
      "Covered in ice!",
      "Santa's home (in stories!)!",
      "SOUTH POLE: Earth's southernmost point!",
      "At bottom of globe!",
      "In Antarctica continent!",
      "Also covered in ice!",
      "Coldest place on Earth!",
      "Poles are FREEZING cold!",
      "Farthest from equator's heat!",
      "LATITUDE: Horizontal Lines! ↔️",
      "Lines that go ACROSS (left to right)!",
      "Also called PARALLELS!",
      "Measure north or south of equator!",
      "Measured in DEGREES (°)!",
      "Equator = 0°!",
      "North Pole = 90°N!",
      "South Pole = 90°S!",
      "LONGITUDE: Vertical Lines! ↕️",
      "Lines that go UP AND DOWN!",
      "Also called MERIDIANS!",
      "Measure east or west!",
      "PRIME MERIDIAN = 0°!",
      "Runs through Greenwich, England!",
      "Splits Earth into:",
      "EASTERN HEMISPHERE (right side)!",
      "WESTERN HEMISPHERE (left side)!",
      "Goes up to 180° east or west!",
      "COORDINATES: Finding Exact Locations! 📍",
      "Latitude + Longitude = EXACT location!",
      "Like an address for any spot on Earth!",
      "Example: New York City is about 41°N, 74°W!",
      "First number (41°N) = latitude!",
      "Second number (74°W) = longitude!",
      "TYPES OF MAPS: 🗺️",
      "Different maps show different information!",
      "1. PHYSICAL MAP:",
      "Shows NATURAL features!",
      "Mountains, rivers, deserts, forests!",
      "Uses colors for elevation:",
      "Brown = High mountains!",
      "Green = Low plains!",
      "Blue = Water!",
      "2. POLITICAL MAP:",
      "Shows COUNTRIES and BORDERS!",
      "Shows cities, especially capitals!",
      "Different colors for different countries!",
      "No mountains or rivers (usually)!",
      "3. ROAD MAP:",
      "Shows roads and highways!",
      "Helps you drive places!",
      "Shows cities, towns, exits!",
      "4. CLIMATE MAP:",
      "Shows weather patterns!",
      "Hot, cold, wet, dry areas!",
      "5. TOPOGRAPHIC MAP:",
      "Shows elevation in detail!",
      "Uses contour lines!",
      "For hikers and explorers!",
      "HEMISPHERES: Earth's Halves! 🌍",
      "Hemisphere = half of Earth!",
      "Earth can be divided different ways:",
      "NORTHERN and SOUTHERN:",
      "Split by equator!",
      "EASTERN and WESTERN:",
      "Split by Prime Meridian!",
      "Most places are in TWO hemispheres!",
      "USA is in Northern and Western!",
      "Australia is in Southern and Eastern!",
      "CONTINENTS ON A GLOBE: 🌎",
      "Seven continents:",
      "1. ASIA - Biggest!",
      "2. AFRICA - Second biggest!",
      "3. NORTH AMERICA - Where USA is!",
      "4. SOUTH AMERICA - Has Amazon!",
      "5. ANTARCTICA - All ice!",
      "6. EUROPE - Lots of countries!",
      "7. AUSTRALIA/OCEANIA - Smallest!",
      "OCEANS ON A GLOBE: 🌊",
      "Five oceans:",
      "1. PACIFIC - Biggest ocean!",
      "2. ATLANTIC - Between Americas and Europe/Africa!",
      "3. INDIAN - Below Asia!",
      "4. ARCTIC - Around North Pole!",
      "5. SOUTHERN - Around Antarctica!",
      "Oceans cover 70% of Earth!",
      "READING A MAP: Step by Step! 📖",
      "How to use a map effectively:",
      "STEP 1: Read the TITLE!",
      "Know what you're looking at!",
      "STEP 2: Find the COMPASS ROSE!",
      "Know which way is north!",
      "STEP 3: Check the KEY/LEGEND!",
      "Understand what symbols mean!",
      "STEP 4: Look at the SCALE!",
      "Know how far things really are!",
      "STEP 5: Find what you need!",
      "Use the information!",
      "MAP DISTORTIONS: The Flat Earth Problem! 🗺️",
      "Remember: Earth is round, maps are flat!",
      "This causes problems!",
      "MERCATOR PROJECTION:",
      "Most common map type!",
      "But makes things near poles look HUGE!",
      "Greenland looks as big as Africa!",
      "Actually, Africa is 14 times bigger!",
      "Countries near equator shown more accurately!",
      "Good for navigation!",
      "GLOBE is always most accurate!",
      "MODERN MAPPING: 📱",
      "Today we have digital maps!",
      "GPS (Global Positioning System)!",
      "Uses satellites in space!",
      "Tells your exact location!",
      "Google Maps, Apple Maps!",
      "Can see real-time traffic!",
      "Street view shows photos!",
      "But it all started with paper maps and globes!",
      "WHY MAPS AND GLOBES MATTER: ✨",
      "Help us find places!",
      "Understand geography!",
      "Plan trips!",
      "See where countries are!",
      "Learn about our world!",
      "Navigate and explore!",
      "Maps and globes are windows to our whole world! 🗺️🌍"
    ],
    questions: [
      {
        question: "What is a globe?",
        options: ["A flat map", "A round model of Earth", "A type of ocean", "A country"],
        correctAnswer: 1,
        explanation: "A globe is a round, 3D model of Earth! It's shaped like a sphere and shows Earth exactly as it looks from space - the most accurate way!"
      },
      {
        question: "What is the imaginary line around Earth's middle called?",
        options: ["Prime Meridian", "Equator", "Tropic", "Border"],
        correctAnswer: 1,
        explanation: "The EQUATOR is the imaginary line around Earth's middle! It's at 0° latitude and divides Earth into Northern and Southern Hemispheres!"
      },
      {
        question: "What shows directions on a map?",
        options: ["Key", "Scale", "Compass rose", "Title"],
        correctAnswer: 2,
        explanation: "The COMPASS ROSE shows directions on a map! It shows North, South, East, and West. Remember: Never Eat Soggy Waffles!"
      },
      {
        question: "What are the four cardinal directions?",
        options: ["Up, Down, Left, Right", "North, South, East, West", "Forward, Back, Left, Right", "Top, Bottom, Side, Side"],
        correctAnswer: 1,
        explanation: "The four cardinal directions are NORTH, SOUTH, EAST, and WEST! These are the main directions we use on maps and compasses!"
      },
      {
        question: "What does a map's KEY or LEGEND do?",
        options: ["Shows directions", "Explains symbols", "Shows the title", "Measures distance"],
        correctAnswer: 1,
        explanation: "The KEY or LEGEND explains what symbols mean on a map! It tells you what colors and symbols represent (cities, mountains, water, etc.)!"
      },
      {
        question: "Which lines on Earth go up and down?",
        options: ["Latitude", "Longitude", "Equator", "Borders"],
        correctAnswer: 1,
        explanation: "LONGITUDE lines go up and down (vertical)! Also called meridians. The Prime Meridian at 0° runs through Greenwich, England!"
      },
      {
        question: "What type of map shows countries and borders?",
        options: ["Physical map", "Road map", "Political map", "Climate map"],
        correctAnswer: 2,
        explanation: "A POLITICAL MAP shows countries, borders, and cities! It uses different colors for different countries and marks capital cities!"
      },
      {
        question: "What covers about 70% of Earth?",
        options: ["Land", "Ice", "Oceans", "Deserts"],
        correctAnswer: 2,
        explanation: "OCEANS cover about 70% of Earth! The five oceans are Pacific, Atlantic, Indian, Arctic, and Southern. Earth is mostly water!"
      }
    ]
  },

};
