interface Question {
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

interface TopicLesson {
  id: number;
  title: string;
  icon: string;
  description: string;
  content: string[];
  questions: Question[];
}

export const lessons: { [key: number]: TopicLesson } = {
  302: {
    id: 302,
    title: 'Plant Life Cycles',
    icon: '🌱',
    description: 'How plants grow and reproduce',
    content: [
      "Get ready to watch magic happen! 🌱 Let's follow a plant's life from start to finish!",
      "Every plant has a LIFE CYCLE - the journey from seed to adult plant to new seeds!",
      "STAGE 1: THE SEED! 🌰",
      "Our story starts with a tiny seed!",
      "Seeds look small, but they're packed with everything needed to make a new plant!",
      "Inside every seed is a BABY PLANT (called an embryo) and FOOD to help it start growing!",
      "Seeds have a tough coat (like a jacket) to protect the baby plant inside!",
      "Seeds can wait for the right time to grow - sometimes for years!",
      "They're waiting for the perfect conditions: water, warmth, and oxygen!",
      "Seeds come in amazing variety: tiny like dust, big like coconuts!",
      "Dandelion seeds float on the wind! Maple seeds spin like helicopters!",
      "STAGE 2: GERMINATION! 🌱",
      "When a seed gets water and warmth, something amazing happens!",
      "The seed wakes up and starts to grow - this is GERMINATION!",
      "The seed coat cracks open!",
      "First, a tiny ROOT pushes out and grows DOWN into the soil!",
      "The root searches for water and anchors the plant!",
      "Then a SHOOT pushes up through the soil toward the light!",
      "The shoot will become the stem and leaves!",
      "The baby plant uses the food stored in the seed to power this first growth!",
      "Germination usually takes a few days to a few weeks!",
      "You can watch this happen if you plant a bean seed in a clear cup!",
      "STAGE 3: SEEDLING GROWTH! 🌿",
      "Once the shoot breaks through the soil, it's called a SEEDLING!",
      "The first leaves appear - hello, sunlight!",
      "Now the plant can make its own food through PHOTOSYNTHESIS!",
      "What's photosynthesis? Plants use sunlight, water, and air to make sugar (food)!",
      "The green chemical in leaves (chlorophyll) captures sunlight!",
      "The roots grow deeper and branch out, searching for water and nutrients!",
      "The stem grows taller, lifting leaves toward the sun!",
      "Plants need three main things: SUNLIGHT, WATER, and good SOIL!",
      "The seedling grows new leaves and gets stronger every day!",
      "This is a delicate time - seedlings need protection from harsh weather!",
      "STAGE 4: MATURE PLANT! 🌳",
      "As weeks and months pass, the plant grows bigger and stronger!",
      "It develops more leaves to catch more sunlight!",
      "Some plants grow tall stems, some spread out, some grow thick trunks!",
      "The roots become a huge underground network - bigger than you can see!",
      "When the plant is fully grown, we call it a MATURE PLANT or ADULT PLANT!",
      "Now it's strong enough to make new plants!",
      "Different plants take different times to mature:",
      "Some plants mature in weeks (like lettuce)!",
      "Some take years (like apple trees)!",
      "Some trees take decades to fully mature!",
      "STAGE 5: FLOWERING AND POLLINATION! 🌸",
      "When ready to reproduce, many plants grow FLOWERS!",
      "Flowers are the plant's way of making new seeds!",
      "Flowers have special parts: PETALS (colorful), STAMENS (make pollen), and PISTIL (makes seeds)!",
      "Pollen (yellow dust) needs to move from one flower to another - this is POLLINATION!",
      "How does pollen travel? Amazing helpers!",
      "BEES and BUTTERFLIES visit flowers for sweet nectar and carry pollen on their bodies!",
      "WIND blows pollen through the air!",
      "HUMMINGBIRDS drink nectar and pollinate flowers!",
      "Even BATS pollinate some flowers at night!",
      "This is why bees are SO important - without them, many plants can't make seeds!",
      "Flowers are colorful and smell nice to attract pollinators!",
      "STAGE 6: FRUITS AND SEED DISPERSAL! 🍎",
      "After pollination, flowers turn into FRUITS!",
      "The fruit protects the new seeds growing inside!",
      "Apples, oranges, berries - all fruits with seeds inside!",
      "Even vegetables like tomatoes and cucumbers are fruits (they have seeds)!",
      "When fruits ripen, the seeds are ready!",
      "Now the seeds need to travel away from the parent plant - this is DISPERSAL!",
      "How do seeds travel?",
      "Some fruits are eaten by animals, and seeds come out in poop far away!",
      "Some seeds have wings or parachutes (dandelions) and float on wind!",
      "Some seeds stick to animal fur with hooks (like burs)!",
      "Some seeds fall into water and float to new places!",
      "Some seed pods explode and shoot seeds out!",
      "STAGE 7: THE CYCLE CONTINUES! 🔄",
      "The seeds land in new places and wait for the right conditions!",
      "When they get water and warmth, they germinate!",
      "And the whole cycle starts over again!",
      "One plant can make hundreds or thousands of seeds!",
      "This is how plants spread and forests grow!",
      "SPECIAL TYPES OF LIFE CYCLES:",
      "ANNUAL PLANTS: Complete their life cycle in one year, then die (like tomatoes)!",
      "PERENNIAL PLANTS: Live for many years, flowering each year (like apple trees)!",
      "WHY PLANT LIFE CYCLES MATTER:",
      "They give us food - fruits, vegetables, grains!",
      "They give animals food and homes!",
      "They make oxygen for us to breathe!",
      "They keep our planet healthy!",
      "Remember: Seed → Germination → Seedling → Mature Plant → Flowers → Fruits & Seeds → New Seeds!",
      "The circle of life for plants! 🌍🌱"
    ],
    questions: [
      {
        question: "What is inside a seed?",
        options: ["A baby plant", "Water", "Soil", "Rocks"],
        correctAnswer: 0,
        explanation: "Seeds contain a tiny baby plant (embryo) and food to help it start growing!"
      },
      {
        question: "What is germination?",
        options: ["When plants die", "When seeds start to grow", "When flowers bloom", "When leaves fall"],
        correctAnswer: 1,
        explanation: "Germination is when a seed 'wakes up' and starts to grow - the root and shoot emerge!"
      },
      {
        question: "What do bees help plants do?",
        options: ["Drink water", "Pollination", "Make oxygen", "Grow taller"],
        correctAnswer: 1,
        explanation: "Bees help with pollination - moving pollen between flowers so plants can make seeds! They're plant superheroes!"
      },
      {
        question: "What grows first when a seed germinates?",
        options: ["Flower", "Leaves", "Root", "Fruit"],
        correctAnswer: 2,
        explanation: "The ROOT grows first! It pushes down into the soil to anchor the plant and find water!"
      },
      {
        question: "What do plants make using sunlight, water, and air?",
        options: ["Seeds", "Flowers", "Food (sugar)", "Roots"],
        correctAnswer: 2,
        explanation: "Plants make food (sugar) through photosynthesis! They use sunlight, water, and carbon dioxide from air!"
      },
      {
        question: "What is pollination?",
        options: ["When plants drink water", "When pollen moves between flowers", "When seeds fall", "When roots grow"],
        correctAnswer: 1,
        explanation: "Pollination is when pollen moves from one flower to another, allowing plants to make seeds!"
      },
      {
        question: "How do dandelion seeds travel?",
        options: ["They walk", "They float on the wind", "Animals carry them", "They swim"],
        correctAnswer: 1,
        explanation: "Dandelion seeds have fluffy parachutes that let them float on the wind to new places!"
      },
      {
        question: "What do we call plants that live for many years?",
        options: ["Annual", "Perennial", "Seasonal", "Temporary"],
        correctAnswer: 1,
        explanation: "PERENNIAL plants live for many years! Annual plants complete their life cycle in one year!"
      }
    ]
  },
  303: {
    id: 303,
    title: 'Food Chains & Webs',
    icon: '🍃',
    description: 'How energy moves through nature',
    content: [
      "Time to learn about nature's dining system! 🍃 Who eats whom?",
      "In nature, energy moves from one living thing to another through eating!",
      "This pathway is called a FOOD CHAIN!",
      "EVERY food chain starts the same way - with the SUN! ☀️",
      "The sun is the ultimate source of energy for ALL life on Earth!",
      "Without the sun, there would be no food chains!",
      "LEVEL 1: PRODUCERS! 🌱",
      "Plants are called PRODUCERS because they PRODUCE (make) their own food!",
      "Through photosynthesis, plants use sunlight, water, and air to make sugar!",
      "This sugar is ENERGY that powers the plant!",
      "Plants don't need to eat other things - they make their own food!",
      "Examples of producers: grass, trees, algae, flowers, crops!",
      "Producers are the BASE of every food chain!",
      "LEVEL 2: PRIMARY CONSUMERS (HERBIVORES)! 🐇",
      "Animals that eat ONLY PLANTS are called HERBIVORES!",
      "They're also called PRIMARY CONSUMERS - they're the first to 'consume' (eat) in the chain!",
      "When a herbivore eats a plant, energy moves from the plant to the animal!",
      "Examples: rabbits eat grass, caterpillars eat leaves, deer eat plants, cows eat grass!",
      "Elephants, zebras, giraffes - all herbivores!",
      "Herbivores often have flat teeth for grinding plants!",
      "LEVEL 3: SECONDARY CONSUMERS (CARNIVORES)! 🦊",
      "Animals that eat OTHER ANIMALS are called CARNIVORES!",
      "They're SECONDARY CONSUMERS - they're second in the eating chain!",
      "Examples: foxes eat rabbits, snakes eat mice, hawks eat smaller birds!",
      "Carnivores often have sharp teeth and claws for catching prey!",
      "They're also called PREDATORS, and the animals they hunt are called PREY!",
      "LEVEL 4: TERTIARY CONSUMERS (TOP PREDATORS)! 🦁",
      "Some carnivores eat OTHER carnivores!",
      "These are TERTIARY (third level) CONSUMERS!",
      "Examples: lions, tigers, sharks, eagles!",
      "TOP PREDATORS are animals with no natural predators - nothing hunts them!",
      "They're at the very top of the food chain!",
      "SPECIAL GROUP: OMNIVORES! 🐻",
      "Some animals eat BOTH plants AND animals!",
      "These are called OMNIVORES!",
      "Examples: bears eat berries AND fish, humans eat vegetables AND meat!",
      "Raccoons, pigs, chickens - all omnivores!",
      "Omnivores have both sharp and flat teeth!",
      "LET'S FOLLOW A FOOD CHAIN! 🔗",
      "Example 1: Forest Food Chain",
      "Sun → Oak Tree → Caterpillar → Bird → Hawk",
      "The sun gives energy to the oak tree!",
      "The caterpillar eats oak leaves and gets energy!",
      "The bird eats the caterpillar and gets energy!",
      "The hawk eats the bird and gets energy!",
      "Example 2: Ocean Food Chain",
      "Sun → Algae → Small Fish → Big Fish → Shark",
      "Energy flows from sun to algae to fish to shark!",
      "Example 3: Grassland Food Chain",
      "Sun → Grass → Grasshopper → Mouse → Snake → Hawk",
      "This chain has 5 levels!",
      "IMPORTANT: ENERGY DECREASES! 📊",
      "At each level, some energy is lost as heat!",
      "That's why there are FEWER animals at each higher level!",
      "There's lots of grass, fewer grasshoppers, even fewer mice, and only a few hawks!",
      "This creates an ENERGY PYRAMID!",
      "DECOMPOSERS: Nature's Recyclers! 🍄",
      "Special organisms break down dead plants and animals!",
      "These are called DECOMPOSERS!",
      "Examples: mushrooms, bacteria, worms, fungi!",
      "They return nutrients to the soil so plants can grow!",
      "Without decomposers, dead stuff would pile up forever!",
      "FOOD WEBS: The Real Picture! 🕸️",
      "In nature, food chains aren't simple - they're all connected!",
      "This creates a FOOD WEB - many food chains linked together!",
      "Example: A rabbit eats grass, clover, AND lettuce (3 chains start here!)",
      "A fox eats rabbits, mice, AND birds (3 chains connect here!)",
      "If one part of the web is removed, it affects everything!",
      "If all the rabbits disappear, foxes have to eat more mice!",
      "If all the grass dies, rabbits and grasshoppers both suffer!",
      "BALANCE IN NATURE! ⚖️",
      "Predators help control prey populations!",
      "Without predators, herbivores would eat ALL the plants!",
      "Without producers, everything else would starve!",
      "Every living thing has an important role!",
      "This balance is called an ECOSYSTEM!",
      "WHY THIS MATTERS: 🌍",
      "Understanding food chains helps us protect nature!",
      "If we harm one species, we harm the whole chain!",
      "Endangered species need protection because they're part of food webs!",
      "Pollution can move up food chains and harm top predators!",
      "Remember: Sun → Producers → Consumers → Decomposers!",
      "Everything is connected in the web of life!"
    ],
    questions: [
      {
        question: "What do we call animals that only eat plants?",
        options: ["Carnivores", "Herbivores", "Omnivores", "Producers"],
        correctAnswer: 1,
        explanation: "Herbivores are animals that eat only plants! They're also called primary consumers!"
      },
      {
        question: "What provides energy to start every food chain?",
        options: ["Water", "Soil", "The Sun", "Air"],
        correctAnswer: 2,
        explanation: "The Sun provides the energy that starts all food chains! Plants capture this energy through photosynthesis!"
      },
      {
        question: "What do we call living things that make their own food?",
        options: ["Consumers", "Producers", "Predators", "Herbivores"],
        correctAnswer: 1,
        explanation: "Producers (like plants) make their own food from sunlight through photosynthesis!"
      },
      {
        question: "What is a carnivore?",
        options: ["Eats only plants", "Eats only animals", "Eats plants and animals", "Makes its own food"],
        correctAnswer: 1,
        explanation: "Carnivores eat only other animals! They're meat-eaters like lions, hawks, and snakes!"
      },
      {
        question: "Which animal is an omnivore?",
        options: ["Deer", "Lion", "Bear", "Rabbit"],
        correctAnswer: 2,
        explanation: "Bears are omnivores! They eat both plants (berries, roots) and animals (fish, insects)!"
      },
      {
        question: "What do decomposers do?",
        options: ["Eat plants", "Hunt animals", "Break down dead things", "Make oxygen"],
        correctAnswer: 2,
        explanation: "Decomposers break down dead plants and animals and return nutrients to the soil!"
      },
      {
        question: "In this food chain: Grass → Rabbit → Fox, what is the rabbit?",
        options: ["Producer", "Primary consumer", "Top predator", "Decomposer"],
        correctAnswer: 1,
        explanation: "The rabbit is a primary consumer (herbivore) because it eats the grass (producer)!"
      },
      {
        question: "What is a food web?",
        options: ["One simple food chain", "Many connected food chains", "Spider webs in nature", "Where animals sleep"],
        correctAnswer: 1,
        explanation: "A food web is many food chains connected together! It shows how all living things in an ecosystem are linked!"
      }
    ]
  },
  304: {
    id: 304,
    title: 'Ecosystems & Biomes',
    icon: '🌍',
    description: 'Different environments on Earth',
    content: [
      "Welcome to Earth's neighborhoods! 🌍 Each one is unique and amazing!",
      "Let's learn about ECOSYSTEMS and BIOMES!",
      "WHAT IS AN ECOSYSTEM? 🌿",
      "An ecosystem is all the living AND non-living things in an area working together!",
      "Living things: plants, animals, insects, bacteria!",
      "Non-living things: water, rocks, soil, air, sunlight, temperature!",
      "Everything in an ecosystem depends on everything else!",
      "A pond is an ecosystem: fish, frogs, water plants, water, rocks, sunlight!",
      "A forest is an ecosystem: trees, deer, birds, soil, streams, air!",
      "Even a rotting log is a tiny ecosystem with insects, fungi, and bacteria!",
      "WHAT IS A BIOME? 🗺️",
      "A BIOME is a LARGE region with similar climate, plants, and animals!",
      "Biomes can spread across continents!",
      "Earth has several major biomes - let's explore them!",
      "BIOME 1: TROPICAL RAINFOREST! 🌴",
      "Location: Near the equator (middle of Earth) - South America, Africa, Asia!",
      "Climate: HOT and WET year-round! Rains almost every day!",
      "Temperature: 70-85°F (20-30°C) always!",
      "Plants: TONS of them! Huge trees, vines, colorful flowers!",
      "The trees are so thick they create layers (canopy, understory, forest floor)!",
      "Animals: monkeys, parrots, jaguars, sloths, poison dart frogs, butterflies!",
      "Rainforests have MORE species than any other biome!",
      "Fun fact: Half of all plant and animal species live in rainforests!",
      "They make lots of oxygen - 'lungs of the Earth'!",
      "BIOME 2: DESERT! 🏜️",
      "Location: Sahara (Africa), Mojave (USA), Gobi (Asia), Australian outback!",
      "Climate: HOT and DRY! Very little rain (less than 10 inches per year)!",
      "Temperature: Extremely hot during day (over 100°F), cold at night!",
      "Plants: Cacti, succulents, small shrubs - all adapted to save water!",
      "Cacti store water in their thick stems and have spines instead of leaves!",
      "Animals: camels, lizards, snakes, scorpions, roadrunners, desert foxes!",
      "Desert animals are active at night when it's cooler!",
      "Many animals get water from food instead of drinking!",
      "Fun fact: Deserts cover about 1/3 of Earth's land!",
      "BIOME 3: GRASSLANDS! 🌾",
      "Location: African savanna, American prairies, Asian steppes!",
      "Climate: Moderate rain, distinct wet and dry seasons!",
      "Temperature: Warm summers, cold winters!",
      "Plants: Mostly GRASSES (duh!) with few trees!",
      "The grass can grow very tall - up to 6 feet in some places!",
      "Animals: bison, zebras, lions, elephants, giraffes, prairie dogs, gazelles!",
      "Big herds of grazing animals live here!",
      "Grassfires are natural and help new grass grow!",
      "Fun fact: Grasslands are perfect for farming - that's where we grow wheat and corn!",
      "BIOME 4: TEMPERATE FOREST! 🌲",
      "Location: Eastern USA, Europe, parts of Asia!",
      "Climate: Four distinct seasons - spring, summer, fall, winter!",
      "Temperature: Warm summers, cold winters!",
      "Plants: Deciduous trees (lose leaves in fall) like oak, maple, birch!",
      "Beautiful fall colors when leaves change!",
      "Animals: deer, bears, squirrels, owls, foxes, raccoons!",
      "Animals adapt to seasons - some hibernate in winter!",
      "Lots of insects in summer, none in winter!",
      "Fun fact: Most humans live in this biome - it's comfortable!",
      "BIOME 5: TAIGA (Boreal Forest)! 🌲❄️",
      "Location: Northern Canada, Russia, Scandinavia!",
      "Climate: Long, VERY cold winters, short cool summers!",
      "Temperature: Can drop to -50°F in winter!",
      "Plants: Coniferous trees (pine, spruce, fir) with needle-like leaves!",
      "These trees keep their needles all year!",
      "Animals: moose, wolves, lynx, bears, owls, caribou!",
      "Animals have thick fur for the cold!",
      "Snow covers ground for months!",
      "Fun fact: Largest land biome on Earth!",
      "BIOME 6: TUNDRA! ❄️📍",
      "Location: Arctic (North Pole), Antarctic (South Pole), mountaintops!",
      "Climate: FREEZING! Short summer, looong winter!",
      "Temperature: Can be -40°F or colder!",
      "Plants: Mosses, lichens, small shrubs - no trees! Ground is frozen (permafrost)!",
      "Growing season is only 6-10 weeks!",
      "Animals: polar bears, arctic foxes, caribou, musk oxen, penguins (Antarctic)!",
      "Animals have special adaptations - thick fur, blubber, white coloring!",
      "Fun fact: 'Tundra' means 'treeless plain'!",
      "In summer, flowers bloom everywhere for a few weeks!",
      "BIOME 7: OCEAN! 🌊",
      "Location: Covers 71% of Earth's surface!",
      "Climate: Varies - cold at poles, warm at equator!",
      "Temperature: Surface warm, deep ocean very cold!",
      "Plants: Algae, seaweed, kelp, phytoplankton (tiny floating plants)!",
      "Animals: fish, whales, dolphins, sharks, octopuses, coral, jellyfish!",
      "Ocean has zones: shallow (coral reefs), deep (dark and cold), ocean floor!",
      "Coral reefs are like underwater rainforests - full of life!",
      "Fun fact: We know more about space than the deep ocean!",
      "Ocean makes most of Earth's oxygen through phytoplankton!",
      "WHY BIOMES MATTER: 🌎",
      "Each biome is a home to thousands of species!",
      "Climate change is affecting all biomes!",
      "Protecting biomes protects biodiversity!",
      "We depend on all biomes for resources - food, wood, medicine!",
      "Remember: Climate + Plants + Animals = Biome!",
      "Every biome is precious and unique!"
    ],
    questions: [
      {
        question: "Which biome is hot and rainy with many trees?",
        options: ["Desert", "Tundra", "Rainforest", "Ocean"],
        correctAnswer: 2,
        explanation: "Tropical rainforests are hot and wet with tons of trees and the most biodiversity!"
      },
      {
        question: "Where would you find cacti?",
        options: ["Rainforest", "Desert", "Ocean", "Tundra"],
        correctAnswer: 1,
        explanation: "Cacti live in deserts where they've adapted to store water and survive with little rain!"
      },
      {
        question: "What is an ecosystem?",
        options: ["Only animals", "Only plants", "Living and non-living things working together", "Just the weather"],
        correctAnswer: 2,
        explanation: "An ecosystem includes ALL living and non-living things interacting in an area!"
      },
      {
        question: "Which biome has four distinct seasons?",
        options: ["Rainforest", "Desert", "Temperate forest", "Tundra"],
        correctAnswer: 2,
        explanation: "Temperate forests have four seasons: spring, summer, fall, and winter!"
      },
      {
        question: "What is permafrost?",
        options: ["Permanent snow", "Permanently frozen ground", "A type of tree", "Winter weather"],
        correctAnswer: 1,
        explanation: "Permafrost is permanently frozen ground found in the tundra biome!"
      },
      {
        question: "Which biome covers most of Earth's surface?",
        options: ["Rainforest", "Desert", "Ocean", "Grassland"],
        correctAnswer: 2,
        explanation: "The ocean biome covers 71% of Earth's surface - that's most of our planet!"
      },
      {
        question: "What makes grasslands good for farming?",
        options: ["Lots of trees", "Rich soil from grass", "No animals", "Always raining"],
        correctAnswer: 1,
        explanation: "Grasslands have rich soil from years of grass growth - perfect for growing crops!"
      },
      {
        question: "In which biome would you find polar bears?",
        options: ["Desert", "Tundra", "Rainforest", "Grassland"],
        correctAnswer: 1,
        explanation: "Polar bears live in the Arctic tundra where it's freezing and covered in ice!"
      }
    ]
  },
  305: {
    id: 305,
    title: 'Adaptation & Survival',
    icon: '🦎',
    description: 'How animals and plants survive',
    content: [
      "Time to discover nature's superpowers! 🦎 Adaptations are AMAZING!",
      "Every living thing has special features that help it survive!",
      "These special features are called ADAPTATIONS!",
      "WHAT ARE ADAPTATIONS? 🔍",
      "Adaptations are traits that help an organism survive in its environment!",
      "They develop over MANY generations through evolution!",
      "An adaptation can be physical (body parts) or behavioral (how they act)!",
      "Let's explore incredible adaptations!",
      "PHYSICAL ADAPTATIONS: Body Features! 💪",
      "CAMOUFLAGE: Blending In! 🎨",
      "Polar bears have WHITE fur to blend in with snow!",
      "This helps them sneak up on seals (their food)!",
      "Chameleons can CHANGE COLOR to match their surroundings!",
      "Stick insects look exactly like sticks - predators walk right past them!",
      "Arctic foxes are white in winter, brown in summer - perfect camouflage year-round!",
      "SPECIALIZED BODY PARTS: Tools for Survival! 🔧",
      "Giraffes have LONG NECKS to reach leaves high in trees!",
      "Other animals can't reach that food, so giraffes have less competition!",
      "Birds have different BEAK SHAPES for different foods!",
      "Hummingbirds: long, thin beaks for drinking nectar from flowers!",
      "Eagles: sharp, hooked beaks for tearing meat!",
      "Pelicans: big pouches for scooping up fish!",
      "Woodpeckers: strong, pointed beaks for drilling into trees!",
      "FEET AND CLAWS: Perfect for Their Needs! 🦶",
      "Ducks have WEBBED FEET for swimming!",
      "Owls have SHARP TALONS for catching prey!",
      "Monkeys have hands that can GRASP branches!",
      "Cheetahs have claws that don't retract - like cleats for running fast!",
      "PROTECTIVE FEATURES: Defense Mechanisms! 🛡️",
      "Porcupines have sharp QUILLS - don't touch!",
      "Skunks spray a STINKY liquid - predators stay away!",
      "Turtles have hard SHELLS to hide inside!",
      "Poison dart frogs have BRIGHT COLORS warning 'I'm poisonous!'",
      "Thorns on roses protect them from being eaten!",
      "SURVIVAL IN EXTREME CONDITIONS! 🌡️",
      "Cacti have THICK SKIN to store water in the desert!",
      "Their spines (modified leaves) reduce water loss!",
      "Camels have TWO HUMPS storing fat (not water!) for energy!",
      "Their wide feet don't sink in sand!",
      "Arctic animals have THICK FUR or BLUBBER for warmth!",
      "Penguins huddle together and take turns in the middle to stay warm!",
      "Desert animals have large EARS to release heat (like elephant ears)!",
      "BREATHING ADAPTATIONS! 💨",
      "Fish have GILLS to breathe underwater!",
      "Whales and dolphins have BLOWHOLES on top of their heads!",
      "Amphibians can breathe through their SKIN!",
      "Plants in water have roots that can get oxygen even underwater!",
      "BEHAVIORAL ADAPTATIONS: How They Act! 🎭",
      "MIGRATION: Traveling for Survival! ✈️",
      "Many birds fly SOUTH for winter when it's cold and food is scarce!",
      "They return north in spring when weather is warm!",
      "Monarch butterflies migrate thousands of miles from Canada to Mexico!",
      "Caribou migrate across the tundra following food!",
      "Whales migrate to warm waters to have babies!",
      "HIBERNATION: Winter Sleep! 😴",
      "Some animals HIBERNATE - deep sleep through winter!",
      "Bears hibernate in dens, living off their body fat!",
      "Their heart rate slows down, body temperature drops!",
      "Groundhogs, chipmunks, and bats also hibernate!",
      "This saves energy when food is hard to find!",
      "NOCTURNAL BEHAVIOR: Active at Night! 🌙",
      "Some animals are NOCTURNAL - awake at night, sleep during day!",
      "Owls hunt at night when their prey (mice) is active!",
      "Desert animals are nocturnal to avoid hot daytime temperatures!",
      "Bats use echolocation to 'see' in the dark!",
      "HUNTING STRATEGIES: Finding Food! 🎯",
      "Lions hunt in GROUPS (prides) to catch big prey!",
      "Cheetahs use SPEED - fastest land animal at 70 mph!",
      "Spiders spin WEBS to trap flying insects!",
      "Angler fish have a GLOWING LURE to attract prey in deep ocean!",
      "Archerfish shoot WATER to knock insects into the water!",
      "STORING FOOD: Planning Ahead! 🥜",
      "Squirrels bury nuts in fall to eat in winter!",
      "Bees make honey to feed the hive when flowers don't bloom!",
      "Ants store food in their underground colonies!",
      "COMMUNICATION: Working Together! 📢",
      "Bees do a 'waggle dance' to tell others where flowers are!",
      "Wolves howl to communicate with their pack!",
      "Dolphins use clicks and whistles to 'talk'!",
      "Fireflies flash lights to attract mates!",
      "PLANT ADAPTATIONS: They're Alive Too! 🌿",
      "Venus flytraps SNAP SHUT to catch insects for nutrients!",
      "Sunflowers turn to FOLLOW THE SUN across the sky!",
      "Mangrove trees have roots ABOVE WATER to breathe!",
      "Dandelion seeds have PARACHUTES to fly on the wind!",
      "Water lilies have flat leaves to FLOAT on water!",
      "Pine trees have NEEDLES instead of leaves - less water loss in cold climates!",
      "HOW ADAPTATIONS DEVELOP: 🧬",
      "Adaptations happen through NATURAL SELECTION!",
      "Animals with helpful traits survive better and have more babies!",
      "Those babies inherit the helpful traits!",
      "Over many generations, the trait becomes common!",
      "This process takes thousands of years!",
      "AMAZING ADAPTATION EXAMPLES: 🌟",
      "The platypus: has a DUCK BILL, lays EGGS, but feeds MILK like a mammal!",
      "Electric eels: can produce ELECTRIC SHOCKS to stun prey!",
      "Leafy sea dragon: looks exactly like SEAWEED!",
      "Bombardier beetle: shoots BOILING CHEMICALS at attackers!",
      "Mimic octopus: can COPY the shape and color of other animals!",
      "WHY ADAPTATIONS MATTER: 🌍",
      "They show how life changes to fit different environments!",
      "They teach us about evolution and biodiversity!",
      "Many human inventions are inspired by nature's adaptations!",
      "Climate change is happening faster than animals can adapt!",
      "We need to protect habitats so animals can survive!",
      "Remember: Every living thing has special adaptations!",
      "These superpowers help them survive in their unique homes!",
      "Nature is the ultimate engineer! 🏗️"
    ],
    questions: [
      {
        question: "What is an adaptation?",
        options: ["A type of animal", "A special feature that helps survival", "A place to live", "A type of food"],
        correctAnswer: 1,
        explanation: "An adaptation is a special feature (physical or behavioral) that helps a living thing survive in its environment!"
      },
      {
        question: "Why do some birds migrate?",
        options: ["To find warmer weather and food", "To hide from predators", "To find water", "To make nests"],
        correctAnswer: 0,
        explanation: "Birds migrate to find warmer weather and more food in winter! It's a behavioral adaptation!"
      },
      {
        question: "What is camouflage?",
        options: ["Finding food", "Blending in with surroundings", "Making noise", "Swimming fast"],
        correctAnswer: 1,
        explanation: "Camouflage is a physical adaptation that helps animals blend in with their surroundings to hide from predators or sneak up on prey!"
      },
      {
        question: "What do bears do in winter?",
        options: ["Migrate south", "Hibernate", "Shed their fur", "Build nests"],
        correctAnswer: 1,
        explanation: "Bears hibernate in winter - they sleep deeply in dens, living off their body fat when food is scarce!"
      },
      {
        question: "Why do cacti have thick skin?",
        options: ["To look pretty", "To store water", "To keep warm", "To scare animals"],
        correctAnswer: 1,
        explanation: "Cacti have thick skin to STORE WATER in the dry desert! It's an adaptation for surviving with little rain!"
      },
      {
        question: "What adaptation helps a giraffe get food?",
        options: ["Long neck", "Sharp teeth", "Webbed feet", "Bright colors"],
        correctAnswer: 0,
        explanation: "A giraffe's LONG NECK helps it reach leaves high in trees that other animals can't reach!"
      },
      {
        question: "What are nocturnal animals?",
        options: ["Animals that swim", "Animals active at night", "Animals that hibernate", "Animals that migrate"],
        correctAnswer: 1,
        explanation: "Nocturnal animals are active at NIGHT and sleep during the day! It's a behavioral adaptation!"
      },
      {
        question: "How do fish breathe underwater?",
        options: ["Lungs", "Gills", "Nose", "Skin only"],
        correctAnswer: 1,
        explanation: "Fish use GILLS to breathe underwater! Gills extract oxygen from water - a perfect adaptation for aquatic life!"
      }
    ]
  },
  // Matter & Energy (401-405)
  401: {
    id: 401,
    title: 'States of Matter',
    icon: '💧',
    description: 'Solid, liquid, and gas',
    content: [
      "Let's explore the building blocks of everything! 💧 Matter is all around us!",
      "WHAT IS MATTER? 🤔",
      "Matter is anything that takes up space and has weight (mass)!",
      "You are matter! This device is matter! Air is matter!",
      "All matter is made of tiny particles called ATOMS and MOLECULES!",
      "These particles are too small to see, but they're always there!",
      "Matter comes in THREE MAIN STATES!",
      "STATE 1: SOLIDS! 🧊",
      "Solids have a DEFINITE SHAPE and VOLUME!",
      "A solid keeps its shape - a book stays book-shaped!",
      "You can't easily squish or pour a solid!",
      "WHY? The particles in solids are packed TIGHTLY together!",
      "The particles vibrate in place but can't move around!",
      "They're like people in a crowded elevator - close together, can barely move!",
      "Examples of solids: ice, rocks, wood, metal, your bones, a pencil!",
      "Properties of solids: hard or soft, rough or smooth, heavy or light!",
      "Even though solids seem still, their particles are always vibrating!",
      "STATE 2: LIQUIDS! 💧",
      "Liquids have a DEFINITE VOLUME but NO definite shape!",
      "A liquid takes the shape of whatever container you put it in!",
      "Pour water from a cup to a bowl - it changes shape!",
      "You can pour liquids, but you can't really squish them!",
      "WHY? Particles in liquids are close together but can SLIDE past each other!",
      "They're like people at a party - close but can move around!",
      "Examples of liquids: water, milk, juice, oil, honey, lava, blood!",
      "Liquids flow - they can move from one place to another!",
      "Some liquids flow fast (water), some flow slowly (honey)!",
      "This is called VISCOSITY - how thick or thin a liquid is!",
      "STATE 3: GASES! 💨",
      "Gases have NO definite shape and NO definite volume!",
      "A gas spreads out to fill ANY container it's in!",
      "Open a bottle of perfume - the smell spreads through the room!",
      "You CAN compress (squish) gases - like pumping air into a tire!",
      "WHY? Particles in gases are FAR APART and move FREELY and FAST!",
      "They're like people in a huge park - lots of space, moving everywhere!",
      "Examples of gases: air, steam, helium, oxygen, carbon dioxide!",
      "You can't see most gases, but they're real matter!",
      "Gases have no color, or they might be invisible!",
      "Air is a gas mixture - mostly nitrogen and oxygen!",
      "THE AMAZING WATER CYCLE! 🌊☁️",
      "Water is SPECIAL - it naturally exists in all three states on Earth!",
      "ICE is solid water (below 32°F / 0°C)!",
      "WATER is liquid water (32-212°F / 0-100°C)!",
      "STEAM/WATER VAPOR is gas water (above 212°F / 100°C)!",
      "Water can change between these states when heated or cooled!",
      "CHANGING STATES: Phase Changes! 🔄",
      "When you add or remove heat, matter can change states!",
      "MELTING: Solid → Liquid (ice melts to water)!",
      "Happens when you ADD heat! Particles speed up and break apart!",
      "Ice cream melts on a hot day!",
      "FREEZING: Liquid → Solid (water freezes to ice)!",
      "Happens when you REMOVE heat! Particles slow down and lock together!",
      "Water in the freezer becomes ice!",
      "EVAPORATION: Liquid → Gas (water evaporates to water vapor)!",
      "Happens when you add heat OR just wait! Particles escape into air!",
      "Puddles dry up in the sun!",
      "Sweat evaporates off your skin to cool you!",
      "CONDENSATION: Gas → Liquid (water vapor condenses to water)!",
      "Happens when you remove heat! Gas particles slow and group together!",
      "Water droplets form on cold glass!",
      "Clouds are water vapor that condensed!",
      "SUBLIMATION: Solid → Gas (skipping liquid!)!",
      "Dry ice (frozen carbon dioxide) turns directly into gas!",
      "Snow can sublimate in very cold, dry weather!",
      "DEPOSITION: Gas → Solid (skipping liquid!)!",
      "Frost forms when water vapor freezes directly onto surfaces!",
      "PARTICLES IN MOTION! 🏃",
      "In SOLIDS: particles vibrate in place (slow)!",
      "In LIQUIDS: particles slide past each other (medium speed)!",
      "In GASES: particles zoom around freely (fast!)!",
      "Temperature affects particle speed!",
      "Hot = particles move FASTER!",
      "Cold = particles move SLOWER!",
      "REAL-WORLD EXAMPLES! 🌍",
      "Morning dew: Water vapor (gas) condensed into liquid water!",
      "Boiling pot: Liquid water evaporating into steam (gas)!",
      "Ice cubes in drink: Solid ice melting into liquid water!",
      "Freezer: Liquid water freezing into solid ice!",
      "Hot shower: Steam (gas) condensing on cool mirror (liquid droplets)!",
      "FUN FACTS! ⭐",
      "The sun turns ocean water into water vapor (evaporation)!",
      "That vapor rises, cools, and forms clouds (condensation)!",
      "Rain brings the water back down!",
      "Metal can be solid (iron), liquid (molten lava), or gas (metal vapor in stars)!",
      "Glass is actually a super-slow-moving liquid!",
      "Remember: Everything is made of matter in constant motion!",
      "Solids, liquids, and gases are all around you right now!"
    ],
    questions: [
      {
        question: "Which state of matter has a definite shape and volume?",
        options: ["Liquid", "Gas", "Solid", "All of them"],
        correctAnswer: 2,
        explanation: "Solids have both definite shape and volume! Their particles are tightly packed together!"
      },
      {
        question: "What is it called when liquid becomes gas?",
        options: ["Melting", "Freezing", "Evaporation", "Condensation"],
        correctAnswer: 2,
        explanation: "Evaporation is when liquid becomes gas! Like water becoming water vapor!"
      },
      {
        question: "Which state has particles that are far apart and move freely?",
        options: ["Solid", "Liquid", "Gas", "None"],
        correctAnswer: 2,
        explanation: "Gas particles are far apart and move freely and fast! They spread out to fill any space!"
      },
      {
        question: "What happens when you remove heat from water?",
        options: ["It evaporates", "It freezes", "It melts", "Nothing"],
        correctAnswer: 1,
        explanation: "When you remove heat from water, it freezes into ice! The particles slow down and lock together!"
      },
      {
        question: "What is water vapor?",
        options: ["Liquid water", "Solid water", "Gas water", "Steam you can see"],
        correctAnswer: 2,
        explanation: "Water vapor is water in its GAS state! You usually can't see it - it's invisible in the air!"
      },
      {
        question: "Why can you pour a liquid but not a solid?",
        options: ["Liquids are lighter", "Liquid particles can slide past each other", "Solids are too heavy", "Liquids have no particles"],
        correctAnswer: 1,
        explanation: "Liquid particles are close but can slide past each other, so liquids can flow and be poured!"
      },
      {
        question: "What is condensation?",
        options: ["Solid to liquid", "Liquid to gas", "Gas to liquid", "Solid to gas"],
        correctAnswer: 2,
        explanation: "Condensation is gas turning into liquid! Like water droplets forming on a cold glass!"
      },
      {
        question: "At what temperature does water freeze?",
        options: ["0°C (32°F)", "50°C (122°F)", "100°C (212°F)", "-10°C (14°F)"],
        correctAnswer: 0,
        explanation: "Water freezes at 0°C (32°F)! Below this temperature, liquid water becomes solid ice!"
      }
    ]
  },

};
