interface Question {
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

interface TopicLesson {
  id: number;
  title: string;
  icon: string;
  description: string;
  content: string[];
  questions: Question[];
}

export const lessons: { [key: number]: TopicLesson } = {
  402: {
    id: 402,
    title: 'Properties of Materials',
    icon: '🔬',
    description: 'What materials are like',
    content: [
      "Let's become material detectives! 🔬 Every material has special properties!",
      "PROPERTIES are the characteristics that describe what a material is like!",
      "Scientists use properties to choose the RIGHT material for each job!",
      "PHYSICAL PROPERTIES: What You Can See and Feel! 👀👋",
      "HARDNESS: How easy or hard it is to scratch or dent!",
      "HARD materials: diamond, metal, rock, glass!",
      "SOFT materials: cotton, rubber, foam, butter!",
      "Hardness helps us choose materials - diamonds cut other materials!",
      "FLEXIBILITY vs RIGIDITY:",
      "FLEXIBLE materials can BEND without breaking!",
      "Examples: rubber bands, fabric, paper, plastic bags!",
      "RIGID materials stay STIFF and don't bend easily!",
      "Examples: wood boards, metal rods, glass, concrete!",
      "Flexibility is great for clothes! Rigidity is good for buildings!",
      "TEXTURE: How It Feels!",
      "SMOOTH: glass, polished metal, silk!",
      "ROUGH: sandpaper, tree bark, concrete!",
      "BUMPY: golf ball, gravel!",
      "Texture affects how things work - smooth surfaces slide easier!",
      "OPTICAL PROPERTIES: Light and Materials! 💡",
      "TRANSPARENT: Light passes through - you can see through it!",
      "Examples: clear glass, water, air, plastic wrap!",
      "Windows are transparent so we can see outside!",
      "TRANSLUCENT: Light passes through, but you can't see clearly!",
      "Examples: frosted glass, wax paper, some lampshades!",
      "OPAQUE: Light CANNOT pass through - you can't see through it!",
      "Examples: wood, metal, brick, your hand!",
      "Most materials are opaque!",
      "THERMAL PROPERTIES: Heat Behavior! 🔥❄️",
      "CONDUCTORS: Materials that let heat pass through EASILY!",
      "Examples: metals (copper, aluminum, iron, gold)!",
      "That's why metal pans heat up fast for cooking!",
      "That's also why metal feels cold - it conducts heat away from your hand!",
      "INSULATORS: Materials that DON'T let heat pass through easily!",
      "Examples: wood, plastic, rubber, foam, air!",
      "Winter coats use insulation to trap heat!",
      "Coolers use insulation to keep drinks cold!",
      "Oven mitts are insulators so you don't burn your hands!",
      "ELECTRICAL PROPERTIES: Electricity Flow! ⚡",
      "ELECTRICAL CONDUCTORS: Let electricity flow through!",
      "Examples: metals (copper wires), water with salt!",
      "Power lines use metal wires to carry electricity!",
      "ELECTRICAL INSULATORS: Block electricity!",
      "Examples: rubber, plastic, glass, wood, air!",
      "Wire coatings are plastic insulators for safety!",
      "NEVER touch electrical wires - but the plastic coating is safe!",
      "MAGNETIC PROPERTIES: Magnet Attraction! 🧲",
      "MAGNETIC materials are attracted to magnets!",
      "Examples: iron, steel, nickel, cobalt!",
      "Most materials are NOT magnetic!",
      "Aluminum, copper, plastic, wood - NOT magnetic!",
      "Magnets work through magnetic force!",
      "Refrigerator magnets stick because the fridge is steel!",
      "DENSITY: How Packed Together! ⚖️",
      "DENSITY is how much matter is packed into a space!",
      "DENSE materials are heavy for their size!",
      "Examples: metals (lead, gold), rocks!",
      "A small piece of gold is very heavy!",
      "LESS DENSE materials are light for their size!",
      "Examples: foam, cork, feathers, balloons!",
      "Density determines if things float or sink!",
      "LESS dense than water = FLOATS (like wood)!",
      "MORE dense than water = SINKS (like rocks)!",
      "WATER PROPERTIES: Absorbent vs Waterproof! 💧",
      "ABSORBENT materials SOAK UP water!",
      "Examples: sponges, paper towels, fabric, soil!",
      "Towels are absorbent so they dry you off!",
      "WATERPROOF materials keep water OUT!",
      "Examples: plastic, rubber, wax, glass!",
      "Raincoats are waterproof to keep you dry!",
      "Umbrellas use waterproof fabric!",
      "STRENGTH: Resistance to Breaking! 💪",
      "STRONG materials are hard to break or tear!",
      "Examples: steel, kevlar, spider silk (super strong!)!",
      "WEAK materials break or tear easily!",
      "Examples: tissue paper, thin plastic!",
      "Strength matters for safety - seatbelts must be strong!",
      "ELASTICITY: Stretching and Bouncing! 🪱",
      "ELASTIC materials can STRETCH and return to original shape!",
      "Examples: rubber bands, springs, balloons!",
      "Pull a rubber band - it stretches!",
      "Let go - it snaps back!",
      "Trampolines use elastic materials!",
      "CHOOSING MATERIALS: Right Tool for the Job! 🛠️",
      "Windows: transparent (glass) so we can see!",
      "Pots and pans: conductors (metal) to heat food!",
      "Winter coats: insulators (fabric with air pockets) to stay warm!",
      "Electrical wires: conductors (copper) with insulator coating (plastic)!",
      "Raincoats: waterproof (rubber/plastic) to stay dry!",
      "Towels: absorbent (cotton) to dry things!",
      "Bridges: strong (steel, concrete) to hold weight!",
      "Balloons: elastic (rubber) to stretch and hold air!",
      "COMBINATIONS: Materials Working Together! 🤝",
      "Many objects use MULTIPLE materials!",
      "Phone: glass screen (transparent), metal/plastic body (rigid), wires (conductor)!",
      "Car: metal frame (strong), glass windows (transparent), rubber tires (flexible, waterproof)!",
      "Pencil: wood body (easy to hold), graphite core (leaves marks)!",
      "Engineers choose materials carefully for each part!",
      "Remember: Properties help us understand and use materials!",
      "Every material is special in its own way!"
    ],
    questions: [
      {
        question: "What do we call materials that let light pass through?",
        options: ["Opaque", "Transparent", "Absorbent", "Magnetic"],
        correctAnswer: 1,
        explanation: "Transparent materials let light pass through so you can see through them, like glass and clear plastic!"
      },
      {
        question: "Which material is a good conductor?",
        options: ["Rubber", "Plastic", "Metal", "Wood"],
        correctAnswer: 2,
        explanation: "Metals are good conductors - they let electricity and heat pass through easily! That's why wires are metal!"
      },
      {
        question: "What property means a material soaks up water?",
        options: ["Waterproof", "Magnetic", "Absorbent", "Rigid"],
        correctAnswer: 2,
        explanation: "Absorbent means the material soaks up water, like a sponge or towel! Perfect for drying things!"
      },
      {
        question: "What are insulators good for?",
        options: ["Conducting electricity", "Keeping heat in or out", "Letting light through", "Attracting magnets"],
        correctAnswer: 1,
        explanation: "Insulators are great for keeping heat in or out! That's why winter coats and oven mitts use insulators!"
      },
      {
        question: "Which material is magnetic?",
        options: ["Plastic", "Wood", "Iron", "Aluminum"],
        correctAnswer: 2,
        explanation: "Iron is magnetic! It sticks to magnets. Most materials (plastic, wood, aluminum) are NOT magnetic!"
      },
      {
        question: "Why does wood float in water?",
        options: ["It's magic", "It's less dense than water", "It's waterproof", "It's transparent"],
        correctAnswer: 1,
        explanation: "Wood floats because it's LESS DENSE than water! Objects less dense than water float!"
      },
      {
        question: "What property means a material can bend without breaking?",
        options: ["Rigid", "Flexible", "Dense", "Opaque"],
        correctAnswer: 1,
        explanation: "Flexible materials can bend without breaking! Like rubber bands, fabric, and paper!"
      },
      {
        question: "Why are pot handles made of plastic or wood?",
        options: ["They look nice", "They're insulators and won't burn you", "They're magnetic", "They're transparent"],
        correctAnswer: 1,
        explanation: "Pot handles are made of insulators (plastic, wood) so they don't get hot and burn your hand!"
      }
    ]
  },
  403: {
    id: 403,
    title: 'Chemical vs Physical Changes',
    icon: '🧪',
    description: 'Different types of changes',
    content: [
      "Time to be a change detective! 🧪 Matter changes in TWO different ways!",
      "Understanding these changes helps us understand the world!",
      "Let's learn about PHYSICAL and CHEMICAL changes!",
      "PHYSICAL CHANGES: Same Stuff, Different Look! 🎨",
      "In a physical change, the MATERIAL STAYS THE SAME!",
      "Only the APPEARANCE changes - how it looks!",
      "The molecules (tiny particles) stay the same!",
      "Examples of Physical Changes:",
      "✂️ CUTTING: Cut paper into pieces - it's still paper!",
      "🔨 BREAKING: Break a stick - pieces are still wood!",
      "🧊 MELTING: Ice melts to water - both are H2O (same molecules)!",
      "❄️ FREEZING: Water freezes to ice - still H2O!",
      "☁️ EVAPORATING: Water becomes steam - still H2O!",
      "💧 CONDENSING: Steam becomes water - still H2O!",
      "📏 BENDING: Bend a paper clip - still metal!",
      "🎨 DISSOLVING: Sugar in water - sugar is still there (taste it!)!",
      "More Physical Change Examples:",
      "Crumpling paper - still paper!",
      "Shredding cheese - still cheese!",
      "Crushing a can - still aluminum!",
      "Folding clothes - still fabric!",
      "Mixing salad - vegetables don't change!",
      "Key Feature: You can often UNDO physical changes!",
      "Freeze water back to ice!",
      "Straighten a paper clip!",
      "Separate a salad back into parts!",
      "CHEMICAL CHANGES: New Stuff Made! 🔬",
      "In a chemical change, you get COMPLETELY NEW MATERIALS!",
      "The original material is GONE - you can't get it back!",
      "The molecules REARRANGE to make new substances!",
      "This is also called a CHEMICAL REACTION!",
      "Examples of Chemical Changes:",
      "🔥 BURNING: Wood burns → becomes ash and smoke (new materials)!",
      "You can't unburn wood back to wood!",
      "🍳 COOKING: Raw egg → cooked egg (new material)!",
      "You can't uncook an egg!",
      "🍞 BAKING: Cake batter → fluffy cake (new material)!",
      "The flour, eggs, sugar REACT to make something new!",
      "🦴 RUSTING: Iron + oxygen → rust (iron oxide, new material)!",
      "Rust is NOT the same as shiny iron!",
      "🥛 SOURING: Fresh milk → sour milk (bacteria changed it)!",
      "Can't make it fresh again!",
      "🍎 ROTTING: Fresh apple → brown mushy apple (decomposition)!",
      "Bacteria and fungi cause chemical changes!",
      "🧪 DIGESTION: Food in stomach → nutrients (broken down)!",
      "Your body chemically changes food!",
      "🔋 BATTERIES: Chemical reactions make electricity!",
      "🎆 FIREWORKS: Explosions are chemical reactions!",
      "More Chemical Change Examples:",
      "Leaves changing color in fall (chlorophyll breaks down)!",
      "Silver tarnishing (reacting with sulfur in air)!",
      "Bread rising (yeast producing carbon dioxide)!",
      "Pancakes browning (Maillard reaction)!",
      "Key Feature: You CANNOT undo chemical changes!",
      "Once the new substance forms, you're stuck with it!",
      "SIGNS of a Chemical Change! 🚨",
      "How do you know a chemical change happened?",
      "1. COLOR CHANGE: Apples turn brown, iron turns orange (rust)!",
      "2. SMELL CHANGE: Rotten eggs smell bad (sulfur release)!",
      "3. BUBBLES/GAS: Baking soda + vinegar makes bubbles (CO2 gas)!",
      "4. HEAT OR LIGHT: Burning produces heat and light!",
      "5. PRECIPITATE: Solid forms in liquid (like when two clear liquids make milky mixture)!",
      "6. HARD TO REVERSE: Can't get original material back!",
      "If you see these signs, it's probably a chemical change!",
      "COMPARING THE TWO: ⚖️",
      "PHYSICAL: Appearance changes, molecules stay same, reversible!",
      "CHEMICAL: New substance forms, molecules change, irreversible!",
      "TRICKY EXAMPLES: Let's Practice! 🤔",
      "Dissolving salt in water: PHYSICAL! Salt molecules still there!",
      "The salt hasn't changed - evaporate the water and you get salt back!",
      "Boiling water: PHYSICAL! Steam is still water (H2O)!",
      "Making caramel from sugar: CHEMICAL! Heat changes sugar molecules!",
      "Caramel is a new substance, not regular sugar!",
      "Tearing paper: PHYSICAL! Still the same paper!",
      "Burning paper: CHEMICAL! Becomes ash and smoke!",
      "WHY THIS MATTERS: 🌟",
      "Cooking uses chemical changes to make yummy food!",
      "Your body uses chemical changes to get energy from food!",
      "Scientists use chemical changes to make medicines!",
      "Physical changes help us recycle (melt plastic, remold it)!",
      "Understanding changes helps us prevent unwanted ones (like rust)!",
      "ENERGY AND CHANGES: 💥",
      "Many chemical changes release energy (burning, digestion)!",
      "Some chemical changes absorb energy (cold packs)!",
      "Physical changes also involve energy (melting needs heat)!",
      "Remember the key question: Did the material change into something new?",
      "If YES → Chemical change!",
      "If NO → Physical change!"
    ],
    questions: [
      {
        question: "Which is a physical change?",
        options: ["Burning wood", "Cutting paper", "Baking a cake", "Rusting metal"],
        correctAnswer: 1,
        explanation: "Cutting paper is physical - you still have paper, just smaller pieces! The material didn't change!"
      },
      {
        question: "What type of change is cooking an egg?",
        options: ["Physical", "Chemical", "No change", "Both"],
        correctAnswer: 1,
        explanation: "Cooking an egg is chemical - you can't uncook it back to raw! New materials form!"
      },
      {
        question: "Which is a sign of a chemical change?",
        options: ["Getting bigger", "Color change", "Breaking apart", "Getting colder"],
        correctAnswer: 1,
        explanation: "Color change often means a chemical change is happening! Like apples turning brown or iron rusting!"
      },
      {
        question: "Is melting ice a physical or chemical change?",
        options: ["Physical", "Chemical", "Both", "Neither"],
        correctAnswer: 0,
        explanation: "Melting ice is PHYSICAL! Ice and water are both H2O - same substance, different state!"
      },
      {
        question: "Can you reverse a chemical change?",
        options: ["Yes, always", "No, usually not", "Sometimes", "Only with magic"],
        correctAnswer: 1,
        explanation: "You usually CANNOT reverse chemical changes! Once wood burns to ash, you can't get the wood back!"
      },
      {
        question: "What happens when you burn wood?",
        options: ["Physical change", "Chemical change making ash and smoke", "No change", "Wood gets smaller only"],
        correctAnswer: 1,
        explanation: "Burning wood is a CHEMICAL change! It creates NEW materials (ash and smoke) that are different from wood!"
      },
      {
        question: "Which is a physical change?",
        options: ["Digesting food", "Freezing water", "Rusting metal", "Baking bread"],
        correctAnswer: 1,
        explanation: "Freezing water is physical! Ice and water are both H2O - you can melt ice back to water!"
      },
      {
        question: "When metal rusts, what type of change is it?",
        options: ["Physical", "Chemical", "No change", "Both"],
        correctAnswer: 1,
        explanation: "Rusting is CHEMICAL! Iron combines with oxygen to make rust (iron oxide) - a completely new substance!"
      }
    ]
  },
  404: {
    id: 404,
    title: 'Forms of Energy',
    icon: '⚡',
    description: 'Different types of energy',
    content: [
      "Energy powers everything! ⚡ Let's explore all its amazing forms!",
      "WHAT IS ENERGY? 💪",
      "Energy is the ability to do WORK or cause CHANGE!",
      "Without energy, nothing would happen - no movement, no growth, no life!",
      "Energy can't be created or destroyed - it just changes form!",
      "This is called the LAW OF CONSERVATION OF ENERGY!",
      "FORM 1: LIGHT ENERGY! ☀️💡",
      "Light energy is energy you can SEE!",
      "Light travels in waves at incredible speed - 186,000 miles per second!",
      "Sources: The SUN (biggest source!), light bulbs, fire, stars, glow sticks!",
      "Plants use light energy for photosynthesis!",
      "We use light to see, read, and do activities!",
      "Different colors of light have different energy levels!",
      "Light can travel through space - that's how sunlight reaches Earth!",
      "FORM 2: SOUND ENERGY! 🔊🎵",
      "Sound is energy from VIBRATIONS!",
      "When things vibrate (move back and forth fast), they make sound waves!",
      "Sound travels through air, water, and solids!",
      "Sound CANNOT travel through space (no air to vibrate)!",
      "Examples: music, talking, animal noises, thunder, car horns!",
      "Loud sounds have more energy than quiet sounds!",
      "Your vocal cords vibrate to make your voice!",
      "Musical instruments make sound by vibrating strings, air, or surfaces!",
      "FORM 3: HEAT (THERMAL) ENERGY! 🔥🌡️",
      "Heat energy makes things WARM!",
      "All matter has heat energy - even ice has some!",
      "Heat is really the movement of tiny particles!",
      "Faster particles = more heat!",
      "Sources: Sun, fire, hot stove, your body, friction (rubbing)!",
      "Heat moves from hot objects to cold objects!",
      "We use heat energy for cooking, warming homes, and running engines!",
      "Rubbing your hands together creates heat from friction!",
      "The Earth's core is super hot - heat from radioactivity!",
      "FORM 4: ELECTRICAL ENERGY! ⚡🔌",
      "Electrical energy is moving electrons (tiny particles)!",
      "Electricity flows through wires like water through pipes!",
      "Sources: power plants, batteries, lightning, solar panels!",
      "We use electricity to power almost everything modern!",
      "Lights, computers, phones, TVs, refrigerators - all need electricity!",
      "Lightning is natural electrical energy - super powerful!",
      "Batteries convert chemical energy to electrical energy!",
      "Electricity can be dangerous - never touch exposed wires!",
      "FORM 5: CHEMICAL ENERGY! 🔋🍎",
      "Chemical energy is stored in the BONDS between atoms!",
      "When bonds break, energy is released!",
      "Sources: FOOD (biggest for us!), batteries, gasoline, natural gas!",
      "Your body breaks down food to release energy!",
      "This energy powers everything you do - running, thinking, growing!",
      "Plants store chemical energy from sunlight in leaves and fruits!",
      "Cars use chemical energy from gasoline!",
      "Batteries store chemical energy and release it as electricity!",
      "FORM 6: KINETIC ENERGY! 🏃🚗",
      "Kinetic means MOTION!",
      "Kinetic energy is the energy of MOVEMENT!",
      "ANYTHING that moves has kinetic energy!",
      "Examples: running kid, rolling ball, flying bird, flowing water, blowing wind!",
      "The FASTER something moves, the MORE kinetic energy it has!",
      "A speeding car has more kinetic energy than a slow bike!",
      "BIGGER objects have more kinetic energy than smaller ones at same speed!",
      "A truck has more kinetic energy than a bicycle at the same speed!",
      "Wind turbines capture kinetic energy from wind!",
      "Water wheels capture kinetic energy from flowing water!",
      "FORM 7: POTENTIAL ENERGY! 📍⛰️",
      "Potential means STORED or WAITING!",
      "Potential energy is stored energy ready to be used!",
      "It's like energy that's taking a nap!",
      "Types of Potential Energy:",
      "GRAVITATIONAL: Based on HEIGHT!",
      "A ball at the top of a hill has potential energy!",
      "When it rolls down, potential becomes kinetic!",
      "The higher something is, the more gravitational potential energy!",
      "ELASTIC: Stored in stretched or compressed things!",
      "A stretched rubber band has potential energy!",
      "A compressed spring has potential energy!",
      "Let go, and it snaps back - potential becomes kinetic!",
      "Examples: yo-yo at top (potential), falling down (kinetic)!",
      "Roller coaster at peak (potential), speeding down (kinetic)!",
      "FORM 8: NUCLEAR ENERGY! ☢️⚛️",
      "Nuclear energy is stored in the center (nucleus) of atoms!",
      "When atoms split (fission) or combine (fusion), HUGE energy released!",
      "The SUN uses nuclear fusion - combining hydrogen into helium!",
      "Nuclear power plants use nuclear fission!",
      "This is the most concentrated form of energy!",
      "One uranium pellet has as much energy as a ton of coal!",
      "FORM 9: MECHANICAL ENERGY! 🔧⚙️",
      "Mechanical energy is kinetic + potential energy in machines!",
      "A moving machine has mechanical energy!",
      "Examples: gears turning, wheels rolling, pendulum swinging!",
      "Simple machines (levers, pulleys) transfer mechanical energy!",
      "Your muscles create mechanical energy to move your body!",
      "ENERGY TRANSFORMATIONS: Changing Forms! 🔄",
      "Energy constantly changes from one form to another!",
      "Solar panels: Light → Electrical!",
      "Light bulb: Electrical → Light (and some heat)!",
      "Your body: Chemical (food) → Kinetic (movement) + Heat!",
      "Battery in flashlight: Chemical → Electrical → Light!",
      "Microphone: Sound → Electrical!",
      "Speaker: Electrical → Sound!",
      "Burning wood: Chemical → Heat + Light!",
      "Hydroelectric dam: Kinetic (flowing water) → Electrical!",
      "Car engine: Chemical (gasoline) → Heat → Kinetic (movement)!",
      "Plant: Light (sun) → Chemical (sugar in leaves)!",
      "ENERGY IN DAILY LIFE: 🏠🚗",
      "Morning: Alarm (electrical → sound), lights (electrical → light)!",
      "Breakfast: Toaster (electrical → heat), you eating (chemical stored)!",
      "School bus: Chemical (fuel) → kinetic (movement)!",
      "Playing: Your energy (chemical → kinetic + heat)!",
      "Phone: Battery (chemical → electrical → light, sound)!",
      "Everything you do involves energy transformations!",
      "Remember: Energy is everywhere, always changing forms!",
      "Without energy, there would be no life, no movement, no universe!"
    ],
    questions: [
      {
        question: "What type of energy do we get from food?",
        options: ["Light", "Sound", "Chemical", "Electrical"],
        correctAnswer: 2,
        explanation: "Food stores CHEMICAL energy in its molecular bonds! Your body breaks it down to power everything you do!"
      },
      {
        question: "What is kinetic energy?",
        options: ["Energy of movement", "Stored energy", "Heat energy", "Light energy"],
        correctAnswer: 0,
        explanation: "Kinetic energy is the energy of MOVEMENT! Anything that moves - running, rolling, flying - has kinetic energy!"
      },
      {
        question: "Which provides light energy?",
        options: ["Battery", "Food", "The Sun", "Wind"],
        correctAnswer: 2,
        explanation: "The Sun is our main source of light energy! It provides light and heat to Earth!"
      },
      {
        question: "What type of energy is in a stretched rubber band?",
        options: ["Kinetic", "Chemical", "Potential (elastic)", "Sound"],
        correctAnswer: 2,
        explanation: "A stretched rubber band has ELASTIC POTENTIAL energy! It's stored energy waiting to snap back!"
      },
      {
        question: "What type of energy is sound?",
        options: ["Light", "Vibration energy", "Chemical", "Nuclear"],
        correctAnswer: 1,
        explanation: "Sound is VIBRATION energy! Things vibrate back and forth, creating sound waves we can hear!"
      },
      {
        question: "What happens to energy - can it disappear?",
        options: ["Yes, it disappears", "No, it changes form", "Only some types disappear", "It multiplies"],
        correctAnswer: 1,
        explanation: "Energy can NEVER be created or destroyed - it only changes forms! This is the Law of Conservation of Energy!"
      },
      {
        question: "A ball at the top of a hill has what type of energy?",
        options: ["Kinetic", "Potential", "Chemical", "Sound"],
        correctAnswer: 1,
        explanation: "The ball has POTENTIAL energy based on its height! When it rolls down, it becomes kinetic!"
      },
      {
        question: "What energy transformation happens in a light bulb?",
        options: ["Light to electrical", "Electrical to light", "Sound to light", "Chemical to sound"],
        correctAnswer: 1,
        explanation: "Light bulbs transform ELECTRICAL energy into LIGHT energy (and some heat)!"
      }
    ]
  },
  405: {
    id: 405,
    title: 'Heat & Temperature',
    icon: '🌡️',
    description: 'Understanding hot and cold',
    content: [
      "Let's explore heat and temperature! 🌡️ They're related but different!",
      "Many people think they're the same - but they're not!",
      "Understanding the difference helps us understand weather, cooking, and our bodies!",
      "WHAT IS TEMPERATURE? 🌡️",
      "Temperature measures HOW HOT or HOW COLD something is!",
      "It tells us the AVERAGE energy of particles in something!",
      "We measure temperature with a THERMOMETER!",
      "Temperature scales: Celsius (°C), Fahrenheit (°F), and Kelvin (K)!",
      "Water freezes at 0°C (32°F)!",
      "Water boils at 100°C (212°F)!",
      "Room temperature is about 20-22°C (68-72°F)!",
      "Your body temperature is about 37°C (98.6°F)!",
      "Higher temperature = particles moving FASTER!",
      "Lower temperature = particles moving SLOWER!",
      "WHAT IS HEAT? 🔥",
      "Heat is ENERGY that moves from hot things to cold things!",
      "Heat is not a temperature - it's energy TRANSFER!",
      "When you touch something hot, heat flows INTO your hand!",
      "When you touch something cold, heat flows OUT OF your hand!",
      "Heat always moves in ONE DIRECTION: hot → cold!",
      "This continues until both things are the same temperature!",
      "This is called THERMAL EQUILIBRIUM!",
      "Example: Hot chocolate cools down because heat moves to the cooler air!",
      "Ice cream melts because heat from warm air moves into it!",
      "THE KEY DIFFERENCE: 🤔",
      "Temperature = HOW hot (a measurement)!",
      "Heat = ENERGY moving (a transfer)!",
      "Think of it like this:",
      "Temperature is like a SPEEDOMETER (tells you the speed)!",
      "Heat is like the ENGINE (makes things move)!",
      "HOW HEAT MOVES: Three Ways! 🌊",
      "Heat transfers in THREE main ways!",
      "METHOD 1: CONDUCTION! 🥄",
      "Conduction is heat moving through DIRECT CONTACT!",
      "Touch a hot stove - ouch! Heat conducts into your hand!",
      "When particles touch, faster ones make slower ones move faster!",
      "It's like dominoes - energy passes from one particle to the next!",
      "Metal is an excellent conductor - metal spoon in hot soup gets hot fast!",
      "Wood, plastic, and rubber are poor conductors (insulators)!",
      "That's why pot handles are often wood or plastic!",
      "Conduction works in solids best!",
      "METHOD 2: CONVECTION! 🌀",
      "Convection is heat moving through LIQUIDS and GASES!",
      "Hot liquid/gas RISES, cool liquid/gas SINKS!",
      "This creates a circular motion called a convection current!",
      "Example: Boiling water!",
      "Hot water at bottom rises to top!",
      "Cooler water at top sinks to bottom!",
      "Creates a rolling motion!",
      "Heating your home: Hot air rises, cool air sinks!",
      "Ocean currents are convection - moving warm and cold water!",
      "Weather systems use convection - warm air rises, forms clouds!",
      "Your refrigerator uses convection!",
      "METHOD 3: RADIATION! ☀️",
      "Radiation is heat moving through SPACE as waves!",
      "NO particles needed - can travel through empty space!",
      "The SUN heats Earth through radiation!",
      "There's empty space between sun and Earth, but heat still reaches us!",
      "Sitting by a fire - you feel heat even without touching!",
      "Microwave ovens use radiation to heat food!",
      "Infrared radiation carries heat!",
      "All objects give off some radiation!",
      "CONDUCTORS VS INSULATORS: ⚡❄️",
      "CONDUCTORS: Let heat pass through EASILY!",
      "Metals are great conductors: copper, aluminum, iron, silver!",
      "Water is a decent conductor!",
      "Good for: cooking pans, heat sinks in computers!",
      "INSULATORS: SLOW DOWN or STOP heat transfer!",
      "Air, foam, wool, plastic, wood, fiberglass!",
      "Good for: winter coats, house insulation, coolers!",
      "Thermos bottles use insulators to keep drinks hot OR cold!",
      "Double walls with air/vacuum between - air insulates!",
      "HEAT AND STATES OF MATTER: 🧊💧☁️",
      "Heat changes matter's state!",
      "Add heat → particles move faster!",
      "Solid → Liquid (melting)!",
      "Liquid → Gas (evaporating)!",
      "Remove heat → particles slow down!",
      "Gas → Liquid (condensing)!",
      "Liquid → Solid (freezing)!",
      "Temperature stays constant DURING a phase change!",
      "THERMAL EXPANSION: Size Changes! 📏",
      "Most materials EXPAND (get bigger) when heated!",
      "Particles move faster and need more space!",
      "Materials CONTRACT (get smaller) when cooled!",
      "Examples:",
      "Metal bridges have gaps - room to expand on hot days!",
      "Thermometers work because liquid expands when warm!",
      "Balloon in sun expands, in freezer shrinks!",
      "Water is weird - ice is LESS dense than liquid water!",
      "That's why ice floats!",
      "REAL-WORLD APPLICATIONS: 🌍",
      "Cooking: Add heat to change food (conduction in pan, convection in oven)!",
      "Thermometer: Measures body temperature to check for fever!",
      "Weather: Temperature differences create wind (convection)!",
      "Clothing: Insulators keep you warm in winter!",
      "Refrigerator: Removes heat to keep food cold!",
      "Solar panels: Use radiation from sun for energy!",
      "Thermostat: Controls home temperature!",
      "MEASURING TEMPERATURE: 🌡️",
      "Thermometers contain liquid (mercury or alcohol) that expands with heat!",
      "Digital thermometers use electrical resistance!",
      "Infrared thermometers measure radiation (touchless)!",
      "Absolute zero: -273°C (-459°F) - coldest possible temperature!",
      "At absolute zero, particles stop moving!",
      "HEAT CAPACITY: How Much Heat Needed! 🔥",
      "Different materials need different amounts of heat to change temperature!",
      "Water has HIGH heat capacity - takes lots of heat to warm up!",
      "That's why oceans regulate climate - slow to heat and cool!",
      "Metal has LOW heat capacity - heats up and cools down quickly!",
      "Remember: Temperature tells how hot, heat is energy moving!",
      "Heat always flows from hot to cold until equilibrium!"
    ],
    questions: [
      {
        question: "What measures how hot or cold something is?",
        options: ["Heat", "Temperature", "Energy", "Thermometer only"],
        correctAnswer: 1,
        explanation: "Temperature measures how hot or cold something is! It's the measure, not the energy itself!"
      },
      {
        question: "At what temperature does water freeze?",
        options: ["0°C", "50°C", "100°C", "25°C"],
        correctAnswer: 0,
        explanation: "Water freezes at 0°C (32°F)! Below this temperature, liquid water becomes solid ice!"
      },
      {
        question: "Which direction does heat move?",
        options: ["Cold to hot", "Hot to cold", "It doesn't move", "Random directions"],
        correctAnswer: 1,
        explanation: "Heat ALWAYS moves from hot things to cold things! It flows until both reach the same temperature!"
      },
      {
        question: "What is conduction?",
        options: ["Heat through space", "Heat through direct contact", "Heat through air only", "No heat movement"],
        correctAnswer: 1,
        explanation: "Conduction is heat moving through direct CONTACT! When you touch something hot, heat conducts into your hand!"
      },
      {
        question: "Which is the BEST conductor of heat?",
        options: ["Wood", "Plastic", "Metal", "Foam"],
        correctAnswer: 2,
        explanation: "Metal is the BEST conductor! Heat passes through it easily - that's why metal pans are used for cooking!"
      },
      {
        question: "What is an insulator?",
        options: ["Lets heat pass easily", "Blocks or slows heat", "Only works with cold", "A type of thermometer"],
        correctAnswer: 1,
        explanation: "An insulator BLOCKS or SLOWS heat transfer! Like foam keeping drinks cold or coats keeping you warm!"
      },
      {
        question: "How does the Sun's heat reach Earth?",
        options: ["Conduction", "Convection", "Radiation", "Wind"],
        correctAnswer: 2,
        explanation: "The Sun's heat reaches Earth through RADIATION! Heat waves travel through empty space!"
      },
      {
        question: "What happens when you add heat to ice?",
        options: ["It gets harder", "It melts to water", "Nothing", "It explodes"],
        correctAnswer: 1,
        explanation: "Adding heat to ice makes it MELT into water! Heat makes the particles move faster, changing from solid to liquid!"
      }
    ]
  },
  // Reading Comprehension (501-505)
  501: {
    id: 501,
    title: 'Main Idea & Details',
    icon: '🎯',
    description: 'Finding what text is mostly about',
    content: [
      "Welcome to reading comprehension! 📚 Let's learn to find the MAIN IDEA!",
      "When you read, there's always a BIG idea - the main point!",
      "And there are SMALLER ideas - the details that support it!",
      "Think of it like a tree: 🌳",
      "The TRUNK is the main idea - it holds everything together!",
      "The BRANCHES are the details - they support the main idea!",
      "WHAT IS THE MAIN IDEA? 🎯",
      "The main idea is what the whole passage is MOSTLY about!",
      "It's the BIG PICTURE, the most important point!",
      "Not just one small part - the WHOLE thing!",
      "Usually, the main idea answers: What is this text trying to tell me?",
      "Example passage:",
      "'Dogs make great pets. They are loyal and loving. Dogs can be trained to do tricks. They also protect your home. Taking care of a dog teaches responsibility.'",
      "What's the MAIN idea? 🤔",
      "It's: 'Dogs make great pets!'",
      "That's what the WHOLE paragraph is about!",
      "Everything else explains WHY dogs make great pets!",
      "WHAT ARE SUPPORTING DETAILS? 🌿",
      "Supporting details are FACTS or EXAMPLES that explain the main idea!",
      "They answer questions like WHO, WHAT, WHEN, WHERE, WHY, HOW!",
      "In our dog example:",
      "Detail 1: They are loyal and loving (WHY they're great)",
      "Detail 2: Can be trained to do tricks (WHAT they can do)",
      "Detail 3: They protect your home (HOW they help)",
      "Detail 4: Teach responsibility (WHAT you learn)",
      "Each detail SUPPORTS the main idea!",
      "Without the details, the main idea would be boring!",
      "Without the main idea, the details would be confusing!",
      "They work together! 🤝",
      "STRATEGY 1: The Title Trick! 📖",
      "Often, the TITLE hints at the main idea!",
      "Title: 'Why Penguins Can't Fly'",
      "Main idea is probably about penguins and flying!",
      "But read the passage - the title isn't always the complete main idea!",
      "STRATEGY 2: The First & Last Sentence! 🔍",
      "Many paragraphs state the main idea in the FIRST or LAST sentence!",
      "This sentence is called the TOPIC SENTENCE!",
      "Example:",
      "'Butterflies go through an amazing transformation. First, they are tiny eggs. Then caterpillars hatch and eat leaves. Next, they form a chrysalis. Finally, a beautiful butterfly emerges!'",
      "First sentence = main idea!",
      "'Butterflies go through an amazing transformation' tells the BIG picture!",
      "The rest are details about the transformation!",
      "STRATEGY 3: Ask 'What's this MOSTLY about?' 🤷",
      "Read the whole passage!",
      "Ask yourself: What is mentioned the MOST?",
      "What do most sentences talk about?",
      "That's probably your main idea!",
      "If passage talks about sharks once but ocean pollution 5 times...",
      "Main idea is probably pollution, not sharks!",
      "STRATEGY 4: The Details Test! ✅",
      "Once you think you found the main idea, TEST it!",
      "Do ALL the details support it?",
      "If you said main idea is 'Dogs are fluffy'...",
      "But details talk about loyalty, protection, responsibility...",
      "Then 'fluffy' is NOT the main idea!",
      "Find a bigger idea that covers ALL the details!",
      "COMMON MISTAKES: ⚠️",
      "Mistake 1: Choosing a DETAIL instead of the main idea!",
      "Detail: 'Dogs can do tricks'",
      "Main idea: 'Dogs make great pets' (bigger!)",
      "Mistake 2: Being too GENERAL!",
      "'This is about animals' - too broad!",
      "Better: 'Dogs make great pets' - specific!",
      "Mistake 3: Focusing on one SENTENCE only!",
      "Read the WHOLE passage!",
      "Mistake 4: Adding your own IDEAS!",
      "Stick to what the passage SAYS, not what you think!",
      "PRACTICE PASSAGE 1: 🦈",
      "'Sharks are often misunderstood creatures. They have lived in oceans for over 400 million years. Most sharks don't attack humans. In fact, only a few species are dangerous. Sharks help keep ocean ecosystems healthy by eating sick fish. They are important for ocean balance.'",
      "What's the main idea?",
      "A) Sharks attack humans",
      "B) Sharks are old",
      "C) Sharks are misunderstood and important",
      "D) Some sharks are dangerous",
      "Answer: C! 🎯",
      "The passage is MOSTLY about how sharks are misunderstood and important!",
      "Options A and D are details, but not the main point!",
      "Option B is true but too narrow - only one fact!",
      "PRACTICE PASSAGE 2: 🌮",
      "'Making tacos is fun and easy. First, gather your ingredients: tortillas, meat or beans, cheese, lettuce, and salsa. Next, warm the tortillas in a pan. Then add your fillings. Finally, fold and enjoy! You can customize tacos however you like. That's what makes them perfect for family dinners.'",
      "Main idea?",
      "A) Tacos need tortillas",
      "B) Making tacos is fun and easy",
      "C) Warm the tortillas",
      "D) Tacos are good for dinner",
      "Answer: B! 🎯",
      "First sentence gives us the main idea!",
      "The rest are STEPS (details) that support it!",
      "IMPLIED MAIN IDEAS: 🕵️",
      "Sometimes the main idea is NOT directly stated!",
      "You have to figure it out from the details!",
      "This is called an IMPLIED main idea!",
      "Example:",
      "'Sara woke up early. She brushed her teeth and got dressed quickly. She packed her backpack carefully. She ate breakfast in a hurry. She double-checked she had everything.'",
      "No sentence says the main idea!",
      "But all details point to: 'Sara was preparing carefully for something important!'",
      "You INFERRED (figured out) the main idea from clues!",
      "FINDING IMPLIED MAIN IDEAS:",
      "Look for patterns in the details!",
      "What do they all have in common?",
      "What big idea connects them all?",
      "TOPIC vs MAIN IDEA: 🎭",
      "TOPIC = what the passage is about (1-2 words)",
      "MAIN IDEA = the specific point about the topic (complete sentence)",
      "Example:",
      "Topic: Recycling",
      "Main Idea: Recycling helps protect the environment and save resources",
      "Topic is simpler, main idea is more complete!",
      "DIFFERENT TYPES OF PASSAGES: 📚",
      "STORIES: Main idea is often the lesson or what happens!",
      "'The Tortoise and the Hare' - main idea: Slow and steady wins the race!",
      "INFORMATIONAL: Main idea is the key fact or concept!",
      "'How Volcanoes Form' - main idea: Volcanoes form when magma rises through Earth's crust!",
      "PERSUASIVE: Main idea is the author's opinion/argument!",
      "'Why We Should Recycle' - main idea: We should recycle to help the planet!",
      "SUMMARY SKILLS: 📝",
      "Once you find the main idea and details...",
      "You can write a SUMMARY!",
      "Summary = main idea + most important details (in your own words!)",
      "Keep it short - only the essentials!",
      "READING STRATEGY CHECKLIST: ✅",
      "1. Read the whole passage carefully!",
      "2. Check the title and first/last sentences!",
      "3. Ask 'What is this MOSTLY about?'",
      "4. Find details that support your answer!",
      "5. Make sure your main idea covers the WHOLE passage!",
      "6. Write it as a complete thought!",
      "Remember: Main idea = the BIG picture, details = the proof! 🎯"
    ],
    questions: [
      {
        question: "'Bees are essential for pollination. They help flowers reproduce. Many crops depend on bees. Without bees, we'd have less food. Bees also make honey.' What's the main idea?",
        options: ["Bees make honey", "Flowers need bees", "Bees are essential and important", "Crops depend on bees"],
        correctAnswer: 2,
        explanation: "The main idea is 'Bees are essential and important' - it covers the WHOLE passage! The other options are just details that support this bigger idea!"
      },
      {
        question: "What is a supporting detail?",
        options: ["The main idea", "A fact that explains the main idea", "The title", "Your opinion"],
        correctAnswer: 1,
        explanation: "A supporting detail is a FACT or EXAMPLE that explains and supports the main idea! Details answer who, what, when, where, why, or how!"
      },
      {
        question: "Where is the main idea often found?",
        options: ["Only in the middle", "First or last sentence", "Never stated", "In every sentence"],
        correctAnswer: 1,
        explanation: "The main idea is often in the FIRST or LAST sentence! This is called the topic sentence. But always read the whole passage to be sure!"
      },
      {
        question: "'Lions sleep up to 20 hours a day. They hunt in groups. Lionesses do most hunting. Lions live in groups called prides.' What's this MOSTLY about?",
        options: ["How long lions sleep", "Lions and their lifestyle", "Lionesses hunting", "What prides are"],
        correctAnswer: 1,
        explanation: "The main idea is 'Lions and their lifestyle' - all details are about different aspects of how lions live! Each detail is important but none alone is the main idea!"
      },
      {
        question: "What's the difference between a topic and a main idea?",
        options: ["They're the same", "Topic is 1-2 words, main idea is a complete thought", "Topic is longer", "There is no topic"],
        correctAnswer: 1,
        explanation: "Topic is what the passage is about (1-2 words like 'recycling'), while main idea is a complete thought about the topic (like 'Recycling helps save resources')!"
      },
      {
        question: "What is an IMPLIED main idea?",
        options: ["Stated in first sentence", "Not directly stated - you figure it out", "Written in bold", "The longest sentence"],
        correctAnswer: 1,
        explanation: "An IMPLIED main idea is NOT directly stated! You figure it out by looking at all the details and finding what they have in common!"
      },
      {
        question: "'Jake grabbed his mitt. He ran to the field. His team was warming up. The game would start soon.' What's the IMPLIED main idea?",
        options: ["Jake has a mitt", "Jake is playing baseball", "The team is warming up", "Games start soon"],
        correctAnswer: 1,
        explanation: "The implied main idea is 'Jake is playing baseball'! No sentence says this directly, but all the details (mitt, field, team, game) point to this conclusion!"
      },
      {
        question: "To find the main idea, you should ask:",
        options: ["What's the first word?", "What is this MOSTLY about?", "Who wrote this?", "How long is it?"],
        correctAnswer: 1,
        explanation: "Ask 'What is this MOSTLY about?' to find the main idea! This helps you focus on the BIG picture, not just one small detail!"
      }
    ]
  },

};
