interface Question {
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
}

interface TopicLesson {
  id: number;
  title: string;
  icon: string;
  description: string;
  content: string[];
  questions: Question[];
}

export const lessons: { [key: number]: TopicLesson } = {
  802: {
    id: 802,
    title: 'The Seven Continents',
    icon: '🌎',
    description: 'Earth\'s major landmasses',
    content: [
      "Welcome to THE SEVEN CONTINENTS! 🌎 Let's tour Earth's giant landmasses!",
      "Continents are HUGE areas of land!",
      "Earth has SEVEN continents!",
      "Each one is special and unique!",
      "Let's explore them all!",
      "WHAT IS A CONTINENT? 🌍",
      "A continent is a MASSIVE piece of land!",
      "Much bigger than a country!",
      "Usually has many countries on it!",
      "Surrounded by oceans!",
      "The seven continents are:",
      "1. Asia",
      "2. Africa",
      "3. North America",
      "4. South America",
      "5. Antarctica",
      "6. Europe",
      "7. Australia (or Oceania)",
      "Let's learn about each one!",
      "ASIA: The Giant! 🌏",
      "ASIA is the BIGGEST continent!",
      "LARGEST in area - 17 million square miles!",
      "MOST people - over 4.6 billion!",
      "That's more than half of all humans!",
      "COUNTRIES IN ASIA:",
      "Over 50 countries!",
      "China - most populated country!",
      "India - second most populated!",
      "Japan - island nation, technology leader!",
      "South Korea, Thailand, Vietnam, and many more!",
      "Russia is partly in Asia!",
      "FAMOUS FEATURES:",
      "MOUNT EVEREST - tallest mountain on Earth!",
      "29,029 feet high!",
      "In the Himalayas!",
      "Great Wall of China!",
      "Gobi Desert!",
      "Tropical rainforests in Southeast Asia!",
      "INTERESTING FACTS:",
      "Home to ancient civilizations: China, India, Mesopotamia!",
      "Has every climate - deserts, jungles, tundra!",
      "Most languages spoken!",
      "AFRICA: The Warm Continent! 🦁",
      "AFRICA is the SECOND LARGEST continent!",
      "11.7 million square miles!",
      "Over 1.3 billion people!",
      "54 countries!",
      "FAMOUS COUNTRIES:",
      "Egypt - pyramids and ancient history!",
      "Kenya - safari animals!",
      "South Africa - diamonds and diverse wildlife!",
      "Nigeria - most populous African country!",
      "Ethiopia - ancient kingdom!",
      "FAMOUS FEATURES:",
      "SAHARA DESERT - world's largest hot desert!",
      "Covers much of North Africa!",
      "NILE RIVER - world's longest river!",
      "4,000+ miles!",
      "Tropical rainforests in center!",
      "MOUNT KILIMANJARO - Africa's tallest mountain!",
      "AMAZING WILDLIFE:",
      "Lions, elephants, giraffes!",
      "Zebras, rhinos, hippos!",
      "Gorillas in the mountains!",
      "INTERESTING FACTS:",
      "Where humans first evolved!",
      "Equator runs through middle!",
      "Mostly hot climate!",
      "NORTH AMERICA: Land of Diversity! 🇺🇸",
      "NORTH AMERICA is the THIRD LARGEST!",
      "9.5 million square miles!",
      "Over 580 million people!",
      "23 countries!",
      "FAMOUS COUNTRIES:",
      "UNITED STATES - 50 states!",
      "Where we live!",
      "CANADA - second largest country in world!",
      "Lots of forests and cold weather!",
      "MEXICO - ancient Mayan pyramids!",
      "Plus many Central American and Caribbean nations!",
      "FAMOUS FEATURES:",
      "GRAND CANYON - massive canyon!",
      "ROCKY MOUNTAINS - long mountain range!",
      "NIAGARA FALLS - powerful waterfalls!",
      "Great Lakes - five huge lakes!",
      "MISSISSIPPI RIVER - major river!",
      "CLIMATES:",
      "Tropical in south (Caribbean, Central America)!",
      "Temperate in middle (USA)!",
      "Cold in north (Canada, Alaska)!",
      "SOUTH AMERICA: Land of Amazon! 🌴",
      "SOUTH AMERICA is FOURTH LARGEST!",
      "6.9 million square miles!",
      "Over 430 million people!",
      "12 countries!",
      "FAMOUS COUNTRIES:",
      "BRAZIL - largest country, speaks Portuguese!",
      "Home of Amazon rainforest!",
      "ARGENTINA - tango dancing, beef!",
      "PERU - Machu Picchu ruins!",
      "CHILE - long, skinny country along coast!",
      "FAMOUS FEATURES:",
      "AMAZON RAINFOREST - world's largest rainforest!",
      "Produces 20% of Earth's oxygen!",
      "'Lungs of the planet'!",
      "AMAZON RIVER - second longest river!",
      "Carries most water!",
      "ANDES MOUNTAINS - longest mountain range!",
      "4,300 miles long!",
      "AMAZING WILDLIFE:",
      "Jaguars, anacondas, piranhas!",
      "Toucans, macaws, sloths!",
      "Llamas, alpacas!",
      "ANTARCTICA: The Frozen Continent! ❄️🐧",
      "ANTARCTICA is FIFTH LARGEST!",
      "5.5 million square miles!",
      "But almost NO permanent people!",
      "Only scientists at research stations!",
      "A FEW thousand in summer!",
      "A FEW hundred in winter!",
      "No countries - international territory!",
      "EXTREME FACTS:",
      "COLDEST continent!",
      "Lowest temp recorded: -128.6°F!",
      "DRIEST continent!",
      "Almost no rain - it's a desert!",
      "WINDIEST continent!",
      "Winds up to 200 mph!",
      "98% covered in ICE!",
      "Ice up to 3 miles thick!",
      "Contains 70% of Earth's fresh water!",
      "(But it's frozen!)!",
      "WILDLIFE:",
      "PENGUINS - lots of them!",
      "Emperor penguins, Adélie penguins!",
      "Seals and sea lions!",
      "Whales visit the waters!",
      "INTERESTING FACTS:",
      "SUN doesn't set for months in summer!",
      "SUN doesn't rise for months in winter!",
      "No trees grow here!",
      "EUROPE: The Historic Continent! 🏰",
      "EUROPE is SIXTH LARGEST!",
      "3.9 million square miles!",
      "About 750 million people!",
      "About 50 countries!",
      "FAMOUS COUNTRIES:",
      "UNITED KINGDOM - England, Scotland, Wales, Northern Ireland!",
      "FRANCE - Eiffel Tower, art, fashion!",
      "GERMANY - engineering, castles!",
      "ITALY - ancient Rome, pizza, pasta!",
      "SPAIN - flamenco, bullfighting!",
      "RUSSIA - partly in Europe, partly in Asia!",
      "Largest country in world!",
      "And many more!",
      "FAMOUS FEATURES:",
      "ALPS - major mountain range!",
      "Great for skiing!",
      "Mediterranean Sea!",
      "Many islands!",
      "HISTORICAL IMPORTANCE:",
      "Ancient Greece and Rome!",
      "Renaissance art and science!",
      "Industrial Revolution!",
      "AUSTRALIA/OCEANIA: The Island Continent! 🦘",
      "AUSTRALIA is SMALLEST continent!",
      "3 million square miles!",
      "About 43 million people!",
      "(If counting all Oceania: more countries and islands!)!",
      "AUSTRALIA (the country):",
      "Takes up most of the continent!",
      "Capital: Canberra!",
      "Biggest city: Sydney!",
      "Great Barrier Reef - largest coral reef!",
      "OUTBACK - vast desert interior!",
      "UNIQUE ANIMALS:",
      "KANGAROOS - hop around!",
      "KOALAS - eat eucalyptus!",
      "PLATYPUS - weird mammal that lays eggs!",
      "Lots of deadly snakes and spiders!",
      "OCEANIA includes:",
      "AUSTRALIA!",
      "NEW ZEALAND - beautiful islands!",
      "PACIFIC ISLANDS:",
      "Fiji, Samoa, Tonga!",
      "Papua New Guinea!",
      "Thousands of islands!",
      "COMPARING THE CONTINENTS: 📊",
      "LARGEST: Asia!",
      "SMALLEST: Australia!",
      "MOST PEOPLE: Asia!",
      "FEWEST PEOPLE: Antarctica!",
      "HOTTEST: Africa (on average)!",
      "COLDEST: Antarctica!",
      "DRIEST: Antarctica!",
      "WETTEST: South America (Amazon)!",
      "CONTINENTAL CONNECTIONS: 🌉",
      "Some continents are connected!",
      "AFRICA and ASIA:",
      "Connected at Suez Canal area!",
      "NORTH and SOUTH AMERICA:",
      "Connected at Panama!",
      "EUROPE and ASIA:",
      "Actually one landmass called EURASIA!",
      "Ural Mountains divide them!",
      "But culturally different!",
      "WHY CONTINENTS MATTER: ✨",
      "Help us organize our planet!",
      "Each has unique cultures!",
      "Different climates and environments!",
      "Home to different animals and plants!",
      "Different histories and peoples!",
      "All seven continents make our world diverse and amazing! 🌍✨"
    ],
    questions: [
      {
        question: "How many continents are there?",
        options: ["5", "6", "7", "8"],
        correctAnswer: 2,
        explanation: "There are SEVEN continents on Earth! Asia, Africa, North America, South America, Antarctica, Europe, and Australia/Oceania!"
      },
      {
        question: "Which is the largest continent?",
        options: ["Africa", "Asia", "North America", "Europe"],
        correctAnswer: 1,
        explanation: "ASIA is the largest continent! It covers 17 million square miles and has over 4.6 billion people - more than half of all humans!"
      },
      {
        question: "Which continent is covered in ice?",
        options: ["Australia", "Europe", "Antarctica", "Africa"],
        correctAnswer: 2,
        explanation: "ANTARCTICA is covered in ice and is the coldest continent! 98% is ice, some up to 3 miles thick! Almost no people live there!"
      },
      {
        question: "Which continent has the Amazon rainforest?",
        options: ["Africa", "South America", "Asia", "Australia"],
        correctAnswer: 1,
        explanation: "SOUTH AMERICA has the Amazon rainforest! It's the world's largest rainforest and produces 20% of Earth's oxygen - called 'the lungs of the planet'!"
      },
      {
        question: "Which is the smallest continent?",
        options: ["Europe", "Australia", "Antarctica", "South America"],
        correctAnswer: 1,
        explanation: "AUSTRALIA is the smallest continent! Only 3 million square miles. It has unique animals like kangaroos, koalas, and platypuses!"
      },
      {
        question: "Which continent has Mount Everest?",
        options: ["Asia", "South America", "Africa", "Europe"],
        correctAnswer: 0,
        explanation: "Mount Everest is in ASIA! It's in the Himalayas on the border of Nepal and China. At 29,029 feet, it's Earth's tallest mountain!"
      },
      {
        question: "Which continent do we live on?",
        options: ["Europe", "Asia", "North America", "South America"],
        correctAnswer: 2,
        explanation: "We live on NORTH AMERICA! It includes the United States, Canada, Mexico, and Central American and Caribbean countries!"
      },
      {
        question: "Which continent has the most countries?",
        options: ["Africa", "Europe", "Asia", "South America"],
        correctAnswer: 0,
        explanation: "AFRICA has the most countries with 54! It's also the second largest continent with incredible wildlife and the Sahara Desert!"
      }
    ]
  },
  803: {
    id: 803,
    title: 'Oceans & Landforms',
    icon: '🏔️',
    description: 'Earth\'s water and land features',
    content: [
      "Welcome to OCEANS & LANDFORMS! 🌊🏔️ Earth's amazing features!",
      "Our planet has incredible water bodies and land shapes!",
      "Let's explore them all!",
      "THE FIVE OCEANS: Earth's Blue! 🌊",
      "Oceans cover 70% of Earth!",
      "Earth has FIVE oceans!",
      "1. PACIFIC OCEAN - Biggest!",
      "Larger than all land combined!",
      "Between Asia and Americas!",
      "Has Mariana Trench - deepest spot on Earth!",
      "36,000 feet deep!",
      "2. ATLANTIC OCEAN - Second biggest!",
      "Between Americas and Europe/Africa!",
      "Explorers crossed it to Americas!",
      "3. INDIAN OCEAN - Third biggest!",
      "South of Asia!",
      "Warmest ocean!",
      "4. ARCTIC OCEAN - Around North Pole!",
      "Coldest, mostly ice!",
      "Home to polar bears!",
      "5. SOUTHERN OCEAN - Around Antarctica!",
      "Very cold and windy!",
      "Penguins and whales!",
      "MOUNTAINS: Touching the Sky! ⛰️",
      "Mountains are tall rocky land!",
      "MOUNT EVEREST - Tallest!",
      "29,029 feet high!",
      "In Himalayas (Asia)!",
      "K2 - Second tallest!",
      "MOUNT KILIMANJARO - Tallest in Africa!",
      "MOUNT DENALI - Tallest in North America!",
      "Mountain ranges: Himalayas, Andes, Rockies, Alps!",
      "Form when tectonic plates crash!",
      "Takes millions of years!",
      "VALLEYS: Low Between Highs! 🏞️",
      "Valleys are low areas between mountains!",
      "Rivers often run through them!",
      "GRAND CANYON - Massive valley!",
      "Carved by Colorado River!",
      "277 miles long, 1 mile deep!",
      "Takes millions of years to form!",
      "PLAINS: Flat and Wide! 🌾",
      "Plains are large flat areas!",
      "Perfect for farming!",
      "GREAT PLAINS - Central USA!",
      "Grows wheat and corn!",
      "'America's breadbasket'!",
      "DESERTS: Dry and Extreme! 🏜️",
      "Deserts get less than 10 inches rain per year!",
      "Can be HOT or COLD!",
      "SAHARA - World's largest hot desert!",
      "In North Africa!",
      "Size of USA!",
      "GOBI - Large cold desert in Asia!",
      "ANTARCTICA - Largest cold desert!",
      "It's a desert because so little precipitation!",
      "ISLANDS: Surrounded by Water! 🏝️",
      "Islands are land completely surrounded by water!",
      "GREENLAND - World's biggest island!",
      "HAWAII - Volcanic islands!",
      "Formed from underwater volcanoes!",
      "PENINSULAS: Almost Islands!",
      "Land surrounded by water on three sides!",
      "FLORIDA - USA!",
      "ITALY - Boot-shaped!",
      "RIVERS: Flowing Water! 🌊",
      "Rivers flow from high to low!",
      "NILE - World's longest, 4,130 miles!",
      "In Africa!",
      "AMAZON - Second longest!",
      "Carries most water!",
      "In South America!",
      "MISSISSIPPI - Longest in North America!",
      "LAKES: Standing Water! 💧",
      "Lakes are water surrounded by land!",
      "CASPIAN SEA - World's largest lake!",
      "LAKE SUPERIOR - Largest of Great Lakes!",
      "VOLCANOES: Earth's Fire! 🌋",
      "Volcanoes can erupt!",
      "Magma comes from inside Earth!",
      "MOUNT VESUVIUS - Buried Pompeii in 79 AD!",
      "MOUNT ST. HELENS - Erupted in 1980!",
      "PLATEAUS: High and Flat! 🏔️",
      "Flat areas at high elevation!",
      "TIBETAN PLATEAU - 'Roof of the World'!",
      "Highest and largest!",
      "COLORADO PLATEAU - Has Grand Canyon!",
      "GLACIERS: Rivers of Ice! ❄️",
      "Huge masses of ice that move!",
      "In Antarctica, Greenland, high mountains!",
      "Carved valleys long ago!",
      "WHY LANDFORMS MATTER: ✨",
      "Shape where people live!",
      "Affect weather!",
      "Provide resources!",
      "Make Earth diverse!",
      "From deepest ocean to highest mountain - Earth is amazing! 🌍✨"
    ],
    questions: [
      {
        question: "Which is the largest ocean?",
        options: ["Atlantic", "Indian", "Pacific", "Arctic"],
        correctAnswer: 2,
        explanation: "The PACIFIC OCEAN is the largest! It's bigger than all land on Earth combined! It's between Asia and the Americas!"
      },
      {
        question: "What is the tallest mountain on Earth?",
        options: ["Mount Kilimanjaro", "Mount Everest", "Mount Fuji", "Mount McKinley"],
        correctAnswer: 1,
        explanation: "MOUNT EVEREST is the tallest mountain at 29,029 feet! It's in the Himalayas between Nepal and China!"
      },
      {
        question: "What is land surrounded by water called?",
        options: ["Peninsula", "Island", "Valley", "Plain"],
        correctAnswer: 1,
        explanation: "An ISLAND is land completely surrounded by water! Greenland is the world's largest island. Hawaii is made of volcanic islands!"
      },
      {
        question: "What is the world's longest river?",
        options: ["Amazon", "Nile", "Mississippi", "Yangtze"],
        correctAnswer: 1,
        explanation: "The NILE is the world's longest river at 4,130 miles! It flows through Africa and was essential to ancient Egypt!"
      },
      {
        question: "What covers 70% of Earth's surface?",
        options: ["Land", "Deserts", "Oceans", "Ice"],
        correctAnswer: 2,
        explanation: "OCEANS cover 70% of Earth's surface! That's why Earth looks blue from space. The five oceans are all connected!"
      },
      {
        question: "What is the largest hot desert?",
        options: ["Gobi", "Mojave", "Sahara", "Australian"],
        correctAnswer: 2,
        explanation: "The SAHARA is the world's largest hot desert! It covers much of North Africa and is about the size of the United States!"
      },
      {
        question: "What is a flat area good for farming called?",
        options: ["Mountain", "Valley", "Plain", "Island"],
        correctAnswer: 2,
        explanation: "PLAINS are flat areas perfect for farming! The Great Plains in the USA are called 'America's breadbasket' because they grow so much food!"
      },
      {
        question: "What is the deepest spot on Earth?",
        options: ["Grand Canyon", "Death Valley", "Mariana Trench", "Dead Sea"],
        correctAnswer: 2,
        explanation: "The MARIANA TRENCH in the Pacific Ocean is the deepest spot at 36,000 feet! That's deeper than Mount Everest is tall!"
      }
    ]
  },
  804: {
    id: 804,
    title: 'Countries & Capitals',
    icon: '🏙️',
    description: 'Nations around the world',
    content: [
      "Welcome to COUNTRIES & CAPITALS! 🏙️ Let's explore the nations of our world!",
      "Earth has about 195 countries!",
      "Each one is unique and special!",
      "WHAT IS A COUNTRY? 🗺️",
      "A COUNTRY is an area with:",
      "Its own GOVERNMENT!",
      "Its own BORDERS!",
      "Its own LAWS!",
      "Its own FLAG!",
      "Often its own LANGUAGE!",
      "Countries range from tiny to huge!",
      "WHAT IS A CAPITAL? 🏛️",
      "A CAPITAL is the main city of a country!",
      "Where the government is located!",
      "Where leaders work!",
      "NOT always the biggest city!",
      "But always the political center!",
      "NORTH AMERICA COUNTRIES: 🌎",
      "UNITED STATES 🇺🇸",
      "Capital: WASHINGTON, D.C.!",
      "NOT a state - special district!",
      "Has White House, Capitol Building!",
      "50 states!",
      "CANADA 🇨🇦",
      "Capital: OTTAWA!",
      "Second largest country in world!",
      "Bilingual: English and French!",
      "MEXICO 🇲🇽",
      "Capital: MEXICO CITY!",
      "One of the largest cities in world!",
      "Ancient Aztec ruins!",
      "SOUTH AMERICA COUNTRIES: 🌎",
      "BRAZIL 🇧🇷",
      "Capital: BRASÍLIA!",
      "Largest country in South America!",
      "Speaks Portuguese!",
      "ARGENTINA 🇦🇷",
      "Capital: BUENOS AIRES!",
      "Famous for tango!",
      "PERU 🇵🇪",
      "Capital: LIMA!",
      "Has Machu Picchu!",
      "CHILE 🇨🇱",
      "Capital: SANTIAGO!",
      "Long, skinny country!",
      "EUROPE COUNTRIES: 🇪🇺",
      "UNITED KINGDOM 🇬🇧",
      "Capital: LONDON!",
      "Big Ben, Tower Bridge!",
      "England, Scotland, Wales, Northern Ireland!",
      "FRANCE 🇫🇷",
      "Capital: PARIS!",
      "Eiffel Tower, Louvre Museum!",
      "City of Lights!",
      "GERMANY 🇩🇪",
      "Capital: BERLIN!",
      "Berlin Wall history!",
      "ITALY 🇮🇹",
      "Capital: ROME!",
      "Ancient Roman Empire!",
      "Colosseum, Vatican City!",
      "SPAIN 🇪🇸",
      "Capital: MADRID!",
      "Flamenco dancing!",
      "RUSSIA 🇷🇺",
      "Capital: MOSCOW!",
      "Largest country in world!",
      "Spans Europe and Asia!",
      "Red Square, Kremlin!",
      "ASIA COUNTRIES: 🌏",
      "CHINA 🇨🇳",
      "Capital: BEIJING!",
      "Most populated country!",
      "Forbidden City, Great Wall!",
      "JAPAN 🇯🇵",
      "Capital: TOKYO!",
      "One of world's largest cities!",
      "Island nation, technology leader!",
      "INDIA 🇮🇳",
      "Capital: NEW DELHI!",
      "Second most populated!",
      "Taj Mahal!",
      "SOUTH KOREA 🇰🇷",
      "Capital: SEOUL!",
      "Technology and K-pop!",
      "THAILAND 🇹🇭",
      "Capital: BANGKOK!",
      "Beautiful temples!",
      "AFRICA COUNTRIES: 🌍",
      "EGYPT 🇪🇬",
      "Capital: CAIRO!",
      "Near the pyramids!",
      "KENYA 🇰🇪",
      "Capital: NAIROBI!",
      "Amazing wildlife!",
      "SOUTH AFRICA 🇿🇦",
      "Capitals: Three!",
      "PRETORIA (executive)!",
      "CAPE TOWN (legislative)!",
      "BLOEMFONTEIN (judicial)!",
      "NIGERIA 🇳🇬",
      "Capital: ABUJA!",
      "Most populous African country!",
      "OCEANIA COUNTRIES: 🦘",
      "AUSTRALIA 🇦🇺",
      "Capital: CANBERRA!",
      "NOT Sydney (biggest city)!",
      "Unique wildlife!",
      "NEW ZEALAND 🇳🇿",
      "Capital: WELLINGTON!",
      "Beautiful islands!",
      "INTERESTING CAPITAL FACTS: 🤔",
      "Smallest capital: VATICAN CITY!",
      "Entire country is one city!",
      "Only about 800 people!",
      "Highest capital: LA PAZ, Bolivia!",
      "Over 11,000 feet elevation!",
      "Northernmost capital: REYKJAVIK, Iceland!",
      "Near Arctic Circle!",
      "Some countries changed capitals!",
      "BRAZIL: Rio de Janeiro → Brasília!",
      "TURKEY: Istanbul → Ankara!",
      "LARGEST vs CAPITAL: 📊",
      "Biggest city NOT always capital!",
      "USA: New York City vs Washington, D.C.!",
      "CANADA: Toronto vs Ottawa!",
      "AUSTRALIA: Sydney vs Canberra!",
      "BRAZIL: São Paulo vs Brasília!",
      "COUNTRY SIZES: 📏",
      "LARGEST: Russia!",
      "SMALLEST: Vatican City!",
      "Most populous: China and India!",
      "Least populous: Vatican City!",
      "FLAGS: National Symbols! 🚩",
      "Every country has a unique flag!",
      "Colors and symbols represent history!",
      "USA: Stars and stripes!",
      "50 stars = 50 states!",
      "13 stripes = original colonies!",
      "CANADA: Red with maple leaf!",
      "JAPAN: White with red circle (rising sun)!",
      "FLAGS tell stories!",
      "BORDERS: Where Countries Meet! 🗺️",
      "Countries have borders!",
      "Some natural: rivers, mountains!",
      "Some drawn: straight lines!",
      "Longest border: USA and Canada!",
      "5,525 miles!",
      "LANGUAGES AROUND THE WORLD: 🗣️",
      "Over 7,000 languages!",
      "Most spoken: Chinese (Mandarin)!",
      "English, Spanish, Hindi, Arabic!",
      "Some countries have multiple official languages!",
      "Canada: English & French!",
      "Switzerland: German, French, Italian, Romansh!",
      "WHY COUNTRIES MATTER: ✨",
      "Organize the world!",
      "Different governments and laws!",
      "Unique cultures and traditions!",
      "Pride and identity!",
      "Work together for peace!",
      "Learning about countries helps us understand our diverse world! 🌍✨"
    ],
    questions: [
      {
        question: "What is a country's capital?",
        options: ["The biggest city", "The main government city", "The oldest city", "The richest city"],
        correctAnswer: 1,
        explanation: "A CAPITAL is the main city where a country's GOVERNMENT is located! It's the political center where leaders work. Not always the biggest city!"
      },
      {
        question: "What is the capital of the United States?",
        options: ["New York", "Los Angeles", "Washington, D.C.", "Chicago"],
        correctAnswer: 2,
        explanation: "WASHINGTON, D.C. is the capital of the United States! It has the White House and Capitol Building. It's not a state - it's a special district!"
      },
      {
        question: "About how many countries are in the world?",
        options: ["50", "100", "195", "500"],
        correctAnswer: 2,
        explanation: "There are about 195 countries in the world! Each has its own government, borders, flag, and often its own language!"
      },
      {
        question: "What is the capital of France?",
        options: ["London", "Paris", "Rome", "Berlin"],
        correctAnswer: 1,
        explanation: "PARIS is the capital of France! It's called the 'City of Lights' and is home to the Eiffel Tower and Louvre Museum!"
      },
      {
        question: "Which is the largest country in the world?",
        options: ["China", "USA", "Russia", "Canada"],
        correctAnswer: 2,
        explanation: "RUSSIA is the largest country in the world! It spans both Europe and Asia. Its capital is Moscow with the famous Red Square!"
      },
      {
        question: "What is the capital of Japan?",
        options: ["Beijing", "Seoul", "Tokyo", "Bangkok"],
        correctAnswer: 2,
        explanation: "TOKYO is the capital of Japan! It's one of the world's largest cities and a leader in technology. Japan is an island nation!"
      },
      {
        question: "Which country has THREE capitals?",
        options: ["USA", "South Africa", "Australia", "Brazil"],
        correctAnswer: 1,
        explanation: "SOUTH AFRICA has three capitals! Pretoria (executive), Cape Town (legislative), and Bloemfontein (judicial) - each for different government functions!"
      },
      {
        question: "What is the smallest country?",
        options: ["Monaco", "Malta", "Vatican City", "Luxembourg"],
        correctAnswer: 2,
        explanation: "VATICAN CITY is the smallest country! The entire country is just one city with only about 800 people. It's also the smallest capital!"
      }
    ]
  },
  805: {
    id: 805,
    title: 'World Cultures',
    icon: '🎭',
    description: 'Different ways people live',
    content: [
      "Welcome to WORLD CULTURES! 🎭 Let's celebrate the diversity of our world!",
      "Every person has a culture!",
      "Culture makes us special!",
      "WHAT IS CULTURE? 🌍",
      "CULTURE is a way of life!",
      "It includes:",
      "TRADITIONS we practice!",
      "BELIEFS we hold!",
      "CUSTOMS we follow!",
      "FOOD we eat!",
      "LANGUAGES we speak!",
      "MUSIC we enjoy!",
      "ART we create!",
      "HOLIDAYS we celebrate!",
      "Culture is passed from generation to generation!",
      "Like a gift from your ancestors!",
      "LANGUAGES: Speaking Around the World! 🗣️",
      "Over 7,000 languages spoken on Earth!",
      "CHINESE (Mandarin): Most speakers!",
      "Over 1 billion people!",
      "ENGLISH: Widely spoken worldwide!",
      "SPANISH: 500+ million speakers!",
      "HINDI: Spoken in India!",
      "ARABIC: Middle East and North Africa!",
      "Many countries have multiple languages!",
      "Language connects communities!",
      "FOOD AROUND THE WORLD: 🍽️",
      "Food is culture you can taste!",
      "SUSHI 🍣 - Japan!",
      "Rice, fish, seaweed!",
      "TACOS 🌮 - Mexico!",
      "Tortillas with fillings!",
      "PIZZA 🍕 - Italy!",
      "Flatbread with toppings!",
      "CURRY 🍛 - India!",
      "Spicy stews with rice!",
      "CROISSANT 🥐 - France!",
      "Buttery, flaky pastry!",
      "DUMPLINGS 🥟 - China!",
      "Filled pockets of dough!",
      "FALAFEL 🧆 - Middle East!",
      "Fried chickpea balls!",
      "Food tells stories about geography and history!",
      "HOLIDAYS & CELEBRATIONS: 🎉",
      "Every culture has special days!",
      "CHRISTMAS 🎄",
      "Christian holiday!",
      "Celebrates Jesus's birth!",
      "December 25!",
      "HANUKKAH 🕎",
      "Jewish Festival of Lights!",
      "8 days, lighting menorah!",
      "DIWALI 🪔",
      "Hindu Festival of Lights!",
      "Celebrates good over evil!",
      "Lamps, fireworks, sweets!",
      "LUNAR NEW YEAR 🏮",
      "Celebrated in many Asian countries!",
      "Dragon dances, red envelopes!",
      "RAMADAN & EID 🌙",
      "Islamic holy month of fasting!",
      "Eid celebration after!",
      "DÍA DE LOS MUERTOS 💀",
      "Day of the Dead - Mexico!",
      "Honors ancestors!",
      "Colorful skulls, marigolds!",
      "Holidays bring families together!",
      "TRADITIONAL CLOTHING: 👘",
      "Special outfits tell stories!",
      "KIMONO 👘 - Japan!",
      "Beautiful robes with wide sleeves!",
      "SARI 🥻 - India!",
      "Long fabric wrapped elegantly!",
      "KILT 🏴󠁧󠁢󠁳󠁣󠁴󠁿 - Scotland!",
      "Plaid skirt worn by men!",
      "PONCHO 🇲🇽 - Latin America!",
      "Warm blanket with hole for head!",
      "DASHIKI 🇳🇬 - West Africa!",
      "Colorful loose-fitting shirt!",
      "Clothing reflects climate and history!",
      "MUSIC & DANCE: 🎵",
      "Every culture has rhythm!",
      "FLAMENCO 💃 - Spain!",
      "Passionate guitar and dancing!",
      "SAMBA 🇧🇷 - Brazil!",
      "Energetic carnival music!",
      "BHANGRA 🇮🇳 - India!",
      "Lively Punjabi folk dance!",
      "TANGO 🇦🇷 - Argentina!",
      "Romantic partner dance!",
      "K-POP 🇰🇷 - South Korea!",
      "Modern pop music and dance!",
      "REGGAE 🇯🇲 - Jamaica!",
      "Bob Marley made it famous!",
      "Music brings joy across cultures!",
      "ART & CRAFTS: 🎨",
      "CALLIGRAPHY - China, Japan, Arab world!",
      "Beautiful artistic writing!",
      "ORIGAMI 🦢 - Japan!",
      "Paper folding art!",
      "HENNA 🖐️ - India, Middle East!",
      "Temporary body art!",
      "POTTERY - Native American, Greek!",
      "Creating with clay!",
      "TEXTILES - Peru, Guatemala!",
      "Weaving colorful patterns!",
      "Art preserves cultural stories!",
      "RELIGION & BELIEFS: 🙏",
      "Many different religions!",
      "CHRISTIANITY ✝️!",
      "Follows teachings of Jesus!",
      "ISLAM ☪️!",
      "Follows teachings of Muhammad!",
      "HINDUISM 🕉️!",
      "Ancient religion from India!",
      "BUDDHISM ☸️!",
      "Follows teachings of Buddha!",
      "JUDAISM ✡️!",
      "Ancient Abrahamic religion!",
      "And many more!",
      "All teach kindness and peace!",
      "FAMILY STRUCTURES: 👨‍👩‍👧‍👦",
      "Families look different everywhere!",
      "NUCLEAR FAMILY: Parents and children!",
      "EXTENDED FAMILY: Grandparents, aunts, uncles together!",
      "Common in many cultures!",
      "COMMUNAL LIVING: Whole village helps raise children!",
      "Love makes a family!",
      "GREETINGS: Saying Hello! 👋",
      "Different ways to greet!",
      "HANDSHAKE 🤝 - Western countries!",
      "BOW 🙇 - Japan!",
      "Shows respect!",
      "NAMASTE 🙏 - India!",
      "Hands together, bow!",
      "KISS ON CHEEK 😘 - France, Italy!",
      "HONGI 👃 - Māori (New Zealand)!",
      "Pressing noses together!",
      "SPORTS & GAMES: ⚽",
      "SOCCER/FOOTBALL ⚽ - Worldwide!",
      "Most popular sport!",
      "CRICKET 🏏 - India, England, Australia!",
      "BASEBALL ⚾ - USA, Japan!",
      "SUMO WRESTLING 🇯🇵 - Japan!",
      "Traditional sport!",
      "CAPOEIRA 🇧🇷 - Brazil!",
      "Martial art that looks like dance!",
      "Play brings people together!",
      "SCHOOLS & EDUCATION: 📚",
      "Children learn everywhere!",
      "Some schools have uniforms!",
      "Some learn in different languages!",
      "Some go to school year-round!",
      "Some have long summer breaks!",
      "Education looks different but is valued everywhere!",
      "CULTURAL RESPECT: ❤️",
      "APPRECIATION vs APPROPRIATION!",
      "APPRECIATION: Learning and respecting!",
      "Asking questions!",
      "Participating respectfully!",
      "APPROPRIATION: Taking without respect!",
      "Treating culture like costume!",
      "Always be respectful!",
      "WHAT WE SHARE: 🌈",
      "All humans need love!",
      "All families care for children!",
      "All cultures tell stories!",
      "All people make music!",
      "All communities celebrate!",
      "We're more alike than different!",
      "CELEBRATING DIVERSITY: 🎊",
      "Different cultures make world beautiful!",
      "Like a garden with many flowers!",
      "Each adds unique beauty!",
      "We can learn from each other!",
      "Trying new foods!",
      "Learning new words!",
      "Hearing new music!",
      "Understanding different viewpoints!",
      "Diversity makes us stronger!",
      "YOUR CULTURE MATTERS: ⭐",
      "You have a culture too!",
      "Maybe you celebrate certain holidays!",
      "Maybe you eat special foods!",
      "Maybe your family has traditions!",
      "Your culture is part of who you are!",
      "Be proud of your heritage!",
      "BEING A GLOBAL CITIZEN: 🌍",
      "We all share one Earth!",
      "Respecting all cultures!",
      "Learning about differences!",
      "Finding common ground!",
      "Building bridges, not walls!",
      "Together we make the world better!",
      "Our diverse world is beautiful! Let's celebrate what makes each culture special while remembering we're all human! 🌍❤️✨"
    ],
    questions: [
      {
        question: "What is culture?",
        options: ["Only the food people eat", "A way of life including traditions and beliefs", "The language people speak", "The clothes people wear"],
        correctAnswer: 1,
        explanation: "CULTURE is a way of life! It includes traditions, beliefs, customs, food, language, music, art, holidays, and more - everything that makes a group special!"
      },
      {
        question: "About how many languages are spoken in the world?",
        options: ["500", "2,000", "7,000", "10,000"],
        correctAnswer: 2,
        explanation: "Over 7,000 languages are spoken on Earth! Chinese (Mandarin) has the most speakers, but there are thousands of other languages connecting communities!"
      },
      {
        question: "What is Diwali?",
        options: ["A Japanese festival", "Hindu Festival of Lights", "A type of food", "A traditional dance"],
        correctAnswer: 1,
        explanation: "DIWALI is the Hindu Festival of Lights! It celebrates good over evil with lamps, fireworks, and sweets. It's one of many beautiful holidays around the world!"
      },
      {
        question: "Which country celebrates Día de los Muertos (Day of the Dead)?",
        options: ["Spain", "Brazil", "Mexico", "Italy"],
        correctAnswer: 2,
        explanation: "MEXICO celebrates Día de los Muertos (Day of the Dead)! It honors ancestors with colorful skulls, marigolds, and altars - a beautiful tradition!"
      },
      {
        question: "What is a sari?",
        options: ["A Japanese robe", "An Indian wrapped garment", "A Mexican blanket", "A Scottish skirt"],
        correctAnswer: 1,
        explanation: "A SARI is traditional Indian clothing! It's a long piece of fabric wrapped elegantly around the body - beautiful and colorful!"
      },
      {
        question: "What is the difference between cultural appreciation and appropriation?",
        options: ["There is no difference", "Appreciation is respectful learning; appropriation takes without respect", "Appropriation is better", "They mean the same thing"],
        correctAnswer: 1,
        explanation: "APPRECIATION means learning about and respecting other cultures! APPROPRIATION means taking from a culture without respect, like treating it as a costume. Always be respectful!"
      },
      {
        question: "What do ALL cultures have in common?",
        options: ["They all speak the same language", "They all have the same holidays", "They all tell stories and celebrate", "They all eat the same food"],
        correctAnswer: 2,
        explanation: "ALL cultures tell stories, make music, celebrate, and care for children! We're more alike than different - all humans need love, family, and community!"
      },
      {
        question: "Why is cultural diversity important?",
        options: ["It's not important", "It makes the world beautiful and helps us learn", "Only one culture should exist", "It's too confusing"],
        correctAnswer: 1,
        explanation: "DIVERSITY makes the world beautiful! Like a garden with many flowers, each culture adds unique beauty. We learn from each other and become stronger together! 🌈"
      }
    ]
  }

};
